Repository OCA/e-commerce, pull requests merged in 2018-10, with the labels that each got.

#209 [FIX] website_sale_affiliate: Handle case of no session
  website_sale_affiliate/README.rst
  website_sale_affiliate/__manifest__.py
  website_sale_affiliate/models/sale_affiliate_request.py
  website_sale_affiliate/tests/test_sale_affiliate_request.py
Labels: bug

#244 [FIX][11.0][website_sale_hide_price] Disable Add to cart option to prevent show prices in cart
  website_sale_hide_price/README.rst
  website_sale_hide_price/__manifest__.py
  website_sale_hide_price/views/website_sale_template.xml
Labels: needs review

#245 [ADD] website_sale_firstname
  oca_dependencies.txt
  website_sale_firstname/__init__.py
  website_sale_firstname/__manifest__.py
  website_sale_firstname/controllers/__init__.py
  website_sale_firstname/controllers/main.py
  website_sale_firstname/data/data.xml
  website_sale_firstname/readme/CONTRIBUTORS.rst
  website_sale_firstname/readme/CREDITS.rst
  website_sale_firstname/readme/DESCRIPTION.rst
Labels: question
