Repository OCA/e-commerce, pull requests merged in 2019-05, with the labels that each got.

#286 [12.0][MIG] website_sale_checkout_country_vat
  website_sale_checkout_country_vat/README.rst
  website_sale_checkout_country_vat/__init__.py
  website_sale_checkout_country_vat/__manifest__.py
  website_sale_checkout_country_vat/i18n/es.po
  website_sale_checkout_country_vat/i18n/website_sale_checkout_country_vat.pot
  website_sale_checkout_country_vat/readme/CONFIGURE.rst
  website_sale_checkout_country_vat/readme/CONTRIBUTORS.rst
  website_sale_checkout_country_vat/readme/DESCRIPTION.rst
  website_sale_checkout_country_vat/readme/USAGE.rst
  website_sale_checkout_country_vat/static/description/icon.png
  website_sale_checkout_country_vat/static/description/index.html
  website_sale_checkout_country_vat/static/src/js/dropdown.js
  website_sale_checkout_country_vat/views/assets.xml
  website_sale_checkout_country_vat/views/templates.xml
Labels: approved, needs review

#289 [IMP] website_sale_require_legal: Tour Test & Data
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/data/auth_signup_data.xml
  website_sale_require_legal/static/src/js/tour.js
Labels: approved

#288 [11.0][NEW] website_sale_product_detail_attribute_image: new module
  website_sale_product_detail_attribute_image/README.rst
  website_sale_product_detail_attribute_image/__init__.py
  website_sale_product_detail_attribute_image/__manifest__.py
  website_sale_product_detail_attribute_image/controllers/__init__.py
  website_sale_product_detail_attribute_image/controllers/main.py
  website_sale_product_detail_attribute_image/data/demo.xml
  website_sale_product_detail_attribute_image/i18n/es.po
  website_sale_product_detail_attribute_image/i18n/website_sale_product_detail_attribute_image.pot
  website_sale_product_detail_attribute_image/models/__init__.py
  website_sale_product_detail_attribute_image/models/product_attribute.py
  website_sale_product_detail_attribute_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_image/readme/USAGE.rst
  website_sale_product_detail_attribute_image/static/description/index.html
  website_sale_product_detail_attribute_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png
  website_sale_product_detail_attribute_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_image/static/src/js/website_sale_product_detail_attribute_image_tour.js
  website_sale_product_detail_attribute_image/static/src/less/style.less
  website_sale_product_detail_attribute_image/tests/__init__.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_product_detail_attribute_image/views/assets.xml
  website_sale_product_detail_attribute_image/views/product_attribute_views.xml
  website_sale_product_detail_attribute_image/views/templates.xml
Labels: approved, ready to merge

#284 [11.0][NEW] website_sale_stock_available_display: New module
  website_sale_stock_available_display/README.rst
  website_sale_stock_available_display/__init__.py
  website_sale_stock_available_display/__manifest__.py
  website_sale_stock_available_display/data/demo.xml
  website_sale_stock_available_display/i18n/es.po
  website_sale_stock_available_display/i18n/website_sale_stock_available_display.pot
  website_sale_stock_available_display/models/__init__.py
  website_sale_stock_available_display/models/product_template.py
  website_sale_stock_available_display/models/res_config_settings.py
  website_sale_stock_available_display/readme/CONTRIBUTORS.rst
  website_sale_stock_available_display/readme/DESCRIPTION.rst
  website_sale_stock_available_display/readme/USAGE.rst
  website_sale_stock_available_display/static/description/icon.png
  website_sale_stock_available_display/static/description/index.html
  website_sale_stock_available_display/static/src/js/website_sale_stock_available_display.js
  website_sale_stock_available_display/static/src/js/website_sale_stock_available_display_tour.js
  website_sale_stock_available_display/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_available_display/tests/__init__.py
  website_sale_stock_available_display/tests/test_website_sale_stock_available_display.py
  website_sale_stock_available_display/views/assets.xml
  website_sale_stock_available_display/views/product_template_views.xml
  website_sale_stock_available_display/views/templates.xml
Labels: approved, needs review

#283 [11.0][NEW] website_sale_product_minimal_price: New module
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/data/demo.xml
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/__init__.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/readme/DESCRIPTION.rst
  website_sale_product_minimal_price/readme/USAGE.rst
  website_sale_product_minimal_price/static/description/icon.png
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price_tour.js
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/assets.xml
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, needs review
