Repository OCA/e-commerce, pull requests merged in 2019-03, with the labels that each got.

#248 [IMP] website_sale_show_company_data: show company in address kanban
  website_sale_show_company_data/views/website_sale_address.xml
Labels: approved, needs review

#274 [FIX] web_sale_hide_price: fix error with product comparison tool
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved

#262 [11.0][ADD] website_sale_product_attribute_filter_visibility: Allow hide some product attributes in shop
  website_sale_product_attribute_filter_visibility/__init__.py
  website_sale_product_attribute_filter_visibility/__manifest__.py
  website_sale_product_attribute_filter_visibility/controllers/__init__.py
  website_sale_product_attribute_filter_visibility/controllers/main.py
  website_sale_product_attribute_filter_visibility/i18n/es.po
  website_sale_product_attribute_filter_visibility/i18n/website_sale_product_attribute_filter_visibility.pot
  website_sale_product_attribute_filter_visibility/models/__init__.py
  website_sale_product_attribute_filter_visibility/models/product_attribute.py
  website_sale_product_attribute_filter_visibility/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_visibility/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_visibility/readme/USAGE.rst
  website_sale_product_attribute_filter_visibility/static/description/icon.png
  website_sale_product_attribute_filter_visibility/tests/__init__.py
  website_sale_product_attribute_filter_visibility/tests/test_attribute_filter_visibility.py
  website_sale_product_attribute_filter_visibility/views/product_attribute_views.xml
Labels: approved, needs review, ready to merge
