Repository OCA/e-commerce, pull requests merged in 2019-04, with the labels that each got.

#275 [11.0][WIP] website_sale_secondary_unit: New module
  oca_dependencies.txt
  website_sale_secondary_unit/README.rst
  website_sale_secondary_unit/__init__.py
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/controllers/__init__.py
  website_sale_secondary_unit/controllers/main.py
  website_sale_secondary_unit/data/demo.xml
  website_sale_secondary_unit/hooks.py
  website_sale_secondary_unit/i18n/es.po
  website_sale_secondary_unit/i18n/website_sale_secondary_unit.pot
  website_sale_secondary_unit/models/__init__.py
  website_sale_secondary_unit/models/product_secondary_unit.py
  website_sale_secondary_unit/models/product_template.py
  website_sale_secondary_unit/models/sale_order.py
  website_sale_secondary_unit/readme/CONTRIBUTORS.rst
  website_sale_secondary_unit/readme/DESCRIPTION.rst
  website_sale_secondary_unit/readme/USAGE.rst
  website_sale_secondary_unit/security/ir.model.access.csv
  website_sale_secondary_unit/security/website_sale_secondary_unit.xml
  website_sale_secondary_unit/static/description/icon.png
  website_sale_secondary_unit/static/description/index.html
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit.js
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit_tour.js
  website_sale_secondary_unit/static/src/less/website_sale_secondary_unit.less
  website_sale_secondary_unit/tests/__init__.py
  website_sale_secondary_unit/tests/test_website_sale_secondary_unit.py
  website_sale_secondary_unit/views/assets.xml
  website_sale_secondary_unit/views/product_secondary_unit_views.xml
  website_sale_secondary_unit/views/product_template_views.xml
  website_sale_secondary_unit/views/templates.xml
Labels: needs review

#276 [11.0][ADD] website_sale_attribute_filter_category: New module
  website_sale_attribute_filter_category/README.rst
  website_sale_attribute_filter_category/__init__.py
  website_sale_attribute_filter_category/__manifest__.py
  website_sale_attribute_filter_category/controllers/__init__.py
  website_sale_attribute_filter_category/controllers/main.py
  website_sale_attribute_filter_category/data/demo.xml
  website_sale_attribute_filter_category/i18n/es.po
  website_sale_attribute_filter_category/i18n/website_sale_attribute_filter_category.pot
  website_sale_attribute_filter_category/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_category/readme/DESCRIPTION.rst
  website_sale_attribute_filter_category/readme/USAGE.rst
  website_sale_attribute_filter_category/static/description/icon.png
  website_sale_attribute_filter_category/static/description/index.html
  website_sale_attribute_filter_category/static/src/js/website_sale_attribute_filter_category_tour.js
  website_sale_attribute_filter_category/static/src/less/website_sale_attribute_filter_category.less
  website_sale_attribute_filter_category/tests/__init__.py
  website_sale_attribute_filter_category/tests/test_website_sale_attribute_filter_category.py
  website_sale_attribute_filter_category/views/assets.xml
  website_sale_attribute_filter_category/views/templates.xml
Labels: approved, needs review

#279 [11.0][IMP] website_sale_product_attribute_filter_visibility: Add hook to publish all existing attributes after install this module
  website_sale_product_attribute_filter_visibility/__manifest__.py
  website_sale_product_attribute_filter_visibility/data/demo.xml
  website_sale_product_attribute_filter_visibility/models/product_attribute.py
  website_sale_product_attribute_filter_visibility/static/src/js/website_sale_product_attribute_filter_visibility_tour.js
  website_sale_product_attribute_filter_visibility/tests/test_attribute_filter_visibility.py
  website_sale_product_attribute_filter_visibility/views/assets.xml
Labels: approved

#280 [11.0][FIX] website_sale_secondary_unit: Crash if product_uom not come in values
  website_sale_secondary_unit/models/sale_order.py
Labels: approved

#281 [FIX] website_sale_require_login: Fix public user test
  website_sale_require_login/tests/test_checkout.py
Labels: bug

#282 [11.0][FIX] website_sale_secondary_unit: Fix tour tests
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit_tour.js
Labels: approved, bug

#267 [12.0][MIG] website_sale_require_legal: Migration to v12
  oca_dependencies.txt
  website_sale_require_legal/README.rst
  website_sale_require_legal/__init__.py
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/controllers/__init__.py
  website_sale_require_legal/controllers/main.py
  website_sale_require_legal/data/auth_signup_data.xml
  website_sale_require_legal/demo/assets.xml
  website_sale_require_legal/i18n/de.po
  website_sale_require_legal/i18n/es.po
  website_sale_require_legal/i18n/hr.po
  website_sale_require_legal/i18n/it.po
  website_sale_require_legal/i18n/sl.po
  website_sale_require_legal/i18n/website_sale_require_legal.pot
  website_sale_require_legal/readme/CONFIGURE.rst
  website_sale_require_legal/readme/CONTRIBUTORS.rst
  website_sale_require_legal/readme/DESCRIPTION.rst
  website_sale_require_legal/readme/INSTALL.rst
  website_sale_require_legal/readme/ROADMAP.rst
  website_sale_require_legal/readme/USAGE.rst
  website_sale_require_legal/static/description/icon.png
  website_sale_require_legal/static/description/index.html
  website_sale_require_legal/static/src/js/tour.js
  website_sale_require_legal/tests/__init__.py
  website_sale_require_legal/tests/test_ui.py
  website_sale_require_legal/views/website_sale.xml
Labels: approved
