Repository OCA/e-commerce, pull requests merged in 2020-11, with the labels that each got.

#451 [12.0] [ADD] website_sale_stock_picking_note: New module that allow clients to set commets on the website orders and its pickings
  website_sale_stock_picking_note/README.rst
  website_sale_stock_picking_note/__init__.py
  website_sale_stock_picking_note/__manifest__.py
  website_sale_stock_picking_note/controllers/__init__.py
  website_sale_stock_picking_note/controllers/main.py
  website_sale_stock_picking_note/data/data.xml
  website_sale_stock_picking_note/i18n/es.po
  website_sale_stock_picking_note/i18n/website_sale_stock_picking_note.pot
  website_sale_stock_picking_note/models/__init__.py
  website_sale_stock_picking_note/models/customer_comment_config.py
  website_sale_stock_picking_note/readme/CONFIGURE.rst
  website_sale_stock_picking_note/readme/CONTRIBUTORS.rst
  website_sale_stock_picking_note/readme/DESCRIPTION.rst
  website_sale_stock_picking_note/readme/USAGE.rst
  website_sale_stock_picking_note/static/description/icon.png
  website_sale_stock_picking_note/static/description/index.html
  website_sale_stock_picking_note/static/src/js/website_sale_stock_picking_note.js
  website_sale_stock_picking_note/views/assets.xml
  website_sale_stock_picking_note/views/customer_comment_config_view.xml
  website_sale_stock_picking_note/views/template.xml
Labels: approved, bot is merging ⏳

#463 [11.0][ADD] website_sale_payment_mode
  oca_dependencies.txt
  website_sale_payment_mode/README.rst
  website_sale_payment_mode/__init__.py
  website_sale_payment_mode/__manifest__.py
  website_sale_payment_mode/models/__init__.py
  website_sale_payment_mode/models/website.py
  website_sale_payment_mode/readme/CONTRIBUTORS.rst
  website_sale_payment_mode/readme/DESCRIPTION.rst
  website_sale_payment_mode/readme/INSTALL.rst
  website_sale_payment_mode/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#447 [FIX] website_sale_hide_price: Hide price from all combination info requests
  website_sale_hide_price/models/__init__.py
  website_sale_hide_price/models/product_template.py
Labels: bot is merging ⏳

#472 [11.0][Fix] website_sale_payment_mode missing import model
  website_sale_payment_mode/__init__.py
Labels: approved, bot is merging ⏳, ready to merge

#471 [FIX] website_snippet_carousel_product: Change domain
  website_snippet_carousel_product/static/src/js/snippet.options.js
Labels: approved, bot is merging ⏳
