Repository OCA/e-commerce, pull requests merged in 2020-06, with the labels that each got.

#367 [13.0] [MIG] website_sale_hide_empty_category: Migration to v13.0
  setup/website_sale_hide_empty_category/odoo/addons/website_sale_hide_empty_category
  setup/website_sale_hide_empty_category/setup.py
  website_sale_hide_empty_category/README.rst
  website_sale_hide_empty_category/__init__.py
  website_sale_hide_empty_category/__manifest__.py
  website_sale_hide_empty_category/i18n/es.po
  website_sale_hide_empty_category/i18n/website_sale_hide_empty_category.pot
  website_sale_hide_empty_category/readme/CONTRIBUTORS.rst
  website_sale_hide_empty_category/readme/DESCRIPTION.rst
  website_sale_hide_empty_category/readme/USAGE.rst
  website_sale_hide_empty_category/static/description/icon.png
  website_sale_hide_empty_category/static/description/index.html
  website_sale_hide_empty_category/static/src/js/tour.js
  website_sale_hide_empty_category/tests/__init__.py
  website_sale_hide_empty_category/tests/test_ui.py
  website_sale_hide_empty_category/views/assets.xml
  website_sale_hide_empty_category/views/website_sale_templates.xml
Labels: approved, bot is merging ⏳

#373 [12.0][ADD] website_sale_attribute_filter_order
  website_sale_attribute_filter_order/README.rst
  website_sale_attribute_filter_order/__init__.py
  website_sale_attribute_filter_order/__manifest__.py
  website_sale_attribute_filter_order/readme/CONFIGURE.rst
  website_sale_attribute_filter_order/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_order/readme/DESCRIPTION.rst
  website_sale_attribute_filter_order/readme/ROADMAP.rst
  website_sale_attribute_filter_order/readme/USAGE.rst
  website_sale_attribute_filter_order/static/description/index.html
  website_sale_attribute_filter_order/templates/website_sale.xml
Labels: approved, bot is merging ⏳

#376 [FIX] website_sale_category_description: make website_description properly editable from website
  website_sale_category_description/models/product_public_category.py
Labels: approved, bot is merging ⏳, bug

#368 [13.0] [MIG] website_sale_product_attribute_value_filter_existing: Migration to v13
  setup/website_sale_product_attribute_value_filter_existing/odoo/addons/website_sale_product_attribute_value_filter_existing
  setup/website_sale_product_attribute_value_filter_existing/setup.py
  website_sale_product_attribute_value_filter_existing/README.rst
  website_sale_product_attribute_value_filter_existing/__init__.py
  website_sale_product_attribute_value_filter_existing/__manifest__.py
  website_sale_product_attribute_value_filter_existing/controllers/__init__.py
  website_sale_product_attribute_value_filter_existing/controllers/main.py
  website_sale_product_attribute_value_filter_existing/i18n/website_sale_product_attribute_value_filter_existing.pot
  website_sale_product_attribute_value_filter_existing/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_value_filter_existing/readme/DESCRIPTION.rst
  website_sale_product_attribute_value_filter_existing/readme/USAGE.rst
  website_sale_product_attribute_value_filter_existing/static/description/icon.png
  website_sale_product_attribute_value_filter_existing/static/description/index.html
  website_sale_product_attribute_value_filter_existing/static/src/js/website_sale_product_attribute_value_filter_existing_tour.js
  website_sale_product_attribute_value_filter_existing/tests/__init__.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_attribute_value_filter_existing/views/assets.xml
  website_sale_product_attribute_value_filter_existing/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#371 [12.0][ADD] website_sale_product_style_badge
  website_sale_product_style_badge/README.rst
  website_sale_product_style_badge/__init__.py
  website_sale_product_style_badge/__manifest__.py
  website_sale_product_style_badge/data/data.xml
  website_sale_product_style_badge/data/menus.xml
  website_sale_product_style_badge/models/__init__.py
  website_sale_product_style_badge/models/product_style.py
  website_sale_product_style_badge/readme/CONFIGURE.rst
  website_sale_product_style_badge/readme/CONTRIBUTORS.rst
  website_sale_product_style_badge/readme/DESCRIPTION.rst
  website_sale_product_style_badge/readme/ROADMAP.rst
  website_sale_product_style_badge/readme/USAGE.rst
  website_sale_product_style_badge/security/ir.model.access.csv
  website_sale_product_style_badge/static/description/index.html
  website_sale_product_style_badge/static/src/scss/website_sale.scss
  website_sale_product_style_badge/templates/assets.xml
  website_sale_product_style_badge/templates/website_sale.xml
  website_sale_product_style_badge/views/product_style_views.xml
  website_sale_product_style_badge/views/product_template_views.xml
Labels: approved, bot is merging ⏳

#370 [13.0] [MIG] website_sale_product_detail_attribute_image: Migration to v13.0
  setup/website_sale_product_detail_attribute_image/odoo/addons/website_sale_product_detail_attribute_image
  setup/website_sale_product_detail_attribute_image/setup.py
  website_sale_product_detail_attribute_image/README.rst
  website_sale_product_detail_attribute_image/__init__.py
  website_sale_product_detail_attribute_image/__manifest__.py
  website_sale_product_detail_attribute_image/controllers/__init__.py
  website_sale_product_detail_attribute_image/controllers/main.py
  website_sale_product_detail_attribute_image/i18n/es.po
  website_sale_product_detail_attribute_image/i18n/website_sale_product_detail_attribute_image.pot
  website_sale_product_detail_attribute_image/models/__init__.py
  website_sale_product_detail_attribute_image/models/product_attribute.py
  website_sale_product_detail_attribute_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_image/readme/USAGE.rst
  website_sale_product_detail_attribute_image/static/description/icon.png
  website_sale_product_detail_attribute_image/static/description/index.html
  website_sale_product_detail_attribute_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_image/static/src/img/EN374:2003.png
  website_sale_product_detail_attribute_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_image/static/src/js/website_sale_product_detail_attribute_image_tour.js
  website_sale_product_detail_attribute_image/static/src/less/style.less
  website_sale_product_detail_attribute_image/tests/__init__.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_product_detail_attribute_image/views/assets.xml
  website_sale_product_detail_attribute_image/views/product_attribute_views.xml
  website_sale_product_detail_attribute_image/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#360 [12.0][ADD] website_snippet_product_category
  website_snippet_product_category/README.rst
  website_snippet_product_category/__init__.py
  website_snippet_product_category/__manifest__.py
  website_snippet_product_category/controllers/__init__.py
  website_snippet_product_category/controllers/website.py
  website_snippet_product_category/demo/demo.xml
  website_snippet_product_category/demo/pages.xml
  website_snippet_product_category/models/__init__.py
  website_snippet_product_category/models/product_public_category.py
  website_snippet_product_category/readme/CONFIGURE.rst
  website_snippet_product_category/readme/CONTRIBUTORS.rst
  website_snippet_product_category/readme/CREDITS.rst
  website_snippet_product_category/readme/DESCRIPTION.rst
  website_snippet_product_category/readme/ROADMAP.rst
  website_snippet_product_category/readme/USAGE.rst
  website_snippet_product_category/static/description/index.html
  website_snippet_product_category/static/img/boxes_32.png
  website_snippet_product_category/static/src/img/s_product_category.png
  website_snippet_product_category/static/src/js/frontend.js
  website_snippet_product_category/static/src/js/snippet.options.js
  website_snippet_product_category/static/src/scss/snippet.scss
  website_snippet_product_category/templates/assets.xml
  website_snippet_product_category/templates/snippets.xml
  website_snippet_product_category/views/product_public_category.xml
Labels: approved, bot is merging ⏳

#377 [ADD] website_sale_product_attachment: add attachments to products in website
  website_sale_product_attachment/README.rst
  website_sale_product_attachment/__init__.py
  website_sale_product_attachment/__manifest__.py
  website_sale_product_attachment/controllers/__init__.py
  website_sale_product_attachment/controllers/main.py
  website_sale_product_attachment/i18n/es.po
  website_sale_product_attachment/i18n/website_sale_product_attachment.pot
  website_sale_product_attachment/models/__init__.py
  website_sale_product_attachment/models/ir_attachment.py
  website_sale_product_attachment/models/product_template.py
  website_sale_product_attachment/readme/CONFIGURE.rst
  website_sale_product_attachment/readme/CONTRIBUTORS.rst
  website_sale_product_attachment/readme/DESCRIPTION.rst
  website_sale_product_attachment/readme/ROADMAP.rst
  website_sale_product_attachment/readme/USAGE.rst
  website_sale_product_attachment/static/description/backend-attachment.png
  website_sale_product_attachment/static/description/backend-product.png
  website_sale_product_attachment/static/description/frontend-download.gif
  website_sale_product_attachment/static/description/frontend-icons.png
  website_sale_product_attachment/static/description/icon.png
  website_sale_product_attachment/static/description/index.html
  website_sale_product_attachment/templates/product_template.xml
  website_sale_product_attachment/views/ir_attachment.xml
  website_sale_product_attachment/views/product_template.xml
Labels: approved, bot is merging ⏳, enhancement

#378 [FIX] website_sale_product_attachment: autogenerate index.html
  website_sale_product_attachment/static/description/index.html
Labels: bot is merging ⏳, enhancement

#381 [FIX] website_sale_product_detail_attribute_image: rename file
  website_sale_product_detail_attribute_image/data/demo.xml
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
Labels: bot is merging ⏳

#382 [FIX] website_sale_product_detail_attribute_image: rename file
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
Labels: bot is merging ⏳

#316 [13.0] [IMP] product_template_multi_link: Makes links bi-directional
  product_template_multi_link/__manifest__.py
  product_template_multi_link/data/product_template_link_type.xml
  product_template_multi_link/demo/product_template_link.xml
  product_template_multi_link/demo/product_template_link_type.xml
  product_template_multi_link/models/__init__.py
  product_template_multi_link/models/product_template.py
  product_template_multi_link/models/product_template_link.py
  product_template_multi_link/models/product_template_link_type.py
  product_template_multi_link/security/product_template_link_type.xml
  product_template_multi_link/tests/__init__.py
  product_template_multi_link/tests/test_product_template_link.py
  product_template_multi_link/tests/test_product_template_link_type.py
  product_template_multi_link/views/product_template_link_type.xml
  product_template_multi_link/views/product_template_link_view.xml
  product_template_multi_link/views/product_template_view.xml
Labels: bot is merging ⏳

#384 [FIX] website_sale_product_attachment: role warning
  website_sale_product_attachment/views/product_template.xml
Labels: approved, bot is merging ⏳

#369 [12.0][ADD] website_snippet_carousel_product
  website_snippet_carousel_product/README.rst
  website_snippet_carousel_product/__init__.py
  website_snippet_carousel_product/__manifest__.py
  website_snippet_carousel_product/controllers/__init__.py
  website_snippet_carousel_product/controllers/website.py
  website_snippet_carousel_product/readme/CONFIGURATION.rst
  website_snippet_carousel_product/readme/CONTRIBUTORS.rst
  website_snippet_carousel_product/readme/DESCRIPTION.rst
  website_snippet_carousel_product/readme/ROADMAP.rst
  website_snippet_carousel_product/readme/USAGE.rst
  website_snippet_carousel_product/static/description/icon.png
  website_snippet_carousel_product/static/description/index.html
  website_snippet_carousel_product/static/src/js/s_product_carousel_frontend.js
  website_snippet_carousel_product/static/src/js/snippet.options.js
  website_snippet_carousel_product/static/src/scss/s_product_carousel.scss
  website_snippet_carousel_product/templates/assets.xml
  website_snippet_carousel_product/templates/snippet.xml
Labels: approved, bot is merging ⏳

#387 [12.0][IMP] website_sale_attribute_filter_category: Allow to display a category folded or unfolded in website
  website_sale_attribute_filter_category/README.rst
  website_sale_attribute_filter_category/__init__.py
  website_sale_attribute_filter_category/__manifest__.py
  website_sale_attribute_filter_category/controllers/main.py
  website_sale_attribute_filter_category/i18n/es.po
  website_sale_attribute_filter_category/i18n/website_sale_attribute_filter_category.pot
  website_sale_attribute_filter_category/models/__init__.py
  website_sale_attribute_filter_category/models/website_sale_attribute_filter_category.py
  website_sale_attribute_filter_category/readme/CONFIGURE.rst
  website_sale_attribute_filter_category/readme/DESCRIPTION.rst
  website_sale_attribute_filter_category/static/description/index.html
  website_sale_attribute_filter_category/static/src/js/website_sale_attribute_filter_category_tour.js
  website_sale_attribute_filter_category/tests/test_website_sale_attribute_filter_category.py
  website_sale_attribute_filter_category/views/templates.xml
  website_sale_attribute_filter_category/views/website_sale_attribute_filter_category_view.xml
Labels: approved, bot is merging ⏳

#386 [FIX] website_sale_product_attachment: sort attachments, support long names
  website_sale_product_attachment/controllers/main.py
  website_sale_product_attachment/templates/product_template.xml
Labels: approved, bot is merging ⏳, bug, needs review

#359 [13.0] [MIG] website_sale_attribute_filter_category: Migration to v13
  setup/website_sale_attribute_filter_category/odoo/addons/website_sale_attribute_filter_category
  setup/website_sale_attribute_filter_category/setup.py
  website_sale_attribute_filter_category/README.rst
  website_sale_attribute_filter_category/__init__.py
  website_sale_attribute_filter_category/__manifest__.py
  website_sale_attribute_filter_category/controllers/__init__.py
  website_sale_attribute_filter_category/controllers/main.py
  website_sale_attribute_filter_category/i18n/es.po
  website_sale_attribute_filter_category/i18n/fi.po
  website_sale_attribute_filter_category/i18n/website_sale_attribute_filter_category.pot
  website_sale_attribute_filter_category/models/__init__.py
  website_sale_attribute_filter_category/models/website_sale_attribute_filter_category.py
  website_sale_attribute_filter_category/readme/CONFIGURE.rst
  website_sale_attribute_filter_category/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_category/readme/DESCRIPTION.rst
  website_sale_attribute_filter_category/readme/USAGE.rst
  website_sale_attribute_filter_category/static/description/icon.png
  website_sale_attribute_filter_category/static/description/index.html
  website_sale_attribute_filter_category/static/src/js/website_sale_attribute_filter_category_tour.js
  website_sale_attribute_filter_category/static/src/less/website_sale_attribute_filter_category.less
  website_sale_attribute_filter_category/tests/__init__.py
  website_sale_attribute_filter_category/tests/test_website_sale_attribute_filter_category.py
  website_sale_attribute_filter_category/views/assets.xml
  website_sale_attribute_filter_category/views/templates.xml
  website_sale_attribute_filter_category/views/website_sale_attribute_filter_category_view.xml
Labels: approved, bot is merging ⏳

#385 [ADD] website_sale_product_detail_attribute_value_image
  website_sale_product_detail_attribute_value_image/README.rst
  website_sale_product_detail_attribute_value_image/__init__.py
  website_sale_product_detail_attribute_value_image/__manifest__.py
  website_sale_product_detail_attribute_value_image/models/__init__.py
  website_sale_product_detail_attribute_value_image/models/product_attribute_value.py
  website_sale_product_detail_attribute_value_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_value_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_value_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_value_image/readme/USAGE.rst
  website_sale_product_detail_attribute_value_image/static/description/icon.png
  website_sale_product_detail_attribute_value_image/static/description/index.html
  website_sale_product_detail_attribute_value_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_value_image/static/src/js/website_sale_product_detail_attribute_value_image_tour.js
  website_sale_product_detail_attribute_value_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_value_image/templates/assets.xml
  website_sale_product_detail_attribute_value_image/templates/shop_product.xml
  website_sale_product_detail_attribute_value_image/tests/__init__.py
  website_sale_product_detail_attribute_value_image/tests/test_website_sale_product_detail_attribute_value_image.py
  website_sale_product_detail_attribute_value_image/views/product_attribute_value_views.xml
Labels: approved, bot is merging ⏳

#389 [12.0][FIX] website_sale_attribute_filter_price: Use the correct depends
  website_sale_attribute_filter_price/__manifest__.py
Labels: approved, bot is merging ⏳

#380 [13.0] [MIG] website_sale_product_minimal_price: Migration to v13
  setup/website_sale_product_minimal_price/odoo/addons/website_sale_product_minimal_price
  setup/website_sale_product_minimal_price/setup.py
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/controllers/__init__.py
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/demo/assets.xml
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/__init__.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/readme/DESCRIPTION.rst
  website_sale_product_minimal_price/readme/USAGE.rst
  website_sale_product_minimal_price/static/description/icon.png
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/tour.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_minimal_price.xml
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/assets.xml
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#391 [MIG] website_sale_product_reference_displayed: Migration to 12.0
  website_sale_product_reference_displayed/README.rst
  website_sale_product_reference_displayed/__init__.py
  website_sale_product_reference_displayed/__manifest__.py
  website_sale_product_reference_displayed/i18n/website_sale_product_reference_displayed.pot
  website_sale_product_reference_displayed/readme/CONTRIBUTORS.rst
  website_sale_product_reference_displayed/readme/DESCRIPTION.rst
  website_sale_product_reference_displayed/readme/USAGE.rst
  website_sale_product_reference_displayed/static/description/enable-product-reference.png
  website_sale_product_reference_displayed/static/description/icon.png
  website_sale_product_reference_displayed/static/description/index.html
  website_sale_product_reference_displayed/views/website_sale_views.xml
Labels: approved, bot is merging ⏳

#392 [13.0][IMP] website_sale_attribute_filter_category: Use sass instead of les…
  website_sale_attribute_filter_category/static/src/scss/website_sale_attribute_filter_category.scss
  website_sale_attribute_filter_category/views/assets.xml
Labels: approved, bot is merging ⏳
