Repository OCA/e-commerce, pull requests merged in 2020-08, with the labels that each got.

#417 [IMP] website_sale_tax_toggle: Fix tests
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
Labels: approved, bot is merging ⏳

#423 [FIX] website_tax_toggle: make tour effective
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/demo/assets.xml
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/views/assets.xml
  website_sale_tax_toggle/views/templates.xml
Labels: approved, bot is merging ⏳, bug

#420 [ADD] website_sale_b2x_alt_price: display B2{B,C} complementary price
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/demo/assets.xml
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/readme/CONFIGURE.rst
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.rst
  website_sale_b2x_alt_price/readme/DESCRIPTION.rst
  website_sale_b2x_alt_price/readme/ROADMAP.rst
  website_sale_b2x_alt_price/readme/USAGE.rst
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.js
  website_sale_b2x_alt_price/static/tours/b2b.js
  website_sale_b2x_alt_price/static/tours/b2c.js
  website_sale_b2x_alt_price/templates/assets.xml
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
Labels: approved, bot is merging ⏳, enhancement, ready to merge

#419 [13.0][IMP] Add form view on product_template_multi_link
  product_template_multi_link/views/action.xml
  product_template_multi_link/views/product_template_link_view.xml
  product_template_multi_link_date_span/views/product_template_link_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#366 [10.0] Fix Travis
  .travis.yml
  website_sale_price_tier/demo/product_pricelist_item.xml
Labels: bot is merging ⏳

#424 [FIX] website_sale_b2x_alt_price: l10n resilient tests
  website_sale_b2x_alt_price/static/tours/b2b.js
  website_sale_b2x_alt_price/static/tours/b2c.js
  website_sale_b2x_alt_price/tests/test_ui.py
Labels: bot is merging ⏳, bug

#425 [13.0] [FIX] website_sale_product_detail_attribute_image : update CSS url from less to scss
  website_sale_product_detail_attribute_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_image/views/assets.xml
Labels: bot is merging ⏳
