Repository OCA/e-commerce, pull requests merged in 2020-07, with the labels that each got.

#394 [FIX][12.0] website_sale_product_available_display: Take into account negative units to display danger style message
  website_sale_stock_available_display/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_available_display/views/templates.xml
Labels: approved, bot is merging ⏳

#393 [IMP] website_sale_product_minimal_price: Removed the async/await for avoid inheritance problems
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
Labels: approved, bot is merging ⏳

#390 [ADD] website_sale_wishlist_keep: New module that keep the items on wishlist when we add to cart
  website_sale_wishlist_keep/README.rst
  website_sale_wishlist_keep/__init__.py
  website_sale_wishlist_keep/__manifest__.py
  website_sale_wishlist_keep/i18n/website_sale_wishlist_keep.pot
  website_sale_wishlist_keep/readme/CONTRIBUTORS.rst
  website_sale_wishlist_keep/readme/DESCRIPTION.rst
  website_sale_wishlist_keep/readme/USAGE.rst
  website_sale_wishlist_keep/static/description/icon.png
  website_sale_wishlist_keep/static/description/index.html
  website_sale_wishlist_keep/static/src/js/tour.js
  website_sale_wishlist_keep/tests/__init__.py
  website_sale_wishlist_keep/tests/test_ui.py
  website_sale_wishlist_keep/views/assets.xml
  website_sale_wishlist_keep/views/website_sale_wishlist_template.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#399 [12.0][NEW] website_sale_tax_toggle: Display price with or without taxes by toggle button in website shop
  website_sale_tax_toggle/README.rst
  website_sale_tax_toggle/__init__.py
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/controllers/__init__.py
  website_sale_tax_toggle/controllers/main.py
  website_sale_tax_toggle/i18n/es.po
  website_sale_tax_toggle/i18n/website_sale_tax_toggle.pot
  website_sale_tax_toggle/models/__init__.py
  website_sale_tax_toggle/models/res_users.py
  website_sale_tax_toggle/readme/CONTRIBUTORS.rst
  website_sale_tax_toggle/readme/DESCRIPTION.rst
  website_sale_tax_toggle/readme/USAGE.rst
  website_sale_tax_toggle/static/description/icon.png
  website_sale_tax_toggle/static/description/index.html
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.js
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/static/src/scss/website_sale_tax_toggle.scss
  website_sale_tax_toggle/tests/__init__.py
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
  website_sale_tax_toggle/views/assets.xml
  website_sale_tax_toggle/views/templates.xml
Labels: approved, bot is merging ⏳

#396 [13.0][MIG] website_sale_attribute_filter_order: Migration to 13.0
  setup/website_sale_attribute_filter_order/odoo/addons/website_sale_attribute_filter_order
  setup/website_sale_attribute_filter_order/setup.py
  website_sale_attribute_filter_order/README.rst
  website_sale_attribute_filter_order/__init__.py
  website_sale_attribute_filter_order/__manifest__.py
  website_sale_attribute_filter_order/i18n/website_sale_attribute_filter_order.pot
  website_sale_attribute_filter_order/readme/CONFIGURE.rst
  website_sale_attribute_filter_order/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_order/readme/DESCRIPTION.rst
  website_sale_attribute_filter_order/readme/ROADMAP.rst
  website_sale_attribute_filter_order/readme/USAGE.rst
  website_sale_attribute_filter_order/static/description/icon.png
  website_sale_attribute_filter_order/static/description/index.html
  website_sale_attribute_filter_order/templates/website_sale.xml
Labels: approved, bot is merging ⏳, ready to merge

#403 [NEW] website_sale_tax_toggle: Test more resilient to pricelists
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
Labels: approved, bot is merging ⏳

#407 [NEW] website_sale_tax_toggle: Test more resilient to CI
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
Labels: bot is merging ⏳

#408 product_template_multi_link: fix link type data
  product_template_multi_link/__manifest__.py
Labels: bot is merging ⏳, bug

#402 [MIG] website_sale_cart_selectable: Migration to 12.0
  website_sale_cart_selectable/README.rst
  website_sale_cart_selectable/__init__.py
  website_sale_cart_selectable/__manifest__.py
  website_sale_cart_selectable/models/__init__.py
  website_sale_cart_selectable/models/product.py
  website_sale_cart_selectable/readme/CONTRIBUTORS.rst
  website_sale_cart_selectable/readme/DESCRIPTION.rst
  website_sale_cart_selectable/readme/USAGE.rst
  website_sale_cart_selectable/static/description/icon.png
  website_sale_cart_selectable/views/product_view.xml
  website_sale_cart_selectable/views/website_sale_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#410 [FIX] website_sale_product_available_display: Take into account negative units to display danger style message
  website_sale_stock_available_display/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_available_display/tests/test_website_sale_stock_available_display.py
  website_sale_stock_available_display/views/templates.xml
Labels: approved, bot is merging ⏳

#411 [12.0][FIX] website_sale_attribute_filter_price: Use the correct assets section
  website_sale_attribute_filter_price/templates/assets.xml
Labels: approved, bot is merging ⏳

#404 [13.0] website_sale_attribute_filter_price: Migration to 13.0.
  setup/website_sale_attribute_filter_price/odoo/addons/website_sale_attribute_filter_price
  setup/website_sale_attribute_filter_price/setup.py
  website_sale_attribute_filter_price/README.rst
  website_sale_attribute_filter_price/__init__.py
  website_sale_attribute_filter_price/__manifest__.py
  website_sale_attribute_filter_price/controllers/__init__.py
  website_sale_attribute_filter_price/controllers/website_sale.py
  website_sale_attribute_filter_price/i18n/website_sale_attribute_filter_price.pot
  website_sale_attribute_filter_price/readme/CONFIGURE.rst
  website_sale_attribute_filter_price/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_price/readme/CREDITS.rst
  website_sale_attribute_filter_price/readme/DESCRIPTION.rst
  website_sale_attribute_filter_price/readme/USAGE.rst
  website_sale_attribute_filter_price/static/description/icon.png
  website_sale_attribute_filter_price/static/description/index.html
  website_sale_attribute_filter_price/static/src/js/shop.js
  website_sale_attribute_filter_price/static/src/lib/ionRangeSlider/ion.rangeSlider.css
  website_sale_attribute_filter_price/static/src/lib/ionRangeSlider/ion.rangeSlider.js
  website_sale_attribute_filter_price/templates/assets.xml
  website_sale_attribute_filter_price/templates/shop.xml
Labels: approved, bot is merging ⏳

#409 [IMP] website_sale_secondary_unit: Set default secondary uom for products when "Add to cart" view is enabled.
  website_sale_secondary_unit/models/sale_order.py
Labels: approved, bot is merging ⏳

#413 [FIX] website_sale_suggest_create_account: signup allowed detection
  website_sale_suggest_create_account/views/website_sale.xml
Labels: approved, bot is merging ⏳, bug, needs review

#414 [12.0][IMP] website_snippet_carousel_product: Initialize animations
  website_snippet_carousel_product/README.rst
  website_snippet_carousel_product/readme/CONFIGURATION.rst
  website_snippet_carousel_product/readme/ROADMAP.rst
  website_snippet_carousel_product/static/description/index.html
  website_snippet_carousel_product/static/src/js/s_product_carousel_frontend.js
Labels: approved, bot is merging ⏳

#416 [13.0][ADD] product_template_multi_link_date_span
  product_template_multi_link_date_span/__init__.py
  product_template_multi_link_date_span/__manifest__.py
  product_template_multi_link_date_span/models/__init__.py
  product_template_multi_link_date_span/models/product_template_link.py
  product_template_multi_link_date_span/readme/CONTRIBUTORS.rst
  product_template_multi_link_date_span/readme/DESCRIPTION.rst
  product_template_multi_link_date_span/tests/__init__.py
  product_template_multi_link_date_span/tests/test_product_template_link_date_span.py
  product_template_multi_link_date_span/views/product_template_link_view.xml
  requirements.txt
  setup/product_template_multi_link_date_span/odoo/addons/product_template_multi_link_date_span
  setup/product_template_multi_link_date_span/setup.py
Labels: approved, needs review
