Repository OCA/e-commerce, pull requests merged in 2020-05, with the labels that each got.

#352 [FIX] website_sale_secondary_unit: Fix quantity position in cart lines
  website_sale_secondary_unit/static/src/scss/website_sale_secondary_unit.scss
Labels: approved, bot is merging ⏳

#354 [12.0][IMP] website_sale_stock_available_display: Allow overwrite invisible attrs in view to avoid crash with other modules
  website_sale_stock_available_display/models/product_template.py
  website_sale_stock_available_display/views/product_template_views.xml
Labels: approved, bot is merging ⏳

#350 [ADD] website_sale_exception: new module
  website_sale_exception/README.rst
  website_sale_exception/__init__.py
  website_sale_exception/__manifest__.py
  website_sale_exception/models/__init__.py
  website_sale_exception/models/sale.py
  website_sale_exception/readme/CONTRIBUTORS.rst
  website_sale_exception/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#351 [12.0][FIX] website_sale_checkout_country_vat: inherit the correct view
  website_sale_checkout_country_vat/views/templates.xml
Labels: approved, bot is merging ⏳, bug, ready to merge

#355 [12.0][FIX] website_sale_stock_available: immediately_usable_qty in_cart_update
  website_sale_stock_available/models/__init__.py
  website_sale_stock_available/models/product_product.py
  website_sale_stock_available/models/product_template.py
  website_sale_stock_available/models/sale_order.py
Labels: approved, bot is merging ⏳

#358 [12.0][IMP] website_sale_stock_available: Improve readme
  website_sale_stock_available/README.rst
  website_sale_stock_available/readme/CONFIGURE.rst
  website_sale_stock_available/readme/DESCRIPTION.rst
  website_sale_stock_available/readme/USAGE.rst
  website_sale_stock_available/static/description/availability_message.png
  website_sale_stock_available/static/description/index.html
  website_sale_stock_available/static/description/product_quantities.png
Labels: bot is merging ⏳

#353 [12.0][ADD] website_sale_stock_force_block: New module to block product sales on website
  website_sale_stock_force_block/README.rst
  website_sale_stock_force_block/__init__.py
  website_sale_stock_force_block/__manifest__.py
  website_sale_stock_force_block/data/demo.xml
  website_sale_stock_force_block/hooks.py
  website_sale_stock_force_block/i18n/es.po
  website_sale_stock_force_block/i18n/website_sale_stock_force_block.pot
  website_sale_stock_force_block/models/__init__.py
  website_sale_stock_force_block/models/product_template.py
  website_sale_stock_force_block/models/res_config_settings.py
  website_sale_stock_force_block/readme/CONTRIBUTORS.rst
  website_sale_stock_force_block/readme/DESCRIPTION.rst
  website_sale_stock_force_block/readme/USAGE.rst
  website_sale_stock_force_block/static/description/icon.png
  website_sale_stock_force_block/static/description/index.html
  website_sale_stock_force_block/static/src/js/website_sale_stock_force_block.js
  website_sale_stock_force_block/static/src/js/website_sale_stock_force_block_tour.js
  website_sale_stock_force_block/static/src/xml/website_sale_stock_force_block.xml
  website_sale_stock_force_block/tests/__init__.py
  website_sale_stock_force_block/tests/test_website_sale_stock_force_block.py
  website_sale_stock_force_block/views/assets.xml
  website_sale_stock_force_block/views/product_template_views.xml
  website_sale_stock_force_block/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#357 [ADD] website_sale_category_description
  website_sale_category_description/README.rst
  website_sale_category_description/__init__.py
  website_sale_category_description/__manifest__.py
  website_sale_category_description/i18n/es.po
  website_sale_category_description/i18n/website_sale_category_description.pot
  website_sale_category_description/models/__init__.py
  website_sale_category_description/models/product_public_category.py
  website_sale_category_description/readme/CONTRIBUTORS.rst
  website_sale_category_description/readme/CREDITS.rst
  website_sale_category_description/readme/DESCRIPTION.rst
  website_sale_category_description/readme/USAGE.rst
  website_sale_category_description/static/description/icon.png
  website_sale_category_description/static/description/index.html
  website_sale_category_description/templates/website_sale.xml
Labels: approved, bot is merging ⏳, enhancement

#361 [FIX] Add roadmap note
  website_sale_category_description/README.rst
  website_sale_category_description/readme/ROADMAP.rst
  website_sale_category_description/static/description/index.html
Labels: bot is merging ⏳, enhancement

#356 [ADD][12.0] website_sale_product_sort: New module
  website_sale_product_sort/README.rst
  website_sale_product_sort/__init__.py
  website_sale_product_sort/__manifest__.py
  website_sale_product_sort/controllers/__init__.py
  website_sale_product_sort/controllers/main.py
  website_sale_product_sort/i18n/es.po
  website_sale_product_sort/i18n/website_sale_product_sort.pot
  website_sale_product_sort/models/__init__.py
  website_sale_product_sort/models/res_config_settings.py
  website_sale_product_sort/models/website.py
  website_sale_product_sort/readme/CONFIGURE.rst
  website_sale_product_sort/readme/CONTRIBUTORS.rst
  website_sale_product_sort/readme/DESCRIPTION.rst
  website_sale_product_sort/readme/ROADMAP.rst
  website_sale_product_sort/readme/USAGE.rst
  website_sale_product_sort/static/description/index.html
  website_sale_product_sort/views/res_config_settings_view.xml
  website_sale_product_sort/views/website_sale_sort.xml
Labels: approved, bot is merging ⏳

#362 [IMP] website_sale_stock_list_preview: hide the add to cart button when no stock available
  website_sale_stock_list_preview/README.rst
  website_sale_stock_list_preview/__manifest__.py
  website_sale_stock_list_preview/controllers/main.py
  website_sale_stock_list_preview/readme/USAGE.rst
  website_sale_stock_list_preview/static/description/index.html
  website_sale_stock_list_preview/static/src/js/tour.js
  website_sale_stock_list_preview/static/src/js/website_sale_stock_list_preview.js
  website_sale_stock_list_preview/tests/test_ui.py
  website_sale_stock_list_preview/views/templates.xml
Labels: approved, bot is merging ⏳, needs review
