Repository OCA/e-commerce, pull requests merged in 2020-10, with the labels that each got.

#430 [12.0][IMP+FIX] website_sale_attribute_filter_category: collapsible
  website_sale_attribute_filter_category/__manifest__.py
  website_sale_attribute_filter_category/demo/assets_tour.xml
  website_sale_attribute_filter_category/i18n/es.po
  website_sale_attribute_filter_category/i18n/website_sale_attribute_filter_category.pot
  website_sale_attribute_filter_category/static/src/less/website_sale_attribute_filter_category.less
  website_sale_attribute_filter_category/static/src/scss/website_sale_attribute_filter_category.scss
  website_sale_attribute_filter_category/views/assets.xml
  website_sale_attribute_filter_category/views/templates.xml
Labels: bot is merging ⏳

#446 [13.0] [FIX] website_sale_stock_list_preview: Added parameter virtual_available_formated to show the quantity available
  website_sale_stock_list_preview/controllers/main.py
  website_sale_stock_list_preview/static/src/js/tour.js
  website_sale_stock_list_preview/static/src/js/website_sale_stock_list_preview.js
  website_sale_stock_list_preview/tests/test_ui.py
Labels: approved, bot is merging ⏳, hacktoberfest-accepted

#448 [13.0][IMP] website_sale_suggest_create_account: unit test compatibility
  website_sale_suggest_create_account/tests/test_shop_buy.py
Labels: bot is merging ⏳

#440 [13.0][MIG] website_sale_vat_required: Migration to 13.0
  setup/website_sale_vat_required/odoo/addons/website_sale_vat_required
  setup/website_sale_vat_required/setup.py
  website_sale_vat_required/README.rst
  website_sale_vat_required/__init__.py
  website_sale_vat_required/__manifest__.py
  website_sale_vat_required/controllers/__init__.py
  website_sale_vat_required/controllers/main.py
  website_sale_vat_required/i18n/es.po
  website_sale_vat_required/i18n/website_sale_vat_required.pot
  website_sale_vat_required/readme/CONTRIBUTORS.rst
  website_sale_vat_required/readme/DESCRIPTION.rst
  website_sale_vat_required/readme/USAGE.rst
  website_sale_vat_required/static/description/icon.png
  website_sale_vat_required/static/description/index.html
  website_sale_vat_required/static/src/js/website_sale_vat_required.tour.js
  website_sale_vat_required/tests/__init__.py
  website_sale_vat_required/tests/test_website_sale_vat_required.py
  website_sale_vat_required/views/assets.xml
  website_sale_vat_required/views/templates.xml
Labels: bot is merging ⏳

#432 [12.0][IMP] website_sale_product_minimal_price: Added fuctionality for take care about the current pricelist items
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/controllers/__init__.py
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/demo/assets.xml
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONFIGURE.rst
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/readme/HISTORY.rst
  website_sale_product_minimal_price/readme/USAGE.rst
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price_tour.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_minimal_price.xml
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/assets.xml
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, bot is merging ⏳, needs review
