Repository OCA/e-commerce, pull requests merged in 2020-09, with the labels that each got.

#418 [12.0] ADD website_sale_product_model_viewer
  website_sale_product_model_viewer/__init__.py
  website_sale_product_model_viewer/__manifest__.py
  website_sale_product_model_viewer/readme/CONTRIBUTORS.rst
  website_sale_product_model_viewer/readme/DESCRIPTION.rst
  website_sale_product_model_viewer/readme/ROADMAP.rst
  website_sale_product_model_viewer/readme/USAGE.rst
  website_sale_product_model_viewer/static/src/js/product_model_viewer.js
  website_sale_product_model_viewer/views/frontend_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#426 [IMP][12.0] website_sale_product_brand: add website.published.mixin
  website_sale_product_brand/README.rst
  website_sale_product_brand/__init__.py
  website_sale_product_brand/__manifest__.py
  website_sale_product_brand/controllers/main.py
  website_sale_product_brand/models/__init__.py
  website_sale_product_brand/models/product_brand.py
  website_sale_product_brand/readme/CONFIGURE.rst
  website_sale_product_brand/readme/CONTRIBUTORS.rst
  website_sale_product_brand/readme/DESCRIPTION.rst
  website_sale_product_brand/readme/INSTALL.rst
  website_sale_product_brand/readme/USAGE.rst
  website_sale_product_brand/static/description/index.html
  website_sale_product_brand/views/product_brand_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#428 [12.0][FIX+IMP] website_sale_attribute_filter_price: Refactor code
  website_sale_attribute_filter_price/README.rst
  website_sale_attribute_filter_price/readme/CONFIGURE.rst
  website_sale_attribute_filter_price/static/description/index.html
  website_sale_attribute_filter_price/static/src/js/shop.js
  website_sale_attribute_filter_price/templates/shop.xml
Labels: approved, bot is merging ⏳

#429 [13.0] Add product_variant_multi_link
  product_template_multi_link/models/product_template_link.py
  product_template_multi_link/tests/test_product_template_link.py
  product_template_multi_link/tests/test_product_template_link_type.py
  product_variant_multi_link/__init__.py
  product_variant_multi_link/__manifest__.py
  product_variant_multi_link/models/__init__.py
  product_variant_multi_link/models/product_product.py
  product_variant_multi_link/models/product_template_link.py
  product_variant_multi_link/readme/CONTRIBUTORS.rst
  product_variant_multi_link/readme/CREDITS.rst
  product_variant_multi_link/readme/DESCRIPTION.rst
  product_variant_multi_link/readme/USAGE.rst
  product_variant_multi_link/tests/__init__.py
  product_variant_multi_link/tests/test_product_template_link.py
  product_variant_multi_link/views/product_template_link_view.xml
  setup/product_variant_multi_link/odoo/addons/product_variant_multi_link
  setup/product_variant_multi_link/setup.py
Labels: approved, bot is merging ⏳, needs review

#431 [12.0][FIX+IMP] website_sale_product_attribute_value_image: Move test tour JS to demo + Add 'alt' and 'title'
  website_sale_product_detail_attribute_value_image/__manifest__.py
  website_sale_product_detail_attribute_value_image/demo/assets_tour.xml
  website_sale_product_detail_attribute_value_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_value_image/templates/assets.xml
  website_sale_product_detail_attribute_value_image/templates/shop_product.xml
Labels: approved, bot is merging ⏳

#264 [10.0][FIX] website_sale_charge_payment_fee: Use a browse record if there a…
  website_sale_charge_payment_fee/__manifest__.py
  website_sale_charge_payment_fee/controllers/website_sale.py
Labels: bot is merging ⏳, needs review

#433 [12.0][ADD] website_sale_stock_provisioning_date: new module.
  website_sale_stock_provisioning_date/README.rst
  website_sale_stock_provisioning_date/__init__.py
  website_sale_stock_provisioning_date/__manifest__.py
  website_sale_stock_provisioning_date/i18n/es.po
  website_sale_stock_provisioning_date/i18n/website_sale_stock_provisioning_date.pot
  website_sale_stock_provisioning_date/models/__init__.py
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/product_template.py
  website_sale_stock_provisioning_date/readme/CONTRIBUTORS.rst
  website_sale_stock_provisioning_date/readme/DESCRIPTION.rst
  website_sale_stock_provisioning_date/readme/USAGE.rst
  website_sale_stock_provisioning_date/static/description/index.html
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date.js
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date_tour.js
  website_sale_stock_provisioning_date/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_provisioning_date/tests/__init__.py
  website_sale_stock_provisioning_date/tests/test_website_sale_stock_provisioning_date.py
  website_sale_stock_provisioning_date/views/assets.xml
  website_sale_stock_provisioning_date/views/product_template_views.xml
Labels: approved, bot is merging ⏳
