Repository OCA/e-commerce, pull requests merged in 2020-04, with the labels that each got.

#317 12.0 mig website sale hide empty category
  website_sale_hide_empty_category/__init__.py
  website_sale_hide_empty_category/__manifest__.py
  website_sale_hide_empty_category/i18n/website_sale_hide_empty_category.pot
  website_sale_hide_empty_category/models/__init__.py
  website_sale_hide_empty_category/models/product_public_category.py
  website_sale_hide_empty_category/readme/CONTRIBUTORS.rst
  website_sale_hide_empty_category/readme/DESCRIPTION.rst
  website_sale_hide_empty_category/readme/HISTORY.rst
  website_sale_hide_empty_category/readme/USAGE.rst
  website_sale_hide_empty_category/static/description/icon.png
  website_sale_hide_empty_category/views/website_sale_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#347 [12.0][FIX] website_sale_show_company_data: use correct variable when displaying VAT
  website_sale_show_company_data/views/website_sale_address.xml
Labels: approved, bot is merging ⏳

#345 [13.0][ADD] website_sale_stock_list_preview: New module
  website_sale_stock_list_preview/README.rst
  website_sale_stock_list_preview/__init__.py
  website_sale_stock_list_preview/__manifest__.py
  website_sale_stock_list_preview/controllers/__init__.py
  website_sale_stock_list_preview/controllers/main.py
  website_sale_stock_list_preview/readme/CONTRIBUTORS.rst
  website_sale_stock_list_preview/readme/DESCRIPTION.rst
  website_sale_stock_list_preview/readme/USAGE.rst
  website_sale_stock_list_preview/static/description/icon.png
  website_sale_stock_list_preview/static/description/index.html
  website_sale_stock_list_preview/static/src/js/tour.js
  website_sale_stock_list_preview/static/src/js/website_sale_stock_list_preview.js
  website_sale_stock_list_preview/tests/__init__.py
  website_sale_stock_list_preview/tests/test_ui.py
  website_sale_stock_list_preview/views/assets.xml
Labels: approved, bot is merging ⏳, ready to merge

#334 [13.0][MIG] website_sale_product_attribute_filter_visibility: Migration to 13.0
  setup/website_sale_product_attribute_filter_visibility/odoo/addons/website_sale_product_attribute_filter_visibility
  setup/website_sale_product_attribute_filter_visibility/setup.py
  website_sale_product_attribute_filter_visibility/README.rst
  website_sale_product_attribute_filter_visibility/__init__.py
  website_sale_product_attribute_filter_visibility/__manifest__.py
  website_sale_product_attribute_filter_visibility/controllers/__init__.py
  website_sale_product_attribute_filter_visibility/controllers/main.py
  website_sale_product_attribute_filter_visibility/i18n/es.po
  website_sale_product_attribute_filter_visibility/i18n/website_sale_product_attribute_filter_visibility.pot
  website_sale_product_attribute_filter_visibility/models/__init__.py
  website_sale_product_attribute_filter_visibility/models/product_attribute.py
  website_sale_product_attribute_filter_visibility/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_visibility/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_visibility/readme/USAGE.rst
  website_sale_product_attribute_filter_visibility/static/description/icon.png
  website_sale_product_attribute_filter_visibility/static/description/index.html
  website_sale_product_attribute_filter_visibility/static/src/js/website_sale_product_attribute_filter_visibility_tour.js
  website_sale_product_attribute_filter_visibility/tests/__init__.py
  website_sale_product_attribute_filter_visibility/tests/test_attribute_filter_visibility.py
  website_sale_product_attribute_filter_visibility/views/assets.xml
  website_sale_product_attribute_filter_visibility/views/product_attribute_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#337 [13.0][MIG] website_sale_require_login: Migration to 13.0
  setup/website_sale_require_login/odoo/addons/website_sale_require_login
  setup/website_sale_require_login/setup.py
  website_sale_require_login/README.rst
  website_sale_require_login/__init__.py
  website_sale_require_login/__manifest__.py
  website_sale_require_login/controllers/__init__.py
  website_sale_require_login/controllers/main.py
  website_sale_require_login/hooks.py
  website_sale_require_login/i18n/de.po
  website_sale_require_login/i18n/it.po
  website_sale_require_login/i18n/sl.po
  website_sale_require_login/i18n/website_sale_require_login.pot
  website_sale_require_login/readme/CONFIGURE.rst
  website_sale_require_login/readme/CONTRIBUTORS.rst
  website_sale_require_login/readme/DESCRIPTION.rst
  website_sale_require_login/readme/USAGE.rst
  website_sale_require_login/static/description/icon.png
  website_sale_require_login/static/description/index.html
  website_sale_require_login/static/tests/tours/checkout.js
  website_sale_require_login/tests/__init__.py
  website_sale_require_login/tests/test_checkout.py
  website_sale_require_login/views/assets.xml
  website_sale_require_login/views/website_sale.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#349 [12.0][ADD] website_sale_stock_available: new module
  oca_dependencies.txt
  website_sale_stock_available/README.rst
  website_sale_stock_available/__init__.py
  website_sale_stock_available/__manifest__.py
  website_sale_stock_available/models/__init__.py
  website_sale_stock_available/models/product_template.py
  website_sale_stock_available/readme/CONFIGURE.rst
  website_sale_stock_available/readme/CONTRIBUTORS.rst
  website_sale_stock_available/readme/DESCRIPTION.rst
  website_sale_stock_available/readme/USAGE.rst
  website_sale_stock_available/static/description/index.html
  website_sale_stock_available/tests/__init__.py
  website_sale_stock_available/tests/test_website_sale_stock_available.py
Labels: approved, bot is merging ⏳, ready to merge
