Repository OCA/e-commerce, pull requests merged in 2021-03, with the labels that each got.

#511 [FIX][website_sale_product_brand] Missing ppg parameter in shop method inheritance
  website_sale_product_brand/controllers/main.py
Labels: approved, bot is merging ⏳

#499 [13.0] [MIG] website_sale_secondary_unit: Migration to v13.0
  oca_dependencies.txt
  setup/website_sale_secondary_unit/odoo/addons/website_sale_secondary_unit
  setup/website_sale_secondary_unit/setup.py
  website_sale_secondary_unit/README.rst
  website_sale_secondary_unit/__init__.py
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/controllers/__init__.py
  website_sale_secondary_unit/controllers/main.py
  website_sale_secondary_unit/data/demo.xml
  website_sale_secondary_unit/hooks.py
  website_sale_secondary_unit/i18n/ca.po
  website_sale_secondary_unit/i18n/de.po
  website_sale_secondary_unit/i18n/es.po
  website_sale_secondary_unit/i18n/fr.po
  website_sale_secondary_unit/i18n/it.po
  website_sale_secondary_unit/i18n/website_sale_secondary_unit.pot
  website_sale_secondary_unit/models/__init__.py
  website_sale_secondary_unit/models/product_secondary_unit.py
  website_sale_secondary_unit/models/product_template.py
  website_sale_secondary_unit/models/sale_order.py
  website_sale_secondary_unit/readme/CONFIGURE.rst
  website_sale_secondary_unit/readme/CONTRIBUTORS.rst
  website_sale_secondary_unit/readme/DESCRIPTION.rst
  website_sale_secondary_unit/readme/USAGE.rst
  website_sale_secondary_unit/security/website_sale_secondary_unit.xml
  website_sale_secondary_unit/static/description/icon.png
  website_sale_secondary_unit/static/description/index.html
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit.js
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit_tour.js
  website_sale_secondary_unit/static/src/scss/website_sale_secondary_unit.scss
  website_sale_secondary_unit/templates/assets.xml
  website_sale_secondary_unit/tests/__init__.py
  website_sale_secondary_unit/tests/test_website_sale_secondary_unit.py
  website_sale_secondary_unit/views/assets.xml
  website_sale_secondary_unit/views/product_secondary_unit_views.xml
  website_sale_secondary_unit/views/product_template_views.xml
  website_sale_secondary_unit/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#497 [13.0][MIG] website_sale_tax_toggle: Migration
  setup/website_sale_tax_toggle/odoo/addons/website_sale_tax_toggle
  setup/website_sale_tax_toggle/setup.py
  website_sale_tax_toggle/README.rst
  website_sale_tax_toggle/__init__.py
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/controllers/__init__.py
  website_sale_tax_toggle/controllers/main.py
  website_sale_tax_toggle/demo/assets.xml
  website_sale_tax_toggle/i18n/ca.po
  website_sale_tax_toggle/i18n/es.po
  website_sale_tax_toggle/i18n/fr.po
  website_sale_tax_toggle/i18n/website_sale_tax_toggle.pot
  website_sale_tax_toggle/models/__init__.py
  website_sale_tax_toggle/models/res_users.py
  website_sale_tax_toggle/readme/CONTRIBUTORS.rst
  website_sale_tax_toggle/readme/DESCRIPTION.rst
  website_sale_tax_toggle/readme/USAGE.rst
  website_sale_tax_toggle/static/description/icon.png
  website_sale_tax_toggle/static/description/index.html
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.js
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/static/src/scss/website_sale_tax_toggle.scss
  website_sale_tax_toggle/tests/__init__.py
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
  website_sale_tax_toggle/views/assets.xml
  website_sale_tax_toggle/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#505 [13.0] [MIG] website_sale_checkout_country_vat: Migration to v13.0
  oca_dependencies.txt
  setup/website_sale_checkout_country_vat/odoo/addons/website_sale_checkout_country_vat
  setup/website_sale_checkout_country_vat/setup.py
  website_sale_checkout_country_vat/README.rst
  website_sale_checkout_country_vat/__init__.py
  website_sale_checkout_country_vat/__manifest__.py
  website_sale_checkout_country_vat/i18n/ca.po
  website_sale_checkout_country_vat/i18n/es.po
  website_sale_checkout_country_vat/i18n/fr.po
  website_sale_checkout_country_vat/i18n/website_sale_checkout_country_vat.pot
  website_sale_checkout_country_vat/readme/CONFIGURE.rst
  website_sale_checkout_country_vat/readme/CONTRIBUTORS.rst
  website_sale_checkout_country_vat/readme/DESCRIPTION.rst
  website_sale_checkout_country_vat/readme/USAGE.rst
  website_sale_checkout_country_vat/static/description/icon.png
  website_sale_checkout_country_vat/static/description/index.html
  website_sale_checkout_country_vat/static/src/js/dropdown.js
  website_sale_checkout_country_vat/views/assets.xml
  website_sale_checkout_country_vat/views/templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#507 [13.0][MIG] website_sale_product_attachment: Migration to 13.0
  setup/website_sale_product_attachment/odoo/addons/website_sale_product_attachment
  setup/website_sale_product_attachment/setup.py
  website_sale_product_attachment/README.rst
  website_sale_product_attachment/__init__.py
  website_sale_product_attachment/__manifest__.py
  website_sale_product_attachment/demo/assets.xml
  website_sale_product_attachment/i18n/ca.po
  website_sale_product_attachment/i18n/es.po
  website_sale_product_attachment/i18n/fr.po
  website_sale_product_attachment/i18n/nl.po
  website_sale_product_attachment/i18n/website_sale_product_attachment.pot
  website_sale_product_attachment/models/__init__.py
  website_sale_product_attachment/models/ir_attachment.py
  website_sale_product_attachment/models/product_template.py
  website_sale_product_attachment/readme/CONFIGURE.rst
  website_sale_product_attachment/readme/CONTRIBUTORS.rst
  website_sale_product_attachment/readme/DESCRIPTION.rst
  website_sale_product_attachment/readme/USAGE.rst
  website_sale_product_attachment/static/description/backend-attachment.png
  website_sale_product_attachment/static/description/backend-product.png
  website_sale_product_attachment/static/description/frontend-download.gif
  website_sale_product_attachment/static/description/frontend-icons.png
  website_sale_product_attachment/static/description/icon.png
  website_sale_product_attachment/static/description/index.html
  website_sale_product_attachment/static/src/js/website_tour.js
  website_sale_product_attachment/templates/product_template.xml
  website_sale_product_attachment/tests/__init__.py
  website_sale_product_attachment/tests/test_tour.py
  website_sale_product_attachment/views/ir_attachment.xml
  website_sale_product_attachment/views/product_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#514 [13.0][FIX] website_sale_stock_available_display: Fix on availabillity render
  website_sale_stock_available_display/static/src/js/website_sale_stock_available_display_tour.js
  website_sale_stock_available_display/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_available_display/templates/templates.xml
Labels: approved, bot is merging ⏳

#460 [12.0] [FIX] website_sale_product_minimal_price: Bug with formulas
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
Labels: approved, bot is merging ⏳

#470 [FIX] website_sale_stock_force_block: prevent add to cart
  website_sale_stock_force_block/models/__init__.py
  website_sale_stock_force_block/models/sale_order.py
Labels: approved, bot is merging ⏳

#513 [13.0][MIG] website_sale_product_sort: Migration script for change res.config.setting stored value
  website_sale_product_sort/migrations/13.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳

#517 [13.0][IMP] website_sale_tax_toggle: Making test more resilient
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
Labels: approved, bot is merging ⏳

#508 [13.0] [MIG] website_sale_b2x_alt_price: Migration to v13.0
  setup/website_sale_b2x_alt_price/odoo/addons/website_sale_b2x_alt_price
  setup/website_sale_b2x_alt_price/setup.py
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/i18n/ca.po
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/fr.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/readme/CONFIGURE.rst
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.rst
  website_sale_b2x_alt_price/readme/DESCRIPTION.rst
  website_sale_b2x_alt_price/readme/ROADMAP.rst
  website_sale_b2x_alt_price/readme/USAGE.rst
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.js
  website_sale_b2x_alt_price/static/tours/b2b.js
  website_sale_b2x_alt_price/static/tours/b2c.js
  website_sale_b2x_alt_price/templates/assets.xml
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
Labels: approved, bot is merging ⏳, ready to merge

#519 [12.0][FIX] website_sale_vat_required: Fix tests
  website_sale_vat_required/static/src/js/website_sale_vat_required.tour.js
Labels: approved, bot is merging ⏳, bug, needs review

#518 [13.0][FIX] website_sale_product_minimal_price: Fix tests
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
Labels: bot is merging ⏳
