Repository OCA/e-commerce, pull requests merged in 2021-09, with the labels that each got.

#566 [FIX] website_sale_secondary_unit: Remove bad view
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/migrations/13.0.1.1.1/pre-delete-view.py
Labels: bot is merging ⏳

#567 [12.0][FIX] website_sale_product_minimal_price: default variant
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/ROADMAP.rst
  website_sale_product_minimal_price/static/description/index.html
Labels: approved

#568 [13.0][MIG] website_sale_order_type: Migration to 13.0
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/demo/assets.xml
  website_sale_order_type/i18n/ca.po
  website_sale_order_type/i18n/es.po
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/sale_order.py
  website_sale_order_type/readme/CONTRIBUTORS.rst
  website_sale_order_type/readme/DESCRIPTION.rst
  website_sale_order_type/readme/USAGE.rst
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/src/js/website_sale_order_type_tour.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, bot is merging ⏳

#563 [13.0][ADD] website_sale_cart_expire
  setup/website_sale_cart_expire/odoo/addons/website_sale_cart_expire
  setup/website_sale_cart_expire/setup.py
  website_sale_cart_expire/__init__.py
  website_sale_cart_expire/__manifest__.py
  website_sale_cart_expire/data/ir_cron.xml
  website_sale_cart_expire/models/__init__.py
  website_sale_cart_expire/models/res_config_settings.py
  website_sale_cart_expire/models/sale_order.py
  website_sale_cart_expire/models/website.py
  website_sale_cart_expire/readme/CONFIGURE.rst
  website_sale_cart_expire/readme/CONTRIBUTORS.rst
  website_sale_cart_expire/readme/DESCRIPTION.rst
  website_sale_cart_expire/tests/__init__.py
  website_sale_cart_expire/tests/test_website_sale_cart_expire.py
  website_sale_cart_expire/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#570 [14.0][MIG] website_sale_order_type: Migration to 14.0
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/demo/assets.xml
  website_sale_order_type/i18n/ca.po
  website_sale_order_type/i18n/es.po
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/sale_order.py
  website_sale_order_type/readme/CONTRIBUTORS.rst
  website_sale_order_type/readme/DESCRIPTION.rst
  website_sale_order_type/readme/USAGE.rst
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/src/js/website_sale_order_type_tour.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, bot is merging ⏳

#527 [13.0][MIG] website_snippet_carousel_product: Migration to v13
  setup/website_snippet_carousel_product/odoo/addons/website_snippet_carousel_product
  setup/website_snippet_carousel_product/setup.py
  website_snippet_carousel_product/README.rst
  website_snippet_carousel_product/__init__.py
  website_snippet_carousel_product/__manifest__.py
  website_snippet_carousel_product/controllers/__init__.py
  website_snippet_carousel_product/controllers/website.py
  website_snippet_carousel_product/i18n/ca.po
  website_snippet_carousel_product/i18n/es.po
  website_snippet_carousel_product/i18n/fr.po
  website_snippet_carousel_product/i18n/nl.po
  website_snippet_carousel_product/i18n/website_snippet_carousel_product.pot
  website_snippet_carousel_product/readme/CONFIGURE.rst
  website_snippet_carousel_product/readme/CONTRIBUTORS.rst
  website_snippet_carousel_product/readme/DESCRIPTION.rst
  website_snippet_carousel_product/readme/ROADMAP.rst
  website_snippet_carousel_product/readme/USAGE.rst
  website_snippet_carousel_product/static/description/icon.png
  website_snippet_carousel_product/static/description/index.html
  website_snippet_carousel_product/static/src/js/s_product_carousel_frontend.js
  website_snippet_carousel_product/static/src/js/snippet.options.js
  website_snippet_carousel_product/static/src/scss/s_product_carousel.scss
  website_snippet_carousel_product/templates/assets.xml
  website_snippet_carousel_product/templates/snippet.xml
Labels: approved, bot is merging ⏳
