Repository OCA/e-commerce, pull requests merged in 2021-07, with the labels that each got.

#552 [13.0][ADD]Website Account Fiscal Position Partner Type
  oca_dependencies.txt
  setup/website_account_fiscal_position_partner_type/odoo/addons/website_account_fiscal_position_partner_type
  setup/website_account_fiscal_position_partner_type/setup.py
  website_account_fiscal_position_partner_type/__init__.py
  website_account_fiscal_position_partner_type/__manifest__.py
  website_account_fiscal_position_partner_type/controllers/__init__.py
  website_account_fiscal_position_partner_type/controllers/main.py
  website_account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  website_account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  website_account_fiscal_position_partner_type/readme/USAGE.rst
  website_account_fiscal_position_partner_type/static/description/icon.png
  website_account_fiscal_position_partner_type/views/website_sale.xml
Labels: bot is merging ⏳

#538 [12.0][FIX] website_sale_secondary_unit: Fixed price computation
  website_sale_secondary_unit/README.rst
  website_sale_secondary_unit/readme/CONTRIBUTORS.rst
  website_sale_secondary_unit/static/description/index.html
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit.js
Labels: approved, bot is merging ⏳

#551 [FIX] website_snippet_product_category: don't handle unpublished
  website_snippet_product_category/templates/snippets.xml
Labels: approved, bot is merging ⏳

#540 [13.0][IMP] website_sale_product_minimal_price: Forward port of improvements of 12.0
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/demo/assets.xml
  website_sale_product_minimal_price/i18n/ca.po
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/nl.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONFIGURE.rst
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/static/src/js/test_product_with_no_prices_tour.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_price_scale.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_price_scale.xml
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_product_with_no_prices.py
  website_sale_product_minimal_price/views/assets.xml
Labels: bot is merging ⏳

#556 [12.0][FIX] website_sale_secondary_unit: Remove sudo access to avoid to display unpublished secondary units.
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/security/ir.model.access.csv
  website_sale_secondary_unit/views/templates.xml
Labels: approved, bot is merging ⏳

#558 [13.0][FIX] website_sale_secondary_unit: Remove sudo access to avoid to display unpublished secondary units.
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/security/ir.model.access.csv
  website_sale_secondary_unit/views/templates.xml
Labels: approved, bot is merging ⏳

#443 [13.0][MIG] website_sale_require_legal: Migration to 13.0
  setup/website_sale_require_legal/odoo/addons/website_sale_require_legal
  setup/website_sale_require_legal/setup.py
  website_sale_require_legal/README.rst
  website_sale_require_legal/__init__.py
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/controllers/__init__.py
  website_sale_require_legal/controllers/main.py
  website_sale_require_legal/i18n/de.po
  website_sale_require_legal/i18n/es.po
  website_sale_require_legal/i18n/fi.po
  website_sale_require_legal/i18n/hr.po
  website_sale_require_legal/i18n/it.po
  website_sale_require_legal/i18n/sl.po
  website_sale_require_legal/i18n/website_sale_require_legal.pot
  website_sale_require_legal/readme/CONFIGURE.rst
  website_sale_require_legal/readme/CONTRIBUTORS.rst
  website_sale_require_legal/readme/DESCRIPTION.rst
  website_sale_require_legal/readme/INSTALL.rst
  website_sale_require_legal/readme/ROADMAP.rst
  website_sale_require_legal/readme/USAGE.rst
  website_sale_require_legal/static/description/address-enable.png
  website_sale_require_legal/static/description/icon.png
  website_sale_require_legal/static/description/index.html
  website_sale_require_legal/static/description/payment-enable.png
  website_sale_require_legal/static/src/scss/website_sale_require_legal.scss
  website_sale_require_legal/static/tests/tours/tour.js
  website_sale_require_legal/templates/assets.xml
  website_sale_require_legal/templates/website_sale.xml
  website_sale_require_legal/tests/__init__.py
  website_sale_require_legal/tests/test_ui.py
Labels: bot is merging ⏳

#490 [MIG] product_variant_multi_link: Migration to 14.0
  product_variant_multi_link/README.rst
  product_variant_multi_link/__init__.py
  product_variant_multi_link/__manifest__.py
  product_variant_multi_link/i18n/nl.po
  product_variant_multi_link/i18n/product_variant_multi_link.pot
  product_variant_multi_link/models/__init__.py
  product_variant_multi_link/models/product_product.py
  product_variant_multi_link/models/product_template_link.py
  product_variant_multi_link/readme/CONTRIBUTORS.rst
  product_variant_multi_link/readme/CREDITS.rst
  product_variant_multi_link/readme/DESCRIPTION.rst
  product_variant_multi_link/readme/USAGE.rst
  product_variant_multi_link/static/description/icon.png
  product_variant_multi_link/static/description/index.html
  product_variant_multi_link/tests/__init__.py
  product_variant_multi_link/tests/test_product_template_link.py
  product_variant_multi_link/views/product_template_link_view.xml
  setup/product_variant_multi_link/odoo/addons/product_variant_multi_link
  setup/product_variant_multi_link/setup.py
Labels: approved, bot is merging ⏳, ready to merge
