Repository OCA/e-commerce, pull requests merged in 2021-12, with the labels that each got.

#593 [14.0][FW] product_variant_multi_link: multiple ports from 13.0
  product_variant_multi_link/__manifest__.py
  product_variant_multi_link/models/product_product.py
  product_variant_multi_link/tests/test_product_template_link.py
  product_variant_multi_link/views/product_product_view.xml
Labels: approved, bot is merging ⏳

#501 [13.0][IMP] Allow to select variant first, on product links
  product_variant_multi_link/models/product_template_link.py
  product_variant_multi_link/views/product_template_link_view.xml
Labels: bot is merging ⏳

#587 [MIG] website_sale_attribute_filter_form_submit: Migration to 13.0
  setup/website_sale_attribute_filter_form_submit/odoo/addons/website_sale_attribute_filter_form_submit
  setup/website_sale_attribute_filter_form_submit/setup.py
  website_sale_attribute_filter_form_submit/README.rst
  website_sale_attribute_filter_form_submit/__init__.py
  website_sale_attribute_filter_form_submit/__manifest__.py
  website_sale_attribute_filter_form_submit/i18n/es.po
  website_sale_attribute_filter_form_submit/i18n/website_sale_attribute_filter_form_submit.pot
  website_sale_attribute_filter_form_submit/readme/CONFIGURE.rst
  website_sale_attribute_filter_form_submit/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_form_submit/readme/DESCRIPTION.rst
  website_sale_attribute_filter_form_submit/readme/USAGE.rst
  website_sale_attribute_filter_form_submit/static/description/icon.png
  website_sale_attribute_filter_form_submit/static/description/index.html
  website_sale_attribute_filter_form_submit/static/description/manual_filter_configuration.png
  website_sale_attribute_filter_form_submit/static/description/manual_filter_usage.gif
  website_sale_attribute_filter_form_submit/static/src/js/website_sale.js
  website_sale_attribute_filter_form_submit/templates/assets.xml
  website_sale_attribute_filter_form_submit/templates/website_sale.xml
Labels: approved, ready to merge, bot is merging ⏳

#594 [FIX] website_sale_stock_provisioning_date: timezone
  website_sale_stock_provisioning_date/__init__.py
  website_sale_stock_provisioning_date/__manifest__.py
  website_sale_stock_provisioning_date/hooks.py
  website_sale_stock_provisioning_date/models/__init__.py
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#596 [13.0][IMP] website_snippet_product_category: Change website published field by published in snippet field
  website_snippet_product_category/README.rst
  website_snippet_product_category/__manifest__.py
  website_snippet_product_category/controllers/website.py
  website_snippet_product_category/demo/demo.xml
  website_snippet_product_category/demo/pages.xml
  website_snippet_product_category/migrations/13.0.2.0.0/pre-migration.py
  website_snippet_product_category/models/product_public_category.py
  website_snippet_product_category/readme/CONFIGURE.rst
  website_snippet_product_category/readme/CONTRIBUTORS.rst
  website_snippet_product_category/static/description/index.html
  website_snippet_product_category/templates/snippets.xml
  website_snippet_product_category/views/product_public_category.xml
Labels: bot is merging ⏳

#600 [13.0][IMP] website_snippet_product_category: Reduced the icon size of the main sections
  website_snippet_product_category/static/src/scss/snippet.scss
Labels: bot is merging ⏳

#599 [13.0][FIX] website_snippet_carousel_product: Use flexible height
  website_snippet_carousel_product/static/src/scss/s_product_carousel.scss
Labels: approved, bot is merging ⏳
