Repository OCA/e-commerce, pull requests merged in 2021-01, with the labels that each got.

#454 [12.0][MIG] website_sale_order_type: Migration to 12.0
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/demo/assets.xml
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/sale_order.py
  website_sale_order_type/readme/CONTRIBUTORS.rst
  website_sale_order_type/readme/DESCRIPTION.rst
  website_sale_order_type/readme/USAGE.rst
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/src/js/website_sale_order_type_tour.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#442 [12.0][ADD] website_sale_product_description
  website_sale_product_description/README.rst
  website_sale_product_description/__init__.py
  website_sale_product_description/__manifest__.py
  website_sale_product_description/data/demo_website_sale_product_description.xml
  website_sale_product_description/i18n/website_sale_product_description.pot
  website_sale_product_description/models/__init__.py
  website_sale_product_description/models/product.py
  website_sale_product_description/readme/CONTRIBUTORS.rst
  website_sale_product_description/readme/DESCRIPTION.rst
  website_sale_product_description/readme/USAGE.rst
  website_sale_product_description/static/description/index.html
  website_sale_product_description/static/description/product.png
  website_sale_product_description/static/description/website-product.png
  website_sale_product_description/views/product_template.xml
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#488 [FIX][13.0]website_sale_product_detail_attribute_image rename file
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
Labels: bot is merging ⏳
