Repository OCA/e-commerce, pull requests merged in 2021-11, with the labels that each got.

#581 [14.0][IMP] product_template_multi_link: Several improvements
  product_template_multi_link/README.rst
  product_template_multi_link/__init__.py
  product_template_multi_link/__manifest__.py
  product_template_multi_link/models/product_template.py
  product_template_multi_link/models/product_template_link.py
  product_template_multi_link/models/product_template_link_type.py
  product_template_multi_link/security/ir.model.access.csv
  product_template_multi_link/tests/__init__.py
  product_template_multi_link/tests/test_product_template_linker.py
  product_template_multi_link/wizards/__init__.py
  product_template_multi_link/wizards/product_template_linker.py
  product_template_multi_link/wizards/product_template_linker.xml
Labels: approved, bot is merging ⏳

#560 [MIG] website_sale_product_attribute_filter_visibility: Migration to 14.0
  setup/website_sale_product_attribute_filter_visibility/odoo/addons/website_sale_product_attribute_filter_visibility
  setup/website_sale_product_attribute_filter_visibility/setup.py
  website_sale_product_attribute_filter_visibility/README.rst
  website_sale_product_attribute_filter_visibility/__init__.py
  website_sale_product_attribute_filter_visibility/__manifest__.py
  website_sale_product_attribute_filter_visibility/controllers/__init__.py
  website_sale_product_attribute_filter_visibility/controllers/main.py
  website_sale_product_attribute_filter_visibility/i18n/es.po
  website_sale_product_attribute_filter_visibility/i18n/website_sale_product_attribute_filter_visibility.pot
  website_sale_product_attribute_filter_visibility/models/__init__.py
  website_sale_product_attribute_filter_visibility/models/product_attribute.py
  website_sale_product_attribute_filter_visibility/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_visibility/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_visibility/readme/USAGE.rst
  website_sale_product_attribute_filter_visibility/static/description/icon.png
  website_sale_product_attribute_filter_visibility/static/description/index.html
  website_sale_product_attribute_filter_visibility/static/src/js/website_sale_product_attribute_filter_visibility_tour.js
  website_sale_product_attribute_filter_visibility/tests/__init__.py
  website_sale_product_attribute_filter_visibility/tests/test_attribute_filter_visibility.py
  website_sale_product_attribute_filter_visibility/views/assets.xml
  website_sale_product_attribute_filter_visibility/views/product_attribute_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#582 [ADD] website_sale_google_tag_manager: New module
  setup/website_sale_google_tag_manager/odoo/addons/website_sale_google_tag_manager
  setup/website_sale_google_tag_manager/setup.py
  website_sale_google_tag_manager/README.rst
  website_sale_google_tag_manager/__init__.py
  website_sale_google_tag_manager/__manifest__.py
  website_sale_google_tag_manager/models/__init__.py
  website_sale_google_tag_manager/models/res_config_settings.py
  website_sale_google_tag_manager/models/website.py
  website_sale_google_tag_manager/readme/CONFIGURE.rst
  website_sale_google_tag_manager/readme/CONTRIBUTORS.rst
  website_sale_google_tag_manager/readme/DESCRIPTION.rst
  website_sale_google_tag_manager/static/description/icon.png
  website_sale_google_tag_manager/static/description/index.html
  website_sale_google_tag_manager/static/description/website_google_tag_manager.jpg
  website_sale_google_tag_manager/views/res_config_settings_view.xml
  website_sale_google_tag_manager/views/website_templates.xml
Labels: approved, bot is merging ⏳

#584 [14.0][MIG] website_sale_show_company_data: Migration to 14.0
  setup/website_sale_show_company_data/odoo/addons/website_sale_show_company_data
  setup/website_sale_show_company_data/setup.py
  website_sale_show_company_data/README.rst
  website_sale_show_company_data/__init__.py
  website_sale_show_company_data/__manifest__.py
  website_sale_show_company_data/i18n/ca.po
  website_sale_show_company_data/i18n/es.po
  website_sale_show_company_data/i18n/fr.po
  website_sale_show_company_data/i18n/website_sale_show_company_data.pot
  website_sale_show_company_data/readme/CONFIGURATION.rst
  website_sale_show_company_data/readme/CONTRIBUTORS.rst
  website_sale_show_company_data/readme/DESCRIPTION.rst
  website_sale_show_company_data/readme/USAGE.rst
  website_sale_show_company_data/static/description/icon.png
  website_sale_show_company_data/static/description/index.html
  website_sale_show_company_data/views/website_sale_address.xml
Labels: approved, bot is merging ⏳

#487 [14.0][ADD] website_sale_attribute_filter_form_submit
  website_sale_attribute_filter_form_submit/__init__.py
  website_sale_attribute_filter_form_submit/__manifest__.py
  website_sale_attribute_filter_form_submit/i18n/es.po
  website_sale_attribute_filter_form_submit/i18n/website_sale_attribute_filter_form_submit.pot
  website_sale_attribute_filter_form_submit/readme/CONFIGURE.rst
  website_sale_attribute_filter_form_submit/readme/CONTRIBUTORS.rst
  website_sale_attribute_filter_form_submit/readme/DESCRIPTION.rst
  website_sale_attribute_filter_form_submit/readme/USAGE.rst
  website_sale_attribute_filter_form_submit/static/description/icon.png
  website_sale_attribute_filter_form_submit/static/description/index.html
  website_sale_attribute_filter_form_submit/static/description/manual_filter_configuration.png
  website_sale_attribute_filter_form_submit/static/description/manual_filter_usage.gif
  website_sale_attribute_filter_form_submit/static/src/js/website_sale.js
  website_sale_attribute_filter_form_submit/templates/assets.xml
  website_sale_attribute_filter_form_submit/templates/website_sale.xml
Labels: approved, bot is merging ⏳

#589 [13.0][ADD] website_sale_product_item_cart_custom_qty: New module to allow add to cart custom quantity from product item
  setup/website_sale_product_item_cart_custom_qty/odoo/addons/website_sale_product_item_cart_custom_qty
  setup/website_sale_product_item_cart_custom_qty/setup.py
  website_sale_product_item_cart_custom_qty/README.rst
  website_sale_product_item_cart_custom_qty/__init__.py
  website_sale_product_item_cart_custom_qty/__manifest__.py
  website_sale_product_item_cart_custom_qty/readme/CONFIGURE.rst
  website_sale_product_item_cart_custom_qty/readme/CONTRIBUTORS.rst
  website_sale_product_item_cart_custom_qty/readme/DESCRIPTION.rst
  website_sale_product_item_cart_custom_qty/readme/USAGE.rst
  website_sale_product_item_cart_custom_qty/static/description/index.html
  website_sale_product_item_cart_custom_qty/static/src/js/tour.js
  website_sale_product_item_cart_custom_qty/static/src/scss/add_to_cart.scss
  website_sale_product_item_cart_custom_qty/tests/__init__.py
  website_sale_product_item_cart_custom_qty/tests/test_website_sale_product_item_cart_custom_qty.py
  website_sale_product_item_cart_custom_qty/views/assets.xml
  website_sale_product_item_cart_custom_qty/views/templates.xml
Labels: approved, bot is merging ⏳

#588 [14.0][MIG] website_sale_product_detail_attribute_value_image: Migration to 14.0
  setup/website_sale_product_detail_attribute_value_image/odoo/addons/website_sale_product_detail_attribute_value_image
  setup/website_sale_product_detail_attribute_value_image/setup.py
  website_sale_product_detail_attribute_value_image/README.rst
  website_sale_product_detail_attribute_value_image/__init__.py
  website_sale_product_detail_attribute_value_image/__manifest__.py
  website_sale_product_detail_attribute_value_image/demo/assets_tour.xml
  website_sale_product_detail_attribute_value_image/i18n/ca.po
  website_sale_product_detail_attribute_value_image/i18n/es.po
  website_sale_product_detail_attribute_value_image/i18n/fr.po
  website_sale_product_detail_attribute_value_image/i18n/website_sale_product_detail_attribute_value_image.pot
  website_sale_product_detail_attribute_value_image/models/__init__.py
  website_sale_product_detail_attribute_value_image/models/product_attribute_value.py
  website_sale_product_detail_attribute_value_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_value_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_value_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_value_image/readme/USAGE.rst
  website_sale_product_detail_attribute_value_image/static/description/icon.png
  website_sale_product_detail_attribute_value_image/static/description/index.html
  website_sale_product_detail_attribute_value_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_value_image/static/src/js/website_sale_product_detail_attribute_value_image_tour.js
  website_sale_product_detail_attribute_value_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_value_image/templates/assets.xml
  website_sale_product_detail_attribute_value_image/templates/shop_product.xml
  website_sale_product_detail_attribute_value_image/tests/__init__.py
  website_sale_product_detail_attribute_value_image/tests/test_website_sale_product_detail_attribute_value_image.py
  website_sale_product_detail_attribute_value_image/views/product_attribute_value_views.xml
Labels: approved, bot is merging ⏳

#590 [MIG] website_sale_stock_force_block: Migration to 13.0
  setup/website_sale_stock_force_block/odoo/addons/website_sale_stock_force_block
  setup/website_sale_stock_force_block/setup.py
  website_sale_stock_force_block/README.rst
  website_sale_stock_force_block/__init__.py
  website_sale_stock_force_block/__manifest__.py
  website_sale_stock_force_block/data/demo.xml
  website_sale_stock_force_block/hooks.py
  website_sale_stock_force_block/i18n/ca.po
  website_sale_stock_force_block/i18n/es.po
  website_sale_stock_force_block/i18n/fr.po
  website_sale_stock_force_block/i18n/nl.po
  website_sale_stock_force_block/i18n/website_sale_stock_force_block.pot
  website_sale_stock_force_block/models/__init__.py
  website_sale_stock_force_block/models/product_template.py
  website_sale_stock_force_block/models/res_config_settings.py
  website_sale_stock_force_block/models/sale_order.py
  website_sale_stock_force_block/readme/CONTRIBUTORS.rst
  website_sale_stock_force_block/readme/DESCRIPTION.rst
  website_sale_stock_force_block/readme/USAGE.rst
  website_sale_stock_force_block/static/description/icon.png
  website_sale_stock_force_block/static/description/index.html
  website_sale_stock_force_block/static/src/js/website_sale_stock_force_block.js
  website_sale_stock_force_block/static/src/js/website_sale_stock_force_block_tour.js
  website_sale_stock_force_block/static/src/xml/website_sale_stock_force_block.xml
  website_sale_stock_force_block/tests/__init__.py
  website_sale_stock_force_block/tests/test_website_sale_stock_force_block.py
  website_sale_stock_force_block/views/assets.xml
  website_sale_stock_force_block/views/product_template_views.xml
  website_sale_stock_force_block/views/templates.xml
Labels: approved, bot is merging ⏳

#154 [10.0][ADD] Status for unavailable products on website
  website_sale_product_unavailable/README.rst
  website_sale_product_unavailable/__init__.py
  website_sale_product_unavailable/__manifest__.py
  website_sale_product_unavailable/controllers/__init__.py
  website_sale_product_unavailable/controllers/main.py
  website_sale_product_unavailable/demo/product_product.xml
  website_sale_product_unavailable/models/__init__.py
  website_sale_product_unavailable/models/product_template.py
  website_sale_product_unavailable/static/description/icon.png
  website_sale_product_unavailable/static/src/xml/product_unavailable.xml
  website_sale_product_unavailable/tests/__init__.py
  website_sale_product_unavailable/tests/test_product_template.py
  website_sale_product_unavailable/tests/test_search_order.py
Labels: needs review, needs fixing, bot is merging ⏳, stale
