Repository OCA/e-commerce, pull requests merged in 2022-05, with the labels that each got.

#637 [13.0][FIX] CI
  website_sale_resource_booking/__manifest__.py
Labels: bot is merging ⏳

#636 [13.0][FIX] website_sale_resource_booking: calendar context
  website_sale_resource_booking/controllers/main.py
Labels: approved, bot is merging ⏳

#554 [14.0][MIG] website_sale_product_attribute_value_filter_existing: migration to 14.0
  CONTRIBUTING.md
  setup/website_sale_product_attribute_value_filter_existing/odoo/addons/website_sale_product_attribute_value_filter_existing
  setup/website_sale_product_attribute_value_filter_existing/setup.py
  website_sale_product_attribute_value_filter_existing/README.rst
  website_sale_product_attribute_value_filter_existing/__init__.py
  website_sale_product_attribute_value_filter_existing/__manifest__.py
  website_sale_product_attribute_value_filter_existing/controllers/__init__.py
  website_sale_product_attribute_value_filter_existing/controllers/main.py
  website_sale_product_attribute_value_filter_existing/i18n/ca.po
  website_sale_product_attribute_value_filter_existing/i18n/es.po
  website_sale_product_attribute_value_filter_existing/i18n/nl.po
  website_sale_product_attribute_value_filter_existing/i18n/website_sale_product_attribute_value_filter_existing.pot
  website_sale_product_attribute_value_filter_existing/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_value_filter_existing/readme/DESCRIPTION.rst
  website_sale_product_attribute_value_filter_existing/readme/USAGE.rst
  website_sale_product_attribute_value_filter_existing/static/description/icon.png
  website_sale_product_attribute_value_filter_existing/static/description/index.html
  website_sale_product_attribute_value_filter_existing/static/src/js/website_sale_product_attribute_value_filter_existing_tour.js
  website_sale_product_attribute_value_filter_existing/tests/__init__.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_attribute_value_filter_existing/views/assets.xml
  website_sale_product_attribute_value_filter_existing/views/templates.xml
Labels: approved, bot is merging ⏳

#641 [FIX] website_sale_secondary_unit: add_qty rounding when not integer secondary unit factor
  website_sale_secondary_unit/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#550 [14.0][MIG] website_sale_b2x_alt_price: Migration to V14
  setup/website_sale_b2x_alt_price/odoo/addons/website_sale_b2x_alt_price
  setup/website_sale_b2x_alt_price/setup.py
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/i18n/ca.po
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/fr.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/readme/CONFIGURE.rst
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.rst
  website_sale_b2x_alt_price/readme/DESCRIPTION.rst
  website_sale_b2x_alt_price/readme/ROADMAP.rst
  website_sale_b2x_alt_price/readme/USAGE.rst
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.js
  website_sale_b2x_alt_price/static/tours/b2b.js
  website_sale_b2x_alt_price/static/tours/b2c.js
  website_sale_b2x_alt_price/templates/assets.xml
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
Labels: bot is merging ⏳
