Repository OCA/e-commerce, pull requests merged in 2022-03, with the labels that each got.

#578 [14.0][MIG] website_sale_checkout_country_vat: Migration to 14.0
  setup/website_sale_checkout_country_vat/odoo/addons/website_sale_checkout_country_vat
  setup/website_sale_checkout_country_vat/setup.py
  website_sale_checkout_country_vat/README.rst
  website_sale_checkout_country_vat/__init__.py
  website_sale_checkout_country_vat/__manifest__.py
  website_sale_checkout_country_vat/i18n/ca.po
  website_sale_checkout_country_vat/i18n/es.po
  website_sale_checkout_country_vat/i18n/fr.po
  website_sale_checkout_country_vat/i18n/website_sale_checkout_country_vat.pot
  website_sale_checkout_country_vat/readme/CONFIGURE.rst
  website_sale_checkout_country_vat/readme/CONTRIBUTORS.rst
  website_sale_checkout_country_vat/readme/DESCRIPTION.rst
  website_sale_checkout_country_vat/readme/USAGE.rst
  website_sale_checkout_country_vat/static/description/icon.png
  website_sale_checkout_country_vat/static/description/index.html
  website_sale_checkout_country_vat/static/src/js/dropdown.js
  website_sale_checkout_country_vat/views/assets.xml
  website_sale_checkout_country_vat/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#616 [FIX] website_sale_product_minimal_price: Integration with website_sale_b2x_alt_price
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
Labels: approved, ready to merge, bot is merging ⏳

#623 [ADD] website_sale_comparison_hide_price: New module
  setup/website_sale_comparison_hide_price/odoo/addons/website_sale_comparison_hide_price
  setup/website_sale_comparison_hide_price/setup.py
  website_sale_comparison_hide_price/README.rst
  website_sale_comparison_hide_price/__init__.py
  website_sale_comparison_hide_price/__manifest__.py
  website_sale_comparison_hide_price/readme/CONTRIBUTORS.rst
  website_sale_comparison_hide_price/readme/DESCRIPTION.rst
  website_sale_comparison_hide_price/static/description/index.html
  website_sale_comparison_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#627 [13.0][FIX] website_sale_checkout_skip_payment: ensure the order isn't draft
  website_sale_checkout_skip_payment/controllers/main.py
Labels: approved, bot is merging ⏳

#626 [FIX] website_sale_comparison_hide_price: hide add to cart button
  website_sale_comparison_hide_price/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#591 [MIG] website_sale_cart_expire: Migration to 14.0
  setup/website_sale_cart_expire/odoo/addons/website_sale_cart_expire
  setup/website_sale_cart_expire/setup.py
  website_sale_cart_expire/README.rst
  website_sale_cart_expire/__init__.py
  website_sale_cart_expire/__manifest__.py
  website_sale_cart_expire/data/ir_cron.xml
  website_sale_cart_expire/i18n/website_sale_cart_expire.pot
  website_sale_cart_expire/models/__init__.py
  website_sale_cart_expire/models/res_config_settings.py
  website_sale_cart_expire/models/sale_order.py
  website_sale_cart_expire/models/website.py
  website_sale_cart_expire/readme/CONFIGURE.rst
  website_sale_cart_expire/readme/CONTRIBUTORS.rst
  website_sale_cart_expire/readme/DESCRIPTION.rst
  website_sale_cart_expire/static/description/icon.png
  website_sale_cart_expire/static/description/index.html
  website_sale_cart_expire/tests/__init__.py
  website_sale_cart_expire/tests/test_website_sale_cart_expire.py
  website_sale_cart_expire/views/res_config_settings.xml
Labels: approved, ready to merge, bot is merging ⏳

#629 [FIX] website_sale_product_sort: README
  website_sale_product_sort/readme/CONFIGURE.rst
Labels: bot is merging ⏳

#598 [MIG] website_sale_cart_expire: Migration to 12.0
  website_sale_cart_expire/README.rst
  website_sale_cart_expire/__init__.py
  website_sale_cart_expire/__manifest__.py
  website_sale_cart_expire/data/ir_cron.xml
  website_sale_cart_expire/i18n/website_sale_cart_expire.pot
  website_sale_cart_expire/models/__init__.py
  website_sale_cart_expire/models/res_config_settings.py
  website_sale_cart_expire/models/sale_order.py
  website_sale_cart_expire/models/website.py
  website_sale_cart_expire/readme/CONFIGURE.rst
  website_sale_cart_expire/readme/CONTRIBUTORS.rst
  website_sale_cart_expire/readme/DESCRIPTION.rst
  website_sale_cart_expire/static/description/icon.png
  website_sale_cart_expire/static/description/index.html
  website_sale_cart_expire/tests/__init__.py
  website_sale_cart_expire/tests/test_website_sale_cart_expire.py
  website_sale_cart_expire/views/res_config_settings.xml
Labels: question, approved, bot is merging ⏳
