Repository OCA/e-commerce, pull requests merged in 2022-10, with the labels that each got.

#671 [15.0][MIG] website_sale_product_description: migration to 15.0
  setup/website_sale_product_description/odoo/addons/website_sale_product_description
  setup/website_sale_product_description/setup.py
  website_sale_product_description/README.rst
  website_sale_product_description/__init__.py
  website_sale_product_description/__manifest__.py
  website_sale_product_description/data/demo_website_sale_product_description.xml
  website_sale_product_description/i18n/ca.po
  website_sale_product_description/i18n/es.po
  website_sale_product_description/i18n/es_AR.po
  website_sale_product_description/i18n/es_ES.po
  website_sale_product_description/i18n/nl.po
  website_sale_product_description/i18n/pt.po
  website_sale_product_description/i18n/website_sale_product_description.pot
  website_sale_product_description/models/__init__.py
  website_sale_product_description/models/product.py
  website_sale_product_description/readme/CONTRIBUTORS.rst
  website_sale_product_description/readme/DESCRIPTION.rst
  website_sale_product_description/readme/USAGE.rst
  website_sale_product_description/static/description/icon.png
  website_sale_product_description/static/description/index.html
  website_sale_product_description/static/description/product.png
  website_sale_product_description/static/description/website-product.png
  website_sale_product_description/views/product_template.xml
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#652 [15.0][MIG] website_sale_secondary_unit: Migration to 15.0
  setup/website_sale_secondary_unit/odoo/addons/website_sale_secondary_unit
  setup/website_sale_secondary_unit/setup.py
  website_sale_secondary_unit/README.rst
  website_sale_secondary_unit/__init__.py
  website_sale_secondary_unit/__manifest__.py
  website_sale_secondary_unit/controllers/__init__.py
  website_sale_secondary_unit/controllers/main.py
  website_sale_secondary_unit/data/demo.xml
  website_sale_secondary_unit/hooks.py
  website_sale_secondary_unit/i18n/ca.po
  website_sale_secondary_unit/i18n/de.po
  website_sale_secondary_unit/i18n/es.po
  website_sale_secondary_unit/i18n/fr.po
  website_sale_secondary_unit/i18n/it.po
  website_sale_secondary_unit/i18n/website_sale_secondary_unit.pot
  website_sale_secondary_unit/models/__init__.py
  website_sale_secondary_unit/models/product_secondary_unit.py
  website_sale_secondary_unit/models/product_template.py
  website_sale_secondary_unit/models/sale_order.py
  website_sale_secondary_unit/readme/CONFIGURE.rst
  website_sale_secondary_unit/readme/CONTRIBUTORS.rst
  website_sale_secondary_unit/readme/DESCRIPTION.rst
  website_sale_secondary_unit/readme/USAGE.rst
  website_sale_secondary_unit/security/ir.model.access.csv
  website_sale_secondary_unit/security/website_sale_secondary_unit.xml
  website_sale_secondary_unit/static/description/icon.png
  website_sale_secondary_unit/static/description/index.html
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit.js
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit_tour.js
  website_sale_secondary_unit/static/src/scss/website_sale_secondary_unit.scss
  website_sale_secondary_unit/tests/__init__.py
  website_sale_secondary_unit/tests/test_website_sale_secondary_unit.py
  website_sale_secondary_unit/views/product_secondary_unit_views.xml
  website_sale_secondary_unit/views/product_template_views.xml
  website_sale_secondary_unit/views/templates.xml
Labels: approved, bot is merging ⏳

#585 [14.0][MIG] website_sale_suggest_create_account: Migration to 14.0
  setup/website_sale_suggest_create_account/odoo/addons/website_sale_suggest_create_account
  setup/website_sale_suggest_create_account/setup.py
  website_sale_suggest_create_account/README.rst
  website_sale_suggest_create_account/__init__.py
  website_sale_suggest_create_account/__manifest__.py
  website_sale_suggest_create_account/hooks.py
  website_sale_suggest_create_account/i18n/ca.po
  website_sale_suggest_create_account/i18n/ca_ES.po
  website_sale_suggest_create_account/i18n/de.po
  website_sale_suggest_create_account/i18n/es.po
  website_sale_suggest_create_account/i18n/es_CO.po
  website_sale_suggest_create_account/i18n/fr.po
  website_sale_suggest_create_account/i18n/hr.po
  website_sale_suggest_create_account/i18n/it.po
  website_sale_suggest_create_account/i18n/nl.po
  website_sale_suggest_create_account/i18n/sl.po
  website_sale_suggest_create_account/i18n/website_sale_suggest_create_account.pot
  website_sale_suggest_create_account/readme/CONTRIBUTORS.rst
  website_sale_suggest_create_account/readme/DESCRIPTION.rst
  website_sale_suggest_create_account/readme/USAGE.rst
  website_sale_suggest_create_account/static/description/icon.png
  website_sale_suggest_create_account/static/description/index.html
  website_sale_suggest_create_account/static/tests/tours/checkout.js
  website_sale_suggest_create_account/tests/__init__.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_suggest_create_account/views/assets.xml
  website_sale_suggest_create_account/views/website_sale.xml
Labels: bot is merging ⏳, stale
