Repository OCA/e-commerce, pull requests merged in 2022-12, with the labels that each got.

#635 [14.0] [MIG] website_sale_wishlist_keep: Migration to 14.0
  setup/website_sale_wishlist_keep/odoo/addons/website_sale_wishlist_keep
  setup/website_sale_wishlist_keep/setup.py
  website_sale_wishlist_keep/README.rst
  website_sale_wishlist_keep/__init__.py
  website_sale_wishlist_keep/__manifest__.py
  website_sale_wishlist_keep/i18n/ca.po
  website_sale_wishlist_keep/i18n/es.po
  website_sale_wishlist_keep/i18n/fr.po
  website_sale_wishlist_keep/i18n/nl.po
  website_sale_wishlist_keep/i18n/website_sale_wishlist_keep.pot
  website_sale_wishlist_keep/readme/CONTRIBUTORS.rst
  website_sale_wishlist_keep/readme/DESCRIPTION.rst
  website_sale_wishlist_keep/readme/USAGE.rst
  website_sale_wishlist_keep/static/description/icon.png
  website_sale_wishlist_keep/static/description/index.html
  website_sale_wishlist_keep/static/src/js/tour.js
  website_sale_wishlist_keep/templates/assets.xml
  website_sale_wishlist_keep/tests/__init__.py
  website_sale_wishlist_keep/tests/test_ui.py
  website_sale_wishlist_keep/views/website_sale_wishlist_template.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#706 [15.0][MIG] website_sale_order_type: Migration to version 15.0
  setup/website_sale_order_type/odoo/addons/website_sale_order_type
  setup/website_sale_order_type/setup.py
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/i18n/ca.po
  website_sale_order_type/i18n/es.po
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/sale_order.py
  website_sale_order_type/readme/CONTRIBUTORS.rst
  website_sale_order_type/readme/DESCRIPTION.rst
  website_sale_order_type/readme/USAGE.rst
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/src/js/website_sale_order_type_tour.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, bot is merging ⏳

#643 [15.0][MIG] website_sale_product_detail_attribute_image: Migration to 15.0
  setup/website_sale_product_detail_attribute_image/odoo/addons/website_sale_product_detail_attribute_image
  setup/website_sale_product_detail_attribute_image/setup.py
  website_sale_product_detail_attribute_image/README.rst
  website_sale_product_detail_attribute_image/__init__.py
  website_sale_product_detail_attribute_image/__manifest__.py
  website_sale_product_detail_attribute_image/controllers/__init__.py
  website_sale_product_detail_attribute_image/controllers/main.py
  website_sale_product_detail_attribute_image/i18n/es.po
  website_sale_product_detail_attribute_image/i18n/es_AR.po
  website_sale_product_detail_attribute_image/i18n/nl.po
  website_sale_product_detail_attribute_image/i18n/pt.po
  website_sale_product_detail_attribute_image/i18n/website_sale_product_detail_attribute_image.pot
  website_sale_product_detail_attribute_image/models/__init__.py
  website_sale_product_detail_attribute_image/models/product_attribute.py
  website_sale_product_detail_attribute_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_image/readme/USAGE.rst
  website_sale_product_detail_attribute_image/static/description/icon.png
  website_sale_product_detail_attribute_image/static/description/index.html
  website_sale_product_detail_attribute_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_image/static/src/js/website_sale_product_detail_attribute_image_tour.js
  website_sale_product_detail_attribute_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_image/tests/__init__.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_product_detail_attribute_image/views/product_attribute_views.xml
  website_sale_product_detail_attribute_image/views/templates.xml
Labels: bot is merging ⏳, stale

#642 [15.0] [MIG] website_sale_tax_toggle: Migration to 15.0
  setup/website_sale_tax_toggle/odoo/addons/website_sale_tax_toggle
  setup/website_sale_tax_toggle/setup.py
  website_sale_tax_toggle/README.rst
  website_sale_tax_toggle/__init__.py
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/controllers/__init__.py
  website_sale_tax_toggle/controllers/main.py
  website_sale_tax_toggle/i18n/ca.po
  website_sale_tax_toggle/i18n/es.po
  website_sale_tax_toggle/i18n/fr.po
  website_sale_tax_toggle/i18n/nl.po
  website_sale_tax_toggle/i18n/website_sale_tax_toggle.pot
  website_sale_tax_toggle/models/__init__.py
  website_sale_tax_toggle/models/res_users.py
  website_sale_tax_toggle/readme/CONTRIBUTORS.rst
  website_sale_tax_toggle/readme/DESCRIPTION.rst
  website_sale_tax_toggle/readme/USAGE.rst
  website_sale_tax_toggle/static/description/icon.png
  website_sale_tax_toggle/static/description/index.html
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.js
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.js
  website_sale_tax_toggle/static/src/scss/website_sale_tax_toggle.scss
  website_sale_tax_toggle/tests/__init__.py
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
  website_sale_tax_toggle/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#712 [13.0][IMP] website_sale_secondary_unit: mobile UX
  website_sale_secondary_unit/views/templates.xml
Labels: bot is merging ⏳

#710 [16.0][MIG] website_sale_product_reference_displayed: Migration to 16.0
  setup/website_sale_product_reference_displayed/odoo/addons/website_sale_product_reference_displayed
  setup/website_sale_product_reference_displayed/setup.py
  website_sale_product_reference_displayed/README.rst
  website_sale_product_reference_displayed/__init__.py
  website_sale_product_reference_displayed/__manifest__.py
  website_sale_product_reference_displayed/data/snippet_filter_data.xml
  website_sale_product_reference_displayed/i18n/ca.po
  website_sale_product_reference_displayed/i18n/es.po
  website_sale_product_reference_displayed/i18n/fr.po
  website_sale_product_reference_displayed/i18n/website_sale_product_reference_displayed.pot
  website_sale_product_reference_displayed/models/__init__.py
  website_sale_product_reference_displayed/models/website_snippet_filter.py
  website_sale_product_reference_displayed/readme/CONTRIBUTORS.rst
  website_sale_product_reference_displayed/readme/DESCRIPTION.rst
  website_sale_product_reference_displayed/readme/USAGE.rst
  website_sale_product_reference_displayed/static/description/enable-product-reference.png
  website_sale_product_reference_displayed/static/description/icon.png
  website_sale_product_reference_displayed/static/description/index.html
  website_sale_product_reference_displayed/views/website_sale_views.xml
Labels: approved, bot is merging ⏳

#644 [15.0] [MIG] website_sale_product_sort: MIgration to 15.0
  setup/website_sale_product_sort/odoo/addons/website_sale_product_sort
  setup/website_sale_product_sort/setup.py
  website_sale_product_sort/README.rst
  website_sale_product_sort/__init__.py
  website_sale_product_sort/__manifest__.py
  website_sale_product_sort/controllers/__init__.py
  website_sale_product_sort/controllers/main.py
  website_sale_product_sort/i18n/ca.po
  website_sale_product_sort/i18n/es.po
  website_sale_product_sort/i18n/fr.po
  website_sale_product_sort/i18n/nl.po
  website_sale_product_sort/i18n/website_sale_product_sort.pot
  website_sale_product_sort/models/__init__.py
  website_sale_product_sort/models/res_config_settings.py
  website_sale_product_sort/models/website.py
  website_sale_product_sort/readme/CONFIGURE.rst
  website_sale_product_sort/readme/CONTRIBUTORS.rst
  website_sale_product_sort/readme/DESCRIPTION.rst
  website_sale_product_sort/readme/ROADMAP.rst
  website_sale_product_sort/readme/USAGE.rst
  website_sale_product_sort/static/description/icon.png
  website_sale_product_sort/static/description/index.html
  website_sale_product_sort/views/res_config_settings_view.xml
  website_sale_product_sort/views/website_sale_sort.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#649 [15.0][MIG] website_sale_b2x_alt_price: Migration to 15.0
  setup/website_sale_b2x_alt_price/odoo/addons/website_sale_b2x_alt_price
  setup/website_sale_b2x_alt_price/setup.py
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/i18n/ca.po
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/fr.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/readme/CONFIGURE.rst
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.rst
  website_sale_b2x_alt_price/readme/DESCRIPTION.rst
  website_sale_b2x_alt_price/readme/ROADMAP.rst
  website_sale_b2x_alt_price/readme/USAGE.rst
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.esm.js
  website_sale_b2x_alt_price/static/tours/b2b.js
  website_sale_b2x_alt_price/static/tours/b2c.js
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#674 [15.0][MIG] website_sale_vat_required
  setup/website_sale_vat_required/odoo/addons/website_sale_vat_required
  setup/website_sale_vat_required/setup.py
  website_sale_vat_required/README.rst
  website_sale_vat_required/__init__.py
  website_sale_vat_required/__manifest__.py
  website_sale_vat_required/controllers/__init__.py
  website_sale_vat_required/controllers/main.py
  website_sale_vat_required/i18n/ca.po
  website_sale_vat_required/i18n/es.po
  website_sale_vat_required/i18n/website_sale_vat_required.pot
  website_sale_vat_required/readme/CONTRIBUTORS.rst
  website_sale_vat_required/readme/DESCRIPTION.rst
  website_sale_vat_required/readme/USAGE.rst
  website_sale_vat_required/static/description/icon.png
  website_sale_vat_required/static/description/index.html
  website_sale_vat_required/static/src/js/website_sale_vat_required.tour.js
  website_sale_vat_required/tests/__init__.py
  website_sale_vat_required/tests/test_website_sale_vat_required.py
  website_sale_vat_required/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳
