Repository OCA/e-commerce, pull requests merged in 2022-07, with the labels that each got.

#661 [MIG] website_sale_product_assortment: Migration to 14.0
  setup/website_sale_product_assortment/odoo/addons/website_sale_product_assortment
  setup/website_sale_product_assortment/setup.py
  website_sale_product_assortment/README.rst
  website_sale_product_assortment/__init__.py
  website_sale_product_assortment/__manifest__.py
  website_sale_product_assortment/controllers/__init__.py
  website_sale_product_assortment/controllers/variant.py
  website_sale_product_assortment/controllers/website_sale.py
  website_sale_product_assortment/i18n/es.po
  website_sale_product_assortment/i18n/website_sale_product_assortment.pot
  website_sale_product_assortment/models/__init__.py
  website_sale_product_assortment/models/ir_filters.py
  website_sale_product_assortment/models/product_template.py
  website_sale_product_assortment/readme/CONFIGURE.rst
  website_sale_product_assortment/readme/CONTRIBUTORS.rst
  website_sale_product_assortment/readme/DESCRIPTION.rst
  website_sale_product_assortment/static/description/icon.png
  website_sale_product_assortment/static/description/index.html
  website_sale_product_assortment/static/src/js/assortment_list_preview.js
  website_sale_product_assortment/static/src/js/no_purchase_tour.js
  website_sale_product_assortment/static/src/js/no_restriction_tour.js
  website_sale_product_assortment/static/src/js/no_show_tour.js
  website_sale_product_assortment/static/src/js/variant_mixin.js
  website_sale_product_assortment/static/src/xml/website_sale_product_assortment.xml
  website_sale_product_assortment/templates/assets.xml
  website_sale_product_assortment/templates/website_sale_views.xml
  website_sale_product_assortment/tests/__init__.py
  website_sale_product_assortment/tests/test_ui.py
  website_sale_product_assortment/views/ir_filters_views.xml
Labels: approved, bot is merging ⏳

#653 [13.0][FIX] website_sale_secondary_unit: Avoid show non published secondary_units
  website_sale_secondary_unit/controllers/main.py
  website_sale_secondary_unit/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#665 [15.0][MIG] website_sale_product_detail_attribute_value_image: Migration to version 15.0
  setup/website_sale_product_detail_attribute_value_image/odoo/addons/website_sale_product_detail_attribute_value_image
  setup/website_sale_product_detail_attribute_value_image/setup.py
  website_sale_product_detail_attribute_value_image/README.rst
  website_sale_product_detail_attribute_value_image/__init__.py
  website_sale_product_detail_attribute_value_image/__manifest__.py
  website_sale_product_detail_attribute_value_image/i18n/ca.po
  website_sale_product_detail_attribute_value_image/i18n/es.po
  website_sale_product_detail_attribute_value_image/i18n/fr.po
  website_sale_product_detail_attribute_value_image/i18n/pt.po
  website_sale_product_detail_attribute_value_image/i18n/website_sale_product_detail_attribute_value_image.pot
  website_sale_product_detail_attribute_value_image/models/__init__.py
  website_sale_product_detail_attribute_value_image/models/product_attribute_value.py
  website_sale_product_detail_attribute_value_image/readme/CONTRIBUTORS.rst
  website_sale_product_detail_attribute_value_image/readme/CREDITS.rst
  website_sale_product_detail_attribute_value_image/readme/DESCRIPTION.rst
  website_sale_product_detail_attribute_value_image/readme/USAGE.rst
  website_sale_product_detail_attribute_value_image/static/description/icon.png
  website_sale_product_detail_attribute_value_image/static/description/index.html
  website_sale_product_detail_attribute_value_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_value_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_value_image/static/src/js/website_sale_product_detail_attribute_value_image_tour.js
  website_sale_product_detail_attribute_value_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_value_image/templates/shop_product.xml
  website_sale_product_detail_attribute_value_image/tests/__init__.py
  website_sale_product_detail_attribute_value_image/tests/test_website_sale_product_detail_attribute_value_image.py
  website_sale_product_detail_attribute_value_image/views/product_attribute_value_views.xml
Labels: approved, bot is merging ⏳

#664 [15.0][MIG] website_sale_product_reference_displayed: Migration to 15.0
  setup/website_sale_product_reference_displayed/odoo/addons/website_sale_product_reference_displayed
  setup/website_sale_product_reference_displayed/setup.py
  website_sale_product_reference_displayed/README.rst
  website_sale_product_reference_displayed/__init__.py
  website_sale_product_reference_displayed/__manifest__.py
  website_sale_product_reference_displayed/i18n/ca.po
  website_sale_product_reference_displayed/i18n/es.po
  website_sale_product_reference_displayed/i18n/fr.po
  website_sale_product_reference_displayed/i18n/website_sale_product_reference_displayed.pot
  website_sale_product_reference_displayed/readme/CONTRIBUTORS.rst
  website_sale_product_reference_displayed/readme/DESCRIPTION.rst
  website_sale_product_reference_displayed/readme/USAGE.rst
  website_sale_product_reference_displayed/static/description/enable-product-reference.png
  website_sale_product_reference_displayed/static/description/icon.png
  website_sale_product_reference_displayed/static/description/index.html
  website_sale_product_reference_displayed/views/website_sale_views.xml
Labels: approved, bot is merging ⏳

#639 [IMP] website_sale_hide_price: hide price at product level
  website_sale_comparison_hide_price/views/website_sale_template.xml
  website_sale_hide_price/README.rst
  website_sale_hide_price/__init__.py
  website_sale_hide_price/__manifest__.py
  website_sale_hide_price/controllers/__init__.py
  website_sale_hide_price/controllers/main.py
  website_sale_hide_price/models/__init__.py
  website_sale_hide_price/models/product_template.py
  website_sale_hide_price/models/res_config_settings.py
  website_sale_hide_price/models/website.py
  website_sale_hide_price/readme/CONFIGURE.rst
  website_sale_hide_price/readme/CONTRIBUTORS.rst
  website_sale_hide_price/readme/DESCRIPTION.rst
  website_sale_hide_price/readme/ROADMAP.rst
  website_sale_hide_price/readme/USAGE.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/static/src/js/website_sale_hide_price.js
  website_sale_hide_price/static/src/xml/website_sale_templates.xml
  website_sale_hide_price/views/assets.xml
  website_sale_hide_price/views/product_template_views.xml
  website_sale_hide_price/views/res_config_settings_views.xml
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#549 [MIG] website_sale_stock_provisioning_date: Migration to 14.0
  setup/website_sale_stock_provisioning_date/odoo/addons/website_sale_stock_provisioning_date
  setup/website_sale_stock_provisioning_date/setup.py
  website_sale_stock_provisioning_date/README.rst
  website_sale_stock_provisioning_date/__init__.py
  website_sale_stock_provisioning_date/__manifest__.py
  website_sale_stock_provisioning_date/i18n/es.po
  website_sale_stock_provisioning_date/i18n/website_sale_stock_provisioning_date.pot
  website_sale_stock_provisioning_date/models/__init__.py
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/product_template.py
  website_sale_stock_provisioning_date/readme/CONTRIBUTORS.rst
  website_sale_stock_provisioning_date/readme/DESCRIPTION.rst
  website_sale_stock_provisioning_date/readme/USAGE.rst
  website_sale_stock_provisioning_date/static/description/icon.png
  website_sale_stock_provisioning_date/static/description/index.html
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date.js
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date_tour.js
  website_sale_stock_provisioning_date/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_provisioning_date/tests/__init__.py
  website_sale_stock_provisioning_date/tests/test_website_sale_stock_provisioning_date.py
  website_sale_stock_provisioning_date/views/assets.xml
  website_sale_stock_provisioning_date/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#646 [15.0] [MIG] website_sale_suggest_create_account: Migration to 15.0
  setup/website_sale_suggest_create_account/odoo/addons/website_sale_suggest_create_account
  setup/website_sale_suggest_create_account/setup.py
  website_sale_suggest_create_account/README.rst
  website_sale_suggest_create_account/__init__.py
  website_sale_suggest_create_account/__manifest__.py
  website_sale_suggest_create_account/hooks.py
  website_sale_suggest_create_account/i18n/ca.po
  website_sale_suggest_create_account/i18n/ca_ES.po
  website_sale_suggest_create_account/i18n/de.po
  website_sale_suggest_create_account/i18n/es.po
  website_sale_suggest_create_account/i18n/es_CO.po
  website_sale_suggest_create_account/i18n/fr.po
  website_sale_suggest_create_account/i18n/hr.po
  website_sale_suggest_create_account/i18n/it.po
  website_sale_suggest_create_account/i18n/nl.po
  website_sale_suggest_create_account/i18n/sl.po
  website_sale_suggest_create_account/i18n/website_sale_suggest_create_account.pot
  website_sale_suggest_create_account/readme/CONTRIBUTORS.rst
  website_sale_suggest_create_account/readme/DESCRIPTION.rst
  website_sale_suggest_create_account/readme/USAGE.rst
  website_sale_suggest_create_account/static/description/icon.png
  website_sale_suggest_create_account/static/description/index.html
  website_sale_suggest_create_account/static/tests/tours/checkout.js
  website_sale_suggest_create_account/tests/__init__.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_suggest_create_account/views/website_sale.xml
Labels: bot is merging ⏳
