Repository OCA/e-commerce, pull requests merged in 2023-10, with the labels that each got.

#856 [15.0][FIX]website_account_fiscal_position_partner_type: Translated account fiscal positions in portal
  website_account_fiscal_position_partner_type/controllers/main.py
  website_account_fiscal_position_partner_type/controllers/portal.py
Labels: approved, bot is merging ⏳

#849 [15.0][FIX] website_sale_checkout_skip_payment: order confirmation
  website_sale_checkout_skip_payment/__manifest__.py
  website_sale_checkout_skip_payment/controllers/main.py
  website_sale_checkout_skip_payment/static/src/tests/tours/website_sale_checkout_skip_payment_tour.js
  website_sale_checkout_skip_payment/tests/test_checkout_skip_payment.py
Labels: approved, ready to merge, bot is merging ⏳

#860 [15.0][FIX] website_sale_product_attribute_value_filter_existing: Add tagged to avoid warning
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
Labels: bot is merging ⏳

#836 [16.0][MIG] website_sale_suggest_create_account: Migration to version 16.0
  setup/website_sale_suggest_create_account/odoo/addons/website_sale_suggest_create_account
  setup/website_sale_suggest_create_account/setup.py
  website_sale_suggest_create_account/README.rst
  website_sale_suggest_create_account/__init__.py
  website_sale_suggest_create_account/__manifest__.py
  website_sale_suggest_create_account/hooks.py
  website_sale_suggest_create_account/i18n/ca.po
  website_sale_suggest_create_account/i18n/ca_ES.po
  website_sale_suggest_create_account/i18n/de.po
  website_sale_suggest_create_account/i18n/es.po
  website_sale_suggest_create_account/i18n/es_CO.po
  website_sale_suggest_create_account/i18n/fr.po
  website_sale_suggest_create_account/i18n/hr.po
  website_sale_suggest_create_account/i18n/it.po
  website_sale_suggest_create_account/i18n/nl.po
  website_sale_suggest_create_account/i18n/sl.po
  website_sale_suggest_create_account/i18n/website_sale_suggest_create_account.pot
  website_sale_suggest_create_account/readme/CONTRIBUTORS.rst
  website_sale_suggest_create_account/readme/DESCRIPTION.rst
  website_sale_suggest_create_account/readme/USAGE.rst
  website_sale_suggest_create_account/static/description/icon.png
  website_sale_suggest_create_account/static/description/index.html
  website_sale_suggest_create_account/static/tests/tours/checkout.js
  website_sale_suggest_create_account/tests/__init__.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_suggest_create_account/views/website_sale.xml
Labels: approved, ready to merge, bot is merging ⏳

#859 [15.0][IMP] e-commerce : test performance improvement
  website_sale_b2x_alt_price/tests/test_ui.py
  website_sale_checkout_skip_payment/tests/test_checkout_skip_payment.py
  website_sale_hide_empty_category/tests/test_has_product_recursive.py
  website_sale_hide_empty_category/tests/test_ui.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_brand/tests/test_ui.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_secondary_unit/tests/test_website_sale_secondary_unit.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
  website_sale_wishlist_keep/tests/test_ui.py
Labels: approved, bot is merging ⏳

#861 [16.0][FIX] website_sale_product_attribute_value_filter_existing: fix test to check the real functionality of the module
  website_sale_product_attribute_value_filter_existing/static/src/js/website_sale_product_attribute_value_filter_existing_tour.esm.js
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
Labels: approved, bot is merging ⏳

#850 [16.0][MIG] website_sale_require_legal: Migration to version 16.0
  setup/website_sale_require_legal/odoo/addons/website_sale_require_legal
  setup/website_sale_require_legal/setup.py
  website_sale_require_legal/README.rst
  website_sale_require_legal/__init__.py
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/controllers/__init__.py
  website_sale_require_legal/controllers/main.py
  website_sale_require_legal/i18n/de.po
  website_sale_require_legal/i18n/es.po
  website_sale_require_legal/i18n/fi.po
  website_sale_require_legal/i18n/hr.po
  website_sale_require_legal/i18n/it.po
  website_sale_require_legal/i18n/sl.po
  website_sale_require_legal/i18n/website_sale_require_legal.pot
  website_sale_require_legal/readme/CONFIGURE.rst
  website_sale_require_legal/readme/CONTEXT.rst
  website_sale_require_legal/readme/CONTRIBUTORS.rst
  website_sale_require_legal/readme/DESCRIPTION.rst
  website_sale_require_legal/readme/ROADMAP.rst
  website_sale_require_legal/readme/USAGE.rst
  website_sale_require_legal/static/description/address-enable.png
  website_sale_require_legal/static/description/icon.png
  website_sale_require_legal/static/description/index.html
  website_sale_require_legal/static/description/payment-enable.png
  website_sale_require_legal/static/src/scss/website_sale_require_legal.scss
  website_sale_require_legal/static/tests/tours/tour.js
  website_sale_require_legal/templates/website_sale.xml
  website_sale_require_legal/tests/__init__.py
  website_sale_require_legal/tests/test_ui.py
Labels: approved, bot is merging ⏳

#862 [16.0][IMP] e-commerce : test performance improvement
  website_sale_checkout_skip_payment/tests/test_checkout_skip_payment.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_brand/tests/test_ui.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_wishlist_keep/tests/test_ui.py
Labels: bot is merging ⏳
