Repository OCA/e-commerce, pull requests merged in 2023-02, with the labels that each got.

#743 [14.0][MIG] website_sale_invoice_address
  setup/website_sale_invoice_address/odoo/addons/website_sale_invoice_address
  setup/website_sale_invoice_address/setup.py
  website_sale_invoice_address/README.rst
  website_sale_invoice_address/__init__.py
  website_sale_invoice_address/__manifest__.py
  website_sale_invoice_address/i18n/ca.po
  website_sale_invoice_address/i18n/es.po
  website_sale_invoice_address/i18n/website_sale_invoice_address.pot
  website_sale_invoice_address/models/__init__.py
  website_sale_invoice_address/models/sale_order.py
  website_sale_invoice_address/models/website.py
  website_sale_invoice_address/readme/CONTRIBUTORS.rst
  website_sale_invoice_address/readme/DESCRIPTION.rst
  website_sale_invoice_address/readme/USAGE.rst
  website_sale_invoice_address/static/description/icon.png
  website_sale_invoice_address/static/description/index.html
  website_sale_invoice_address/static/src/js/website_sale_invoice_address_tour.js
  website_sale_invoice_address/tests/__init__.py
  website_sale_invoice_address/tests/test_website_sale_invoice_address.py
  website_sale_invoice_address/views/assets.xml
Labels: approved, bot is merging ⏳

#735 [15.0][MIG] website_sale_attribute_filter_order > website_sale_product_attribute_filter_order: Migration to version 15.0
  setup/website_sale_product_attribute_filter_order/odoo/addons/website_sale_product_attribute_filter_order
  setup/website_sale_product_attribute_filter_order/setup.py
  website_sale_product_attribute_filter_order/README.rst
  website_sale_product_attribute_filter_order/__init__.py
  website_sale_product_attribute_filter_order/__manifest__.py
  website_sale_product_attribute_filter_order/i18n/ca.po
  website_sale_product_attribute_filter_order/i18n/es.po
  website_sale_product_attribute_filter_order/i18n/website_sale_product_attribute_filter_order.pot
  website_sale_product_attribute_filter_order/readme/CONFIGURE.rst
  website_sale_product_attribute_filter_order/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_order/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_order/readme/ROADMAP.rst
  website_sale_product_attribute_filter_order/readme/USAGE.rst
  website_sale_product_attribute_filter_order/static/description/attributes00.png
  website_sale_product_attribute_filter_order/static/description/icon.png
  website_sale_product_attribute_filter_order/static/description/index.html
  website_sale_product_attribute_filter_order/templates/website_sale.xml
Labels: approved, ready to merge, bot is merging ⏳

#744 [15.0][FIX] website_sale_attribute_filter_category: Added configuration option in menu "/shop/Customize".
  website_sale_product_attribute_filter_category/README.rst
  website_sale_product_attribute_filter_category/readme/USAGE.rst
  website_sale_product_attribute_filter_category/static/description/index.html
  website_sale_product_attribute_filter_category/tests/test_website_sale_product_attribute_filter_category.py
  website_sale_product_attribute_filter_category/views/templates.xml
Labels: approved, bot is merging ⏳

#740 [15.0][ADD] website_sale_product_attribute_filter_collapse: New module
  setup/website_sale_product_attribute_filter_collapse/odoo/addons/website_sale_product_attribute_filter_collapse
  setup/website_sale_product_attribute_filter_collapse/setup.py
  website_sale_product_attribute_filter_collapse/README.rst
  website_sale_product_attribute_filter_collapse/__init__.py
  website_sale_product_attribute_filter_collapse/__manifest__.py
  website_sale_product_attribute_filter_collapse/readme/CONFIGURE.rst
  website_sale_product_attribute_filter_collapse/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_collapse/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_collapse/readme/USAGE.rst
  website_sale_product_attribute_filter_collapse/static/description/index.html
  website_sale_product_attribute_filter_collapse/static/src/js/website_sale_product_attribute_filter_collapse.js
  website_sale_product_attribute_filter_collapse/static/src/scss/website_sale_product_attribute_filter_collapse.scss
  website_sale_product_attribute_filter_collapse/tests/__init__.py
  website_sale_product_attribute_filter_collapse/tests/test_tour.py
  website_sale_product_attribute_filter_collapse/views/templates.xml
Labels: bot is merging ⏳

#726 [15.0][MIG] website_sale_stock_provisioning_date: Migration to 15.0
  setup/website_sale_stock_provisioning_date/odoo/addons/website_sale_stock_provisioning_date
  setup/website_sale_stock_provisioning_date/setup.py
  website_sale_stock_provisioning_date/README.rst
  website_sale_stock_provisioning_date/__init__.py
  website_sale_stock_provisioning_date/__manifest__.py
  website_sale_stock_provisioning_date/i18n/es.po
  website_sale_stock_provisioning_date/i18n/website_sale_stock_provisioning_date.pot
  website_sale_stock_provisioning_date/models/__init__.py
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/product_template.py
  website_sale_stock_provisioning_date/readme/CONTRIBUTORS.rst
  website_sale_stock_provisioning_date/readme/DESCRIPTION.rst
  website_sale_stock_provisioning_date/readme/USAGE.rst
  website_sale_stock_provisioning_date/static/description/icon.png
  website_sale_stock_provisioning_date/static/description/index.html
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date.js
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date_tour.js
  website_sale_stock_provisioning_date/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_provisioning_date/tests/__init__.py
  website_sale_stock_provisioning_date/tests/test_website_sale_stock_provisioning_date.py
  website_sale_stock_provisioning_date/views/product_template_views.xml
Labels: approved, bot is merging ⏳

#749 [15.0][MIG] website_snippet_product_category: Migration to version 15.0
  setup/website_snippet_product_category/odoo/addons/website_snippet_product_category
  setup/website_snippet_product_category/setup.py
  website_snippet_product_category/README.rst
  website_snippet_product_category/__init__.py
  website_snippet_product_category/__manifest__.py
  website_snippet_product_category/controllers/__init__.py
  website_snippet_product_category/controllers/website.py
  website_snippet_product_category/demo/demo.xml
  website_snippet_product_category/demo/pages.xml
  website_snippet_product_category/i18n/ca.po
  website_snippet_product_category/i18n/es.po
  website_snippet_product_category/i18n/fr.po
  website_snippet_product_category/i18n/nl.po
  website_snippet_product_category/i18n/website_snippet_product_category.pot
  website_snippet_product_category/models/__init__.py
  website_snippet_product_category/models/product_public_category.py
  website_snippet_product_category/readme/CONFIGURE.rst
  website_snippet_product_category/readme/CONTRIBUTORS.rst
  website_snippet_product_category/readme/CREDITS.rst
  website_snippet_product_category/readme/DESCRIPTION.rst
  website_snippet_product_category/readme/ROADMAP.rst
  website_snippet_product_category/readme/USAGE.rst
  website_snippet_product_category/static/description/icon.png
  website_snippet_product_category/static/description/index.html
  website_snippet_product_category/static/img/boxes_32.png
  website_snippet_product_category/static/src/img/s_product_category.png
  website_snippet_product_category/static/src/js/frontend.js
  website_snippet_product_category/static/src/js/snippet.options.js
  website_snippet_product_category/static/src/scss/snippet.scss
  website_snippet_product_category/templates/snippets.xml
  website_snippet_product_category/views/product_public_category.xml
Labels: approved, bot is merging ⏳

#747 [15.0][MIG] website_sale_product_assortment: Migration to version 15.0
  setup/website_sale_product_assortment/odoo/addons/website_sale_product_assortment
  setup/website_sale_product_assortment/setup.py
  website_sale_product_assortment/README.rst
  website_sale_product_assortment/__init__.py
  website_sale_product_assortment/__manifest__.py
  website_sale_product_assortment/controllers/__init__.py
  website_sale_product_assortment/controllers/variant.py
  website_sale_product_assortment/controllers/website_sale.py
  website_sale_product_assortment/i18n/es.po
  website_sale_product_assortment/i18n/it.po
  website_sale_product_assortment/i18n/website_sale_product_assortment.pot
  website_sale_product_assortment/models/__init__.py
  website_sale_product_assortment/models/ir_filters.py
  website_sale_product_assortment/models/product_template.py
  website_sale_product_assortment/readme/CONFIGURE.rst
  website_sale_product_assortment/readme/CONTRIBUTORS.rst
  website_sale_product_assortment/readme/DESCRIPTION.rst
  website_sale_product_assortment/static/description/icon.png
  website_sale_product_assortment/static/description/index.html
  website_sale_product_assortment/static/src/js/assortment_list_preview.js
  website_sale_product_assortment/static/src/js/no_purchase_tour.js
  website_sale_product_assortment/static/src/js/no_restriction_tour.js
  website_sale_product_assortment/static/src/js/no_show_tour.js
  website_sale_product_assortment/static/src/js/variant_mixin.js
  website_sale_product_assortment/static/src/xml/website_sale_product_assortment.xml
  website_sale_product_assortment/templates/website_sale_views.xml
  website_sale_product_assortment/tests/__init__.py
  website_sale_product_assortment/tests/test_ui.py
  website_sale_product_assortment/views/ir_filters_views.xml
Labels: approved, bot is merging ⏳

#750 [15.0][FIX] website_sale_product_description: Move the product description text closer to the image carousel
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#737 [14.0][MIG] website_sale_hide_empty_category
  setup/website_sale_hide_empty_category/odoo/addons/website_sale_hide_empty_category
  setup/website_sale_hide_empty_category/setup.py
  website_sale_hide_empty_category/README.rst
  website_sale_hide_empty_category/__init__.py
  website_sale_hide_empty_category/__manifest__.py
  website_sale_hide_empty_category/i18n/ca.po
  website_sale_hide_empty_category/i18n/es.po
  website_sale_hide_empty_category/i18n/nl.po
  website_sale_hide_empty_category/i18n/website_sale_hide_empty_category.pot
  website_sale_hide_empty_category/models/__init__.py
  website_sale_hide_empty_category/models/product_public_category.py
  website_sale_hide_empty_category/readme/CONTRIBUTORS.rst
  website_sale_hide_empty_category/readme/DESCRIPTION.rst
  website_sale_hide_empty_category/readme/USAGE.rst
  website_sale_hide_empty_category/static/description/icon.png
  website_sale_hide_empty_category/static/description/index.html
  website_sale_hide_empty_category/static/src/js/tour.js
  website_sale_hide_empty_category/tests/__init__.py
  website_sale_hide_empty_category/tests/test_has_product_recursive.py
  website_sale_hide_empty_category/tests/test_ui.py
  website_sale_hide_empty_category/views/assets.xml
  website_sale_hide_empty_category/views/website_sale_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#752 [14.0][IMP] website_sale_checkout_skip_payment: hide new payment message
  website_sale_checkout_skip_payment/readme/CONTRIBUTORS.rst
  website_sale_checkout_skip_payment/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#753 [15.0][IMP] website_sale_checkout_skip_payment: hide payment message
  website_sale_checkout_skip_payment/readme/CONTRIBUTORS.rst
  website_sale_checkout_skip_payment/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#756 [FIX][website_sale_cart_expire] fix singleton
  website_sale_cart_expire/models/website.py
Labels: approved, bot is merging ⏳

#760 [15.0][FIX] website_sale_checkout_skip_payment: Increase priority to avoid crash with other views without dependencies
  website_sale_checkout_skip_payment/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#761 [15.0][FIX] website_sale_require_legal: remove dependency to website_legal_page
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/templates/website_sale.xml
Labels: approved, bot is merging ⏳

#708 [MIG] website_sale_stock_available: Migration to 16.0
  setup/website_sale_stock_available/odoo/addons/website_sale_stock_available
  setup/website_sale_stock_available/setup.py
  website_sale_stock_available/README.rst
  website_sale_stock_available/__init__.py
  website_sale_stock_available/__manifest__.py
  website_sale_stock_available/controllers/__init__.py
  website_sale_stock_available/controllers/main.py
  website_sale_stock_available/i18n/ca.po
  website_sale_stock_available/i18n/es.po
  website_sale_stock_available/i18n/es_AR.po
  website_sale_stock_available/i18n/es_CL.po
  website_sale_stock_available/i18n/fr.po
  website_sale_stock_available/i18n/nl.po
  website_sale_stock_available/i18n/website_sale_stock_available.pot
  website_sale_stock_available/models/__init__.py
  website_sale_stock_available/models/product_product.py
  website_sale_stock_available/models/product_template.py
  website_sale_stock_available/models/sale_order.py
  website_sale_stock_available/readme/CONFIGURE.rst
  website_sale_stock_available/readme/CONTRIBUTORS.rst
  website_sale_stock_available/readme/DESCRIPTION.rst
  website_sale_stock_available/readme/USAGE.rst
  website_sale_stock_available/static/description/availability_message.png
  website_sale_stock_available/static/description/icon.png
  website_sale_stock_available/static/description/index.html
  website_sale_stock_available/tests/__init__.py
  website_sale_stock_available/tests/test_website_sale_stock_available.py
Labels: approved, ready to merge, bot is merging ⏳
