Repository OCA/e-commerce, pull requests merged in 2023-04, with the labels that each got.

#776 [15.0][IMP] website_sale_product_attribute_filter_collapse: changes to the template
  website_sale_product_attribute_filter_collapse/static/src/scss/website_sale_product_attribute_filter_collapse.scss
  website_sale_product_attribute_filter_collapse/views/templates.xml
Labels: bot is merging ⏳

#781 [15.0][FIX] website_sale_product_attribute_filter_collapse: fix test error
  website_sale_product_attribute_filter_collapse/tests/test_tour.py
Labels: approved, bot is merging ⏳

#773 [16.0][MIG] website_sale_product_attribute_value_filter_existing: Migration to 16.0
  setup/website_sale_product_attribute_value_filter_existing/odoo/addons/website_sale_product_attribute_value_filter_existing
  setup/website_sale_product_attribute_value_filter_existing/setup.py
  website_sale_product_attribute_value_filter_existing/README.rst
  website_sale_product_attribute_value_filter_existing/__init__.py
  website_sale_product_attribute_value_filter_existing/__manifest__.py
  website_sale_product_attribute_value_filter_existing/controllers/__init__.py
  website_sale_product_attribute_value_filter_existing/controllers/main.py
  website_sale_product_attribute_value_filter_existing/i18n/ca.po
  website_sale_product_attribute_value_filter_existing/i18n/es.po
  website_sale_product_attribute_value_filter_existing/i18n/nl.po
  website_sale_product_attribute_value_filter_existing/i18n/website_sale_product_attribute_value_filter_existing.pot
  website_sale_product_attribute_value_filter_existing/readme/CONFIGURATION.rst
  website_sale_product_attribute_value_filter_existing/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_value_filter_existing/readme/CREDITS.rst
  website_sale_product_attribute_value_filter_existing/readme/DESCRIPTION.rst
  website_sale_product_attribute_value_filter_existing/static/description/icon.png
  website_sale_product_attribute_value_filter_existing/static/description/index.html
  website_sale_product_attribute_value_filter_existing/static/src/js/website_sale_product_attribute_value_filter_existing_tour.esm.js
  website_sale_product_attribute_value_filter_existing/tests/__init__.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_attribute_value_filter_existing/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#715 [15.0][IMP] website_sale_secondary_unit: mobile UX
  website_sale_secondary_unit/views/templates.xml
Labels: bot is merging ⏳, stale

#762 [14.0][ADD] website_sale_filter_product_brand
  oca_dependencies.txt
  setup/website_sale_filter_product_brand/odoo/addons/website_sale_filter_product_brand
  setup/website_sale_filter_product_brand/setup.py
  website_sale_filter_product_brand/README.rst
  website_sale_filter_product_brand/__init__.py
  website_sale_filter_product_brand/__manifest__.py
  website_sale_filter_product_brand/controllers/__init__.py
  website_sale_filter_product_brand/controllers/website_sale.py
  website_sale_filter_product_brand/demo/product_brand_demo.xml
  website_sale_filter_product_brand/demo/product_product_demo.xml
  website_sale_filter_product_brand/readme/CONTRIBUTORS.rst
  website_sale_filter_product_brand/readme/DESCRIPTION.rst
  website_sale_filter_product_brand/readme/USAGE.rst
  website_sale_filter_product_brand/static/description/icon.png
  website_sale_filter_product_brand/static/src/js/website_sale_product_brand_filter.js
  website_sale_filter_product_brand/static/src/scss/website_sale_product_brand_filter.scss
  website_sale_filter_product_brand/static/src/tests/tours/test_website_sale_filter_brand.js
  website_sale_filter_product_brand/tests/__init__.py
  website_sale_filter_product_brand/tests/test_website_sale_filter_brand.py
  website_sale_filter_product_brand/views/assets.xml
  website_sale_filter_product_brand/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#788 [13.0][IMP] website_sale_b2x_alt_price: Add price without tax to the quotation in the portal
  website_sale_b2x_alt_price/templates/product.xml
Labels: approved, bot is merging ⏳

#786 [15.0][IMP] website_sale_b2x_alt_price: Add price without tax to the quotation in the portal
  website_sale_b2x_alt_price/templates/product.xml
Labels: approved, bot is merging ⏳
