Repository OCA/e-commerce, pull requests merged in 2023-05, with the labels that each got.

#640 [14.0] [MIG] website_sale_stock_list_preview: Migration to 14.0
  setup/website_sale_stock_list_preview/odoo/addons/website_sale_stock_list_preview
  setup/website_sale_stock_list_preview/setup.py
  website_sale_payment_term_acquirer/tests/test_website_sale.py
  website_sale_stock_list_preview/README.rst
  website_sale_stock_list_preview/__init__.py
  website_sale_stock_list_preview/__manifest__.py
  website_sale_stock_list_preview/controllers/__init__.py
  website_sale_stock_list_preview/controllers/main.py
  website_sale_stock_list_preview/i18n/es.po
  website_sale_stock_list_preview/i18n/website_sale_stock_list_preview.pot
  website_sale_stock_list_preview/readme/CONTRIBUTORS.rst
  website_sale_stock_list_preview/readme/DESCRIPTION.rst
  website_sale_stock_list_preview/readme/USAGE.rst
  website_sale_stock_list_preview/static/description/icon.png
  website_sale_stock_list_preview/static/description/index.html
  website_sale_stock_list_preview/static/src/js/tour.js
  website_sale_stock_list_preview/static/src/js/website_sale_stock_list_preview.js
  website_sale_stock_list_preview/tests/__init__.py
  website_sale_stock_list_preview/tests/test_ui.py
  website_sale_stock_list_preview/views/assets.xml
  website_sale_stock_list_preview/views/templates.xml
Labels: bot is merging ⏳

#793 [14.0][MIG] website_sale_product_item_cart_custom_qty: Migration to 14.0
  setup/website_sale_product_item_cart_custom_qty/odoo/addons/website_sale_product_item_cart_custom_qty
  setup/website_sale_product_item_cart_custom_qty/setup.py
  website_sale_product_item_cart_custom_qty/README.rst
  website_sale_product_item_cart_custom_qty/__init__.py
  website_sale_product_item_cart_custom_qty/__manifest__.py
  website_sale_product_item_cart_custom_qty/i18n/website_sale_product_item_cart_custom_qty.pot
  website_sale_product_item_cart_custom_qty/readme/CONFIGURE.rst
  website_sale_product_item_cart_custom_qty/readme/CONTRIBUTORS.rst
  website_sale_product_item_cart_custom_qty/readme/DESCRIPTION.rst
  website_sale_product_item_cart_custom_qty/readme/USAGE.rst
  website_sale_product_item_cart_custom_qty/static/description/icon.png
  website_sale_product_item_cart_custom_qty/static/description/index.html
  website_sale_product_item_cart_custom_qty/static/src/js/tour.js
  website_sale_product_item_cart_custom_qty/static/src/scss/add_to_cart.scss
  website_sale_product_item_cart_custom_qty/tests/__init__.py
  website_sale_product_item_cart_custom_qty/tests/test_website_sale_product_item_cart_custom_qty.py
  website_sale_product_item_cart_custom_qty/views/assets.xml
  website_sale_product_item_cart_custom_qty/views/templates.xml
Labels: approved, bot is merging ⏳

#797 [16.0][FIX] website_sale_product_attribute_value_filter_existing: match signature
  website_sale_product_attribute_value_filter_existing/controllers/main.py
Labels: bot is merging ⏳

#791 [16.0][MIG] website_sale_product_description: Migration to 16.0
  setup/website_sale_product_description/odoo/addons/website_sale_product_description
  setup/website_sale_product_description/setup.py
  website_sale_product_description/README.rst
  website_sale_product_description/__init__.py
  website_sale_product_description/__manifest__.py
  website_sale_product_description/data/demo_website_sale_product_description.xml
  website_sale_product_description/i18n/ca.po
  website_sale_product_description/i18n/es.po
  website_sale_product_description/i18n/es_AR.po
  website_sale_product_description/i18n/es_ES.po
  website_sale_product_description/i18n/nl.po
  website_sale_product_description/i18n/pt.po
  website_sale_product_description/i18n/website_sale_product_description.pot
  website_sale_product_description/models/__init__.py
  website_sale_product_description/models/product.py
  website_sale_product_description/readme/CONTRIBUTORS.rst
  website_sale_product_description/readme/DESCRIPTION.rst
  website_sale_product_description/readme/USAGE.rst
  website_sale_product_description/static/description/icon.png
  website_sale_product_description/static/description/index.html
  website_sale_product_description/static/description/product.png
  website_sale_product_description/static/description/website-product.png
  website_sale_product_description/views/product_template.xml
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#806 [15.0][FIX] website_sale_hide_price: fix key error when editing snippet
  website_sale_hide_price/__manifest__.py
  website_sale_hide_price/data/product_snippet_template_data.xml
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳
