Repository OCA/e-commerce, pull requests merged in 2023-01, with the labels that each got.

#672 [13.0][FIX] website_sale_stock_provisioning_date: reception in two steps + website warehouse
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/product_template.py
  website_sale_stock_provisioning_date/static/src/xml/website_sale_stock_product_availability.xml
Labels: bot is merging ⏳, stale

#719 Adding contributor in README.rst
  website_sale_product_reference_displayed/README.rst
Labels: approved, bot is merging ⏳

#720 Adding contributors in readme.rst
  website_sale_product_reference_displayed/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#724 [15.0][MIG] website_sale_product_item_cart_custom_qty: Migration to version 15.0
  setup/website_sale_product_item_cart_custom_qty/odoo/addons/website_sale_product_item_cart_custom_qty
  setup/website_sale_product_item_cart_custom_qty/setup.py
  website_sale_product_item_cart_custom_qty/README.rst
  website_sale_product_item_cart_custom_qty/__init__.py
  website_sale_product_item_cart_custom_qty/__manifest__.py
  website_sale_product_item_cart_custom_qty/i18n/website_sale_product_item_cart_custom_qty.pot
  website_sale_product_item_cart_custom_qty/readme/CONFIGURE.rst
  website_sale_product_item_cart_custom_qty/readme/CONTRIBUTORS.rst
  website_sale_product_item_cart_custom_qty/readme/DESCRIPTION.rst
  website_sale_product_item_cart_custom_qty/readme/USAGE.rst
  website_sale_product_item_cart_custom_qty/static/description/icon.png
  website_sale_product_item_cart_custom_qty/static/description/index.html
  website_sale_product_item_cart_custom_qty/static/src/js/tour.js
  website_sale_product_item_cart_custom_qty/static/src/scss/add_to_cart.scss
  website_sale_product_item_cart_custom_qty/tests/__init__.py
  website_sale_product_item_cart_custom_qty/tests/test_website_sale_product_item_cart_custom_qty.py
  website_sale_product_item_cart_custom_qty/views/templates.xml
Labels: approved, bot is merging ⏳

#727 [15.0][MIG] website_sale_product_attribute_filter_category: Migration to version 15.0
  setup/website_sale_product_attribute_filter_category/odoo/addons/website_sale_product_attribute_filter_category
  setup/website_sale_product_attribute_filter_category/setup.py
  website_sale_product_attribute_filter_category/README.rst
  website_sale_product_attribute_filter_category/__init__.py
  website_sale_product_attribute_filter_category/__manifest__.py
  website_sale_product_attribute_filter_category/controllers/__init__.py
  website_sale_product_attribute_filter_category/controllers/main.py
  website_sale_product_attribute_filter_category/i18n/ca.po
  website_sale_product_attribute_filter_category/i18n/es.po
  website_sale_product_attribute_filter_category/i18n/fi.po
  website_sale_product_attribute_filter_category/i18n/nl.po
  website_sale_product_attribute_filter_category/i18n/website_sale_product_attribute_filter_category.pot
  website_sale_product_attribute_filter_category/models/__init__.py
  website_sale_product_attribute_filter_category/models/product_attribute_category.py
  website_sale_product_attribute_filter_category/readme/CONFIGURE.rst
  website_sale_product_attribute_filter_category/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_filter_category/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_category/readme/USAGE.rst
  website_sale_product_attribute_filter_category/static/description/icon.png
  website_sale_product_attribute_filter_category/static/description/index.html
  website_sale_product_attribute_filter_category/static/src/js/website_sale_attribute_filter_category_tour.js
  website_sale_product_attribute_filter_category/static/src/scss/website_sale_attribute_filter_category.scss
  website_sale_product_attribute_filter_category/tests/__init__.py
  website_sale_product_attribute_filter_category/tests/test_website_sale_product_attribute_filter_category.py
  website_sale_product_attribute_filter_category/views/templates.xml
  website_sale_product_attribute_filter_category/views/website_sale_product_attribute_filter_category_view.xml
Labels: approved, bot is merging ⏳

#707 [14.0][ADD] website_sale_payment_term_acquirer
  setup/website_sale_payment_term_acquirer/odoo/addons/website_sale_payment_term_acquirer
  setup/website_sale_payment_term_acquirer/setup.py
  website_sale_payment_term_acquirer/README.rst
  website_sale_payment_term_acquirer/__init__.py
  website_sale_payment_term_acquirer/__manifest__.py
  website_sale_payment_term_acquirer/controllers/__init__.py
  website_sale_payment_term_acquirer/controllers/main.py
  website_sale_payment_term_acquirer/demo/demo.xml
  website_sale_payment_term_acquirer/models/__init__.py
  website_sale_payment_term_acquirer/models/payment_acquirer.py
  website_sale_payment_term_acquirer/models/sale_order.py
  website_sale_payment_term_acquirer/readme/CONTRIBUTORS.rst
  website_sale_payment_term_acquirer/readme/DESCRIPTION.rst
  website_sale_payment_term_acquirer/readme/USAGE.rst
  website_sale_payment_term_acquirer/tests/__init__.py
  website_sale_payment_term_acquirer/tests/test_sale_order.py
  website_sale_payment_term_acquirer/tests/test_website_sale.py
  website_sale_payment_term_acquirer/views/payment_acquirer_views.xml
  website_sale_payment_term_acquirer/views/payment_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#733 [15.0][MIG] website_sale_require_legal: Migration to version 15.0
  setup/website_sale_require_legal/odoo/addons/website_sale_require_legal
  setup/website_sale_require_legal/setup.py
  website_sale_require_legal/README.rst
  website_sale_require_legal/__init__.py
  website_sale_require_legal/__manifest__.py
  website_sale_require_legal/controllers/__init__.py
  website_sale_require_legal/controllers/main.py
  website_sale_require_legal/i18n/de.po
  website_sale_require_legal/i18n/es.po
  website_sale_require_legal/i18n/fi.po
  website_sale_require_legal/i18n/hr.po
  website_sale_require_legal/i18n/it.po
  website_sale_require_legal/i18n/sl.po
  website_sale_require_legal/i18n/website_sale_require_legal.pot
  website_sale_require_legal/readme/CONFIGURE.rst
  website_sale_require_legal/readme/CONTRIBUTORS.rst
  website_sale_require_legal/readme/DESCRIPTION.rst
  website_sale_require_legal/readme/ROADMAP.rst
  website_sale_require_legal/readme/USAGE.rst
  website_sale_require_legal/static/description/address-enable.png
  website_sale_require_legal/static/description/icon.png
  website_sale_require_legal/static/description/index.html
  website_sale_require_legal/static/description/payment-enable.png
  website_sale_require_legal/static/src/scss/website_sale_require_legal.scss
  website_sale_require_legal/static/tests/tours/tour.js
  website_sale_require_legal/templates/website_sale.xml
  website_sale_require_legal/tests/__init__.py
  website_sale_require_legal/tests/test_ui.py
Labels: approved, bot is merging ⏳

#738 [15.0][FIX] website_sale_product_attribute_filter_category: Removed products_attributes_collapsible template + migration script
  website_sale_product_attribute_filter_category/README.rst
  website_sale_product_attribute_filter_category/migrations/15.0.1.0.0/pre-migration.py
  website_sale_product_attribute_filter_category/readme/DESCRIPTION.rst
  website_sale_product_attribute_filter_category/static/description/index.html
  website_sale_product_attribute_filter_category/views/templates.xml
Labels: approved, bot is merging ⏳

#709 [14.0][FIX] website_sale_product_description: Move the product description text closer to the image carousel
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#723 [14.0][MIG] website_sale_product_attachment: Migration to 14.0
  setup/website_sale_product_attachment/odoo/addons/website_sale_product_attachment
  setup/website_sale_product_attachment/setup.py
  website_sale_product_attachment/README.rst
  website_sale_product_attachment/__init__.py
  website_sale_product_attachment/__manifest__.py
  website_sale_product_attachment/demo/assets.xml
  website_sale_product_attachment/i18n/ca.po
  website_sale_product_attachment/i18n/es.po
  website_sale_product_attachment/i18n/fr.po
  website_sale_product_attachment/i18n/nl.po
  website_sale_product_attachment/i18n/website_sale_product_attachment.pot
  website_sale_product_attachment/migrations/13.0.2.0.0/post-migration.py
  website_sale_product_attachment/migrations/13.0.2.0.0/pre-migration.py
  website_sale_product_attachment/models/__init__.py
  website_sale_product_attachment/models/ir_attachment.py
  website_sale_product_attachment/models/product_template.py
  website_sale_product_attachment/readme/CONFIGURE.rst
  website_sale_product_attachment/readme/CONTRIBUTORS.rst
  website_sale_product_attachment/readme/DESCRIPTION.rst
  website_sale_product_attachment/readme/ROADMAP.rst
  website_sale_product_attachment/readme/USAGE.rst
  website_sale_product_attachment/static/description/backend-attachment.png
  website_sale_product_attachment/static/description/backend-product.png
  website_sale_product_attachment/static/description/frontend-download.gif
  website_sale_product_attachment/static/description/frontend-icons.png
  website_sale_product_attachment/static/description/icon.png
  website_sale_product_attachment/static/description/index.html
  website_sale_product_attachment/static/src/js/website_tour.js
  website_sale_product_attachment/templates/product_template.xml
  website_sale_product_attachment/tests/__init__.py
  website_sale_product_attachment/tests/test_tour.py
  website_sale_product_attachment/views/ir_attachment.xml
  website_sale_product_attachment/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳
