Repository OCA/e-commerce, pull requests merged in 2023-11, with the labels that each got.

#871 [16.0][FIX] website_sale_hide_price: Error loading view after update
  website_sale_hide_price/README.rst
  website_sale_hide_price/readme/CONTRIBUTORS.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#867 [16.0][FIX] website_sale_require_legal: Test compatibility with website_sale_vat_required module
  website_sale_require_legal/static/tests/tours/tour.js
Labels: approved, bot is merging ⏳

#841 [16.0][MIG] website_sale_vat_required: Migration to version 16.0
  setup/website_sale_vat_required/odoo/addons/website_sale_vat_required
  setup/website_sale_vat_required/setup.py
  website_sale_vat_required/README.rst
  website_sale_vat_required/__init__.py
  website_sale_vat_required/__manifest__.py
  website_sale_vat_required/controllers/__init__.py
  website_sale_vat_required/controllers/main.py
  website_sale_vat_required/i18n/ca.po
  website_sale_vat_required/i18n/es.po
  website_sale_vat_required/i18n/website_sale_vat_required.pot
  website_sale_vat_required/readme/CONTRIBUTORS.rst
  website_sale_vat_required/readme/DESCRIPTION.rst
  website_sale_vat_required/readme/USAGE.rst
  website_sale_vat_required/static/description/icon.png
  website_sale_vat_required/static/description/index.html
  website_sale_vat_required/static/src/js/website_sale_vat_required.tour.js
  website_sale_vat_required/tests/__init__.py
  website_sale_vat_required/tests/test_website_sale_vat_required.py
  website_sale_vat_required/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#872 [14.0] [IMP] update dotfiles
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  website_sale_attribute_filter_price/templates/assets.xml
  website_sale_cart_expire/data/ir_cron.xml
  website_sale_category_breadcrumb/__init__.py
  website_sale_category_breadcrumb/views/templates.xml
  website_sale_checkout_country_vat/views/templates.xml
  website_sale_delivery_group/views/templates.xml
  website_sale_filter_product_brand/views/templates.xml
  website_sale_infinite_scroll/demo/demo_products.xml
  website_sale_product_assortment/views/ir_filters_views.xml
Labels: bot is merging ⏳

#873 [16.0][MIG] website_sale_product_assortment: Migration to version 16.0
  setup/website_sale_product_assortment/odoo/addons/website_sale_product_assortment
  setup/website_sale_product_assortment/setup.py
  website_sale_product_assortment/README.rst
  website_sale_product_assortment/__init__.py
  website_sale_product_assortment/__manifest__.py
  website_sale_product_assortment/controllers/__init__.py
  website_sale_product_assortment/controllers/variant.py
  website_sale_product_assortment/controllers/website_sale.py
  website_sale_product_assortment/i18n/es.po
  website_sale_product_assortment/i18n/it.po
  website_sale_product_assortment/i18n/website_sale_product_assortment.pot
  website_sale_product_assortment/models/__init__.py
  website_sale_product_assortment/models/ir_filters.py
  website_sale_product_assortment/models/product_template.py
  website_sale_product_assortment/readme/CONFIGURE.rst
  website_sale_product_assortment/readme/CONTRIBUTORS.rst
  website_sale_product_assortment/readme/DESCRIPTION.rst
  website_sale_product_assortment/static/description/icon.png
  website_sale_product_assortment/static/description/index.html
  website_sale_product_assortment/static/src/js/assortment_list_preview.js
  website_sale_product_assortment/static/src/js/no_purchase_tour.js
  website_sale_product_assortment/static/src/js/no_restriction_tour.js
  website_sale_product_assortment/static/src/js/no_show_tour.js
  website_sale_product_assortment/static/src/js/variant_mixin.js
  website_sale_product_assortment/static/src/xml/website_sale_product_assortment.xml
  website_sale_product_assortment/templates/website_sale_views.xml
  website_sale_product_assortment/tests/__init__.py
  website_sale_product_assortment/tests/test_ui.py
  website_sale_product_assortment/views/ir_filters_views.xml
Labels: bot is merging ⏳
