Repository OCA/e-commerce, pull requests merged in 2023-03, with the labels that each got.

#764 [13.0][FIX] website_sale_hide_price: hide the price in the add_to_cart option
  website_sale_hide_price/README.rst
  website_sale_hide_price/readme/CONTRIBUTORS.rst
  website_sale_hide_price/readme/ROADMAP.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#766 [15.0][MIG] website_sale_google_tag_manager: Migration to version 15.0
  setup/website_sale_google_tag_manager/odoo/addons/website_sale_google_tag_manager
  setup/website_sale_google_tag_manager/setup.py
  website_sale_google_tag_manager/README.rst
  website_sale_google_tag_manager/__init__.py
  website_sale_google_tag_manager/__manifest__.py
  website_sale_google_tag_manager/i18n/website_sale_google_tag_manager.pot
  website_sale_google_tag_manager/models/__init__.py
  website_sale_google_tag_manager/models/res_config_settings.py
  website_sale_google_tag_manager/models/website.py
  website_sale_google_tag_manager/readme/CONFIGURE.rst
  website_sale_google_tag_manager/readme/CONTRIBUTORS.rst
  website_sale_google_tag_manager/readme/DESCRIPTION.rst
  website_sale_google_tag_manager/static/description/icon.png
  website_sale_google_tag_manager/static/description/index.html
  website_sale_google_tag_manager/static/description/website_google_tag_manager.jpg
  website_sale_google_tag_manager/views/res_config_settings_view.xml
  website_sale_google_tag_manager/views/website_templates.xml
Labels: approved, bot is merging ⏳

#690 [15.0][MIG] website_sale_product_attribute_value_filter_existing: Migration to 15.0
  setup/website_sale_product_attribute_value_filter_existing/odoo/addons/website_sale_product_attribute_value_filter_existing
  setup/website_sale_product_attribute_value_filter_existing/setup.py
  website_sale_product_attribute_value_filter_existing/README.rst
  website_sale_product_attribute_value_filter_existing/__init__.py
  website_sale_product_attribute_value_filter_existing/__manifest__.py
  website_sale_product_attribute_value_filter_existing/controllers/__init__.py
  website_sale_product_attribute_value_filter_existing/controllers/main.py
  website_sale_product_attribute_value_filter_existing/i18n/ca.po
  website_sale_product_attribute_value_filter_existing/i18n/es.po
  website_sale_product_attribute_value_filter_existing/i18n/nl.po
  website_sale_product_attribute_value_filter_existing/i18n/website_sale_product_attribute_value_filter_existing.pot
  website_sale_product_attribute_value_filter_existing/readme/CONTRIBUTORS.rst
  website_sale_product_attribute_value_filter_existing/readme/DESCRIPTION.rst
  website_sale_product_attribute_value_filter_existing/readme/USAGE.rst
  website_sale_product_attribute_value_filter_existing/static/description/icon.png
  website_sale_product_attribute_value_filter_existing/static/description/index.html
  website_sale_product_attribute_value_filter_existing/static/src/js/website_sale_product_attribute_value_filter_existing_tour.js
  website_sale_product_attribute_value_filter_existing/tests/__init__.py
  website_sale_product_attribute_value_filter_existing/tests/test_website_sale_product_attribute_value_filter_existing.py
  website_sale_product_attribute_value_filter_existing/views/templates.xml
Labels: approved, bot is merging ⏳, stale

#770 [15.0][FIX] website_sale_hide_price: hide the price in the add_to_cart option
  website_sale_hide_price/README.rst
  website_sale_hide_price/readme/CONTRIBUTORS.rst
  website_sale_hide_price/readme/ROADMAP.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#767 [14.0][FIX/IMP] website_sale_hide_price: Fordward ports from 13.0 to 14.0
  website_sale_hide_price/README.rst
  website_sale_hide_price/__init__.py
  website_sale_hide_price/__manifest__.py
  website_sale_hide_price/controllers/__init__.py
  website_sale_hide_price/controllers/main.py
  website_sale_hide_price/models/__init__.py
  website_sale_hide_price/models/product_template.py
  website_sale_hide_price/models/res_config_settings.py
  website_sale_hide_price/models/website.py
  website_sale_hide_price/readme/CONFIGURE.rst
  website_sale_hide_price/readme/CONTRIBUTORS.rst
  website_sale_hide_price/readme/DESCRIPTION.rst
  website_sale_hide_price/readme/ROADMAP.rst
  website_sale_hide_price/readme/USAGE.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/static/src/js/website_sale_hide_price.js
  website_sale_hide_price/static/src/xml/website_sale_templates.xml
  website_sale_hide_price/views/assets.xml
  website_sale_hide_price/views/product_template_views.xml
  website_sale_hide_price/views/res_config_settings_views.xml
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#772 [15.0][FIX] website_sale_hide_price, hide price on results of search bar
  website_sale_hide_price/models/product_template.py
Labels: approved, bot is merging ⏳

#763 [15.0][MIG] website_sale_product_minimal_price: Migration to version 15.0
  setup/website_sale_product_minimal_price/odoo/addons/website_sale_product_minimal_price
  setup/website_sale_product_minimal_price/setup.py
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/controllers/__init__.py
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/i18n/ca.po
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/nl.po
  website_sale_product_minimal_price/i18n/pt.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/__init__.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONFIGURE.rst
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/readme/DESCRIPTION.rst
  website_sale_product_minimal_price/readme/USAGE.rst
  website_sale_product_minimal_price/static/description/icon.png
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/test_product_with_no_prices_tour.js
  website_sale_product_minimal_price/static/src/js/tour.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_price_scale.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_minimal_price.xml
  website_sale_product_minimal_price/static/src/xml/website_sale_product_price_scale.xml
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_product_with_no_prices.py
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#775 [15.0][MIG] website_sale_stock_list_preview: Migration to 15.0
  setup/website_sale_stock_list_preview/odoo/addons/website_sale_stock_list_preview
  setup/website_sale_stock_list_preview/setup.py
  website_sale_stock_list_preview/README.rst
  website_sale_stock_list_preview/__init__.py
  website_sale_stock_list_preview/__manifest__.py
  website_sale_stock_list_preview/controllers/__init__.py
  website_sale_stock_list_preview/controllers/main.py
  website_sale_stock_list_preview/i18n/es.po
  website_sale_stock_list_preview/i18n/website_sale_stock_list_preview.pot
  website_sale_stock_list_preview/readme/CONTRIBUTORS.rst
  website_sale_stock_list_preview/readme/DESCRIPTION.rst
  website_sale_stock_list_preview/readme/USAGE.rst
  website_sale_stock_list_preview/static/description/icon.png
  website_sale_stock_list_preview/static/description/index.html
  website_sale_stock_list_preview/static/src/js/website_sale_stock_list_preview.js
  website_sale_stock_list_preview/static/src/scss/website_sale_stock_list_preview.scss
  website_sale_stock_list_preview/static/src/tests/tour.js
  website_sale_stock_list_preview/tests/__init__.py
  website_sale_stock_list_preview/tests/test_ui.py
  website_sale_stock_list_preview/views/templates.xml
Labels: approved, bot is merging ⏳
