Repository OCA/e-commerce, pull requests merged in 2023-09, with the labels that each got.

#837 [16.0][MIG] website_sale_invoice_address module
  setup/website_sale_invoice_address/odoo/addons/website_sale_invoice_address
  setup/website_sale_invoice_address/setup.py
  website_sale_invoice_address/README.rst
  website_sale_invoice_address/__init__.py
  website_sale_invoice_address/__manifest__.py
  website_sale_invoice_address/i18n/ca.po
  website_sale_invoice_address/i18n/es.po
  website_sale_invoice_address/i18n/website_sale_invoice_address.pot
  website_sale_invoice_address/models/__init__.py
  website_sale_invoice_address/models/sale_order.py
  website_sale_invoice_address/models/website.py
  website_sale_invoice_address/readme/CONTRIBUTORS.rst
  website_sale_invoice_address/readme/DESCRIPTION.rst
  website_sale_invoice_address/readme/USAGE.rst
  website_sale_invoice_address/static/description/icon.png
  website_sale_invoice_address/static/description/index.html
  website_sale_invoice_address/static/src/js/website_sale_invoice_address_tour.js
  website_sale_invoice_address/tests/__init__.py
  website_sale_invoice_address/tests/test_website_sale_invoice_address.py
Labels: approved, bot is merging ⏳

#829 [16.0][MIG] website_sale_product_attachment: Migration to version 16.0
  setup/website_sale_product_attachment/odoo/addons/website_sale_product_attachment
  setup/website_sale_product_attachment/setup.py
  website_sale_product_attachment/README.rst
  website_sale_product_attachment/__init__.py
  website_sale_product_attachment/__manifest__.py
  website_sale_product_attachment/i18n/ca.po
  website_sale_product_attachment/i18n/es.po
  website_sale_product_attachment/i18n/fr.po
  website_sale_product_attachment/i18n/nl.po
  website_sale_product_attachment/i18n/website_sale_product_attachment.pot
  website_sale_product_attachment/models/__init__.py
  website_sale_product_attachment/models/ir_attachment.py
  website_sale_product_attachment/models/product_template.py
  website_sale_product_attachment/readme/CONFIGURE.rst
  website_sale_product_attachment/readme/CONTRIBUTORS.rst
  website_sale_product_attachment/readme/DESCRIPTION.rst
  website_sale_product_attachment/readme/ROADMAP.rst
  website_sale_product_attachment/readme/USAGE.rst
  website_sale_product_attachment/static/description/backend-attachment.png
  website_sale_product_attachment/static/description/backend-product.png
  website_sale_product_attachment/static/description/frontend-download.gif
  website_sale_product_attachment/static/description/frontend-icons.png
  website_sale_product_attachment/static/description/icon.png
  website_sale_product_attachment/static/description/index.html
  website_sale_product_attachment/static/tests/tours/website_tour.js
  website_sale_product_attachment/templates/product_template.xml
  website_sale_product_attachment/tests/__init__.py
  website_sale_product_attachment/tests/test_tour.py
  website_sale_product_attachment/views/ir_attachment.xml
  website_sale_product_attachment/views/product_template.xml
Labels: approved, bot is merging ⏳

#784 [14.0][ADD] website_sale_infinite_scroll: new module
  setup/website_sale_infinite_scroll/odoo/addons/website_sale_infinite_scroll
  setup/website_sale_infinite_scroll/setup.py
  website_sale_infinite_scroll/README.rst
  website_sale_infinite_scroll/__init__.py
  website_sale_infinite_scroll/__manifest__.py
  website_sale_infinite_scroll/controllers/__init__.py
  website_sale_infinite_scroll/controllers/main.py
  website_sale_infinite_scroll/demo/demo_products.xml
  website_sale_infinite_scroll/models/__init__.py
  website_sale_infinite_scroll/models/res_config_settings.py
  website_sale_infinite_scroll/models/website.py
  website_sale_infinite_scroll/readme/CONFIGURE.rst
  website_sale_infinite_scroll/readme/CONTRIBUTORS.rst
  website_sale_infinite_scroll/readme/DESCRIPTION.rst
  website_sale_infinite_scroll/readme/USAGE.rst
  website_sale_infinite_scroll/static/description/icon.png
  website_sale_infinite_scroll/static/src/js/bus_longpolling.js
  website_sale_infinite_scroll/static/src/js/main.js
  website_sale_infinite_scroll/static/src/js/toors/toor.js
  website_sale_infinite_scroll/static/src/scss/main.scss
  website_sale_infinite_scroll/tests/__init__.py
  website_sale_infinite_scroll/tests/test_website_sale_infinite_scroll.py
  website_sale_infinite_scroll/views/assets.xml
  website_sale_infinite_scroll/views/res_config_settings.xml
  website_sale_infinite_scroll/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#844 [15.0][FIX]website_sale_invoice_address: One of the elements in the tour test cannot be found using the current repository
  website_sale_invoice_address/static/src/js/website_sale_invoice_address_tour.js
Labels: approved, bot is merging ⏳

#830 [15.0][MIG+IMP] website_account_fiscal_position_partner_type
  setup/website_account_fiscal_position_partner_type/odoo/addons/website_account_fiscal_position_partner_type
  setup/website_account_fiscal_position_partner_type/setup.py
  website_account_fiscal_position_partner_type/README.rst
  website_account_fiscal_position_partner_type/__init__.py
  website_account_fiscal_position_partner_type/__manifest__.py
  website_account_fiscal_position_partner_type/controllers/__init__.py
  website_account_fiscal_position_partner_type/controllers/main.py
  website_account_fiscal_position_partner_type/controllers/portal.py
  website_account_fiscal_position_partner_type/i18n/es.po
  website_account_fiscal_position_partner_type/i18n/website_account_fiscal_position_partner_type.pot
  website_account_fiscal_position_partner_type/models/__init__.py
  website_account_fiscal_position_partner_type/models/res_partner.py
  website_account_fiscal_position_partner_type/models/res_users.py
  website_account_fiscal_position_partner_type/readme/CONTRIBUTORS.rst
  website_account_fiscal_position_partner_type/readme/DESCRIPTION.rst
  website_account_fiscal_position_partner_type/readme/USAGE.rst
  website_account_fiscal_position_partner_type/static/description/icon.png
  website_account_fiscal_position_partner_type/static/description/index.html
  website_account_fiscal_position_partner_type/views/auth_signup_login_templates.xml
  website_account_fiscal_position_partner_type/views/portal_templates.xml
  website_account_fiscal_position_partner_type/views/website_sale.xml
Labels: approved, bot is merging ⏳

#845 [15.0][IMP] website_sale_secondary_unit: Hide/show uom name in secondary quantity description and delete column in cart summary
  website_sale_secondary_unit/README.rst
  website_sale_secondary_unit/readme/CONTRIBUTORS.rst
  website_sale_secondary_unit/static/description/index.html
  website_sale_secondary_unit/static/src/js/website_sale_secondary_unit_tour.js
  website_sale_secondary_unit/views/templates.xml
Labels: approved, bot is merging ⏳

#846 [16.0][MIG] website_sale_stock_provisioning_date: Migration to version 16.0
  setup/website_sale_stock_provisioning_date/odoo/addons/website_sale_stock_provisioning_date
  setup/website_sale_stock_provisioning_date/setup.py
  website_sale_stock_provisioning_date/README.rst
  website_sale_stock_provisioning_date/__init__.py
  website_sale_stock_provisioning_date/__manifest__.py
  website_sale_stock_provisioning_date/i18n/es.po
  website_sale_stock_provisioning_date/i18n/website_sale_stock_provisioning_date.pot
  website_sale_stock_provisioning_date/models/__init__.py
  website_sale_stock_provisioning_date/models/product_product.py
  website_sale_stock_provisioning_date/models/product_template.py
  website_sale_stock_provisioning_date/readme/CONTRIBUTORS.rst
  website_sale_stock_provisioning_date/readme/DESCRIPTION.rst
  website_sale_stock_provisioning_date/readme/USAGE.rst
  website_sale_stock_provisioning_date/static/description/icon.png
  website_sale_stock_provisioning_date/static/description/index.html
  website_sale_stock_provisioning_date/static/src/js/website_sale_stock_provisioning_date_tour.js
  website_sale_stock_provisioning_date/static/src/xml/website_sale_stock_product_availability.xml
  website_sale_stock_provisioning_date/tests/__init__.py
  website_sale_stock_provisioning_date/tests/test_website_sale_stock_provisioning_date.py
  website_sale_stock_provisioning_date/views/product_template_views.xml
Labels: approved, bot is merging ⏳

#827 [16.0][ADD] New module website sale product image sample
  setup/website_sale_product_image_sample/odoo/addons/website_sale_product_image_sample
  setup/website_sale_product_image_sample/setup.py
  website_sale_product_image_sample/README.rst
  website_sale_product_image_sample/__init__.py
  website_sale_product_image_sample/__manifest__.py
  website_sale_product_image_sample/models/__init__.py
  website_sale_product_image_sample/models/product_attribute.py
  website_sale_product_image_sample/models/product_template.py
  website_sale_product_image_sample/readme/CONTRIBUTORS.rst
  website_sale_product_image_sample/readme/DESCRIPTION.rst
  website_sale_product_image_sample/readme/ROADMAP.rst
  website_sale_product_image_sample/readme/USAGE.rst
  website_sale_product_image_sample/static/description/icon.png
  website_sale_product_image_sample/static/description/index.html
  website_sale_product_image_sample/static/img/image.gif
  website_sale_product_image_sample/static/src/css/product_configurator.scss
  website_sale_product_image_sample/views/variants.xml
Labels: approved, bot is merging ⏳

#843 [16.0][FIX] website_sale_checkout_skip_payment: Fix test by adding the vat
  website_sale_checkout_skip_payment/tests/test_checkout_skip_payment.py
Labels: approved, bot is merging ⏳

#805 [15.0][FIX] website_sale_product_item_cart_custom_qty
  website_sale_product_item_cart_custom_qty/static/src/scss/add_to_cart.scss
  website_sale_product_item_cart_custom_qty/views/templates.xml
Labels: bot is merging ⏳, stale

#848 [16.0][FIX] website_sale_product_item_cart_custom_qty
  website_sale_product_item_cart_custom_qty/static/src/scss/add_to_cart.scss
  website_sale_product_item_cart_custom_qty/views/templates.xml
Labels: approved, bot is merging ⏳
