Repository OCA/e-commerce, pull requests merged in 2024-03, with the labels that each got.

#857 [16.0] [MIG] website_sale_product_minimal_price
  setup/website_sale_product_minimal_price/odoo/addons/website_sale_product_minimal_price
  setup/website_sale_product_minimal_price/setup.py
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/controllers/__init__.py
  website_sale_product_minimal_price/controllers/main.py
  website_sale_product_minimal_price/i18n/ca.po
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/fr.po
  website_sale_product_minimal_price/i18n/nl.po
  website_sale_product_minimal_price/i18n/pt.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/__init__.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/readme/CONFIGURE.rst
  website_sale_product_minimal_price/readme/CONTRIBUTORS.rst
  website_sale_product_minimal_price/readme/DESCRIPTION.rst
  website_sale_product_minimal_price/readme/USAGE.rst
  website_sale_product_minimal_price/static/description/icon.png
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/tours/test_product_with_no_prices_tour.js
  website_sale_product_minimal_price/static/src/js/tours/tour.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_minimal_price.js
  website_sale_product_minimal_price/static/src/js/website_sale_product_price_scale.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_minimal_price.xml
  website_sale_product_minimal_price/static/src/xml/website_sale_product_price_scale.xml
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_product_with_no_prices.py
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#907 [16.0][FIX] website_sale_stock_available: respect args
  website_sale_stock_available/models/sale_order.py
Labels: approved, bot is merging ⏳

#875 [15.0][IMP] website_sale_product_attribute_value_filter_existing: performance
  website_sale_product_attribute_value_filter_existing/controllers/main.py
Labels: approved, bot is merging ⏳, stale

#899 [FIX] website_sale_suggest_create_account: changing the priority of a view
  website_sale_suggest_create_account/views/website_sale.xml
Labels: approved, bot is merging ⏳

#909 [14.0][IMP] website_sale_infinite_scroll: add back to top button
  website_sale_infinite_scroll/static/src/js/main.js
  website_sale_infinite_scroll/static/src/js/widget_back_to_top.js
  website_sale_infinite_scroll/static/src/scss/main.scss
  website_sale_infinite_scroll/views/assets.xml
  website_sale_infinite_scroll/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳
