Repository OCA/e-commerce, pull requests merged in 2024-07, with the labels that each got.

#902 [16.0][FIX] website_sale_stock_available: depends_context
  website_sale_stock_available/models/product_product.py
Labels: bot is merging ⏳, stale

#944 [16.0][FIX] website_sale_product_attachment: product template view ad…
  website_sale_product_attachment/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#943 [16.0][DOC] website_sale_hide_price: message
  website_sale_hide_price/README.rst
  website_sale_hide_price/models/product_template.py
  website_sale_hide_price/models/website.py
  website_sale_hide_price/readme/CONFIGURE.rst
  website_sale_hide_price/static/description/index.html
  website_sale_hide_price/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#951 [16.0][FIX] website_sale_hide_price: change of priority in product view
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#953 [16.0][MIG] website_sale_category_breadcrumb: Migration to version 16.0
  setup/website_sale_category_breadcrumb/odoo/addons/website_sale_category_breadcrumb
  setup/website_sale_category_breadcrumb/setup.py
  website_sale_category_breadcrumb/README.rst
  website_sale_category_breadcrumb/__init__.py
  website_sale_category_breadcrumb/__manifest__.py
  website_sale_category_breadcrumb/i18n/es.po
  website_sale_category_breadcrumb/i18n/it.po
  website_sale_category_breadcrumb/i18n/website_sale_category_breadcrumb.pot
  website_sale_category_breadcrumb/readme/CONTRIBUTORS.rst
  website_sale_category_breadcrumb/readme/DESCRIPTION.rst
  website_sale_category_breadcrumb/readme/USAGE.rst
  website_sale_category_breadcrumb/static/description/icon.png
  website_sale_category_breadcrumb/static/description/index.html
  website_sale_category_breadcrumb/views/templates.xml
Labels: approved, bot is merging ⏳

#954 [17.0][MIG] website_sale_suggest_create_account
  website_sale_suggest_create_account/README.rst
  website_sale_suggest_create_account/__init__.py
  website_sale_suggest_create_account/__manifest__.py
  website_sale_suggest_create_account/hooks.py
  website_sale_suggest_create_account/i18n/ca.po
  website_sale_suggest_create_account/i18n/ca_ES.po
  website_sale_suggest_create_account/i18n/de.po
  website_sale_suggest_create_account/i18n/es.po
  website_sale_suggest_create_account/i18n/es_CO.po
  website_sale_suggest_create_account/i18n/fr.po
  website_sale_suggest_create_account/i18n/hr.po
  website_sale_suggest_create_account/i18n/it.po
  website_sale_suggest_create_account/i18n/nl.po
  website_sale_suggest_create_account/i18n/sl.po
  website_sale_suggest_create_account/i18n/website_sale_suggest_create_account.pot
  website_sale_suggest_create_account/migrations/17.0.1.0.0/pre-migration.py
  website_sale_suggest_create_account/pyproject.toml
  website_sale_suggest_create_account/readme/CONTRIBUTORS.md
  website_sale_suggest_create_account/readme/DESCRIPTION.md
  website_sale_suggest_create_account/readme/USAGE.md
  website_sale_suggest_create_account/static/description/icon.png
  website_sale_suggest_create_account/static/description/index.html
  website_sale_suggest_create_account/static/tests/tours/checkout.js
  website_sale_suggest_create_account/tests/__init__.py
  website_sale_suggest_create_account/tests/test_shop_buy.py
  website_sale_suggest_create_account/views/website_sale.xml
Labels: approved, ready to merge, bot is merging ⏳

#959 [16.0][FIX] website_sale_checkout_skip_payment: Fix wrong confirmation method.
  website_sale_checkout_skip_payment/controllers/main.py
  website_sale_checkout_skip_payment/static/tests/tours/website_sale_checkout_skip_payment_tour.js
Labels: approved, bot is merging ⏳
