Repository OCA/e-commerce, pull requests merged in 2024-08, with the labels that each got.

#960 [17.0][MIG] website_sale_b2x_alt_price: Migration to 17.0
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/i18n/ca.po
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/fr.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/pyproject.toml
  website_sale_b2x_alt_price/readme/CONFIGURE.md
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.md
  website_sale_b2x_alt_price/readme/DESCRIPTION.md
  website_sale_b2x_alt_price/readme/ROADMAP.md
  website_sale_b2x_alt_price/readme/USAGE.md
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.esm.js
  website_sale_b2x_alt_price/static/tests/tours/b2b.esm.js
  website_sale_b2x_alt_price/static/tests/tours/b2c.esm.js
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
  website_sale_suggest_create_account/__manifest__.py
  website_sale_suggest_create_account/static/tests/tours/checkout.esm.js
  website_sale_suggest_create_account/static/tests/tours/checkout.js
Labels: approved, bot is merging ⏳

#963 [IMP] website_sale_product_assortment: bullet list
  website_sale_product_assortment/readme/CONFIGURE.rst
Labels: approved, bot is merging ⏳

#952 [16.0][MIG] website_sale_tax_toggle: Migration to version 16.0
  setup/website_sale_tax_toggle/odoo/addons/website_sale_tax_toggle
  setup/website_sale_tax_toggle/setup.py
  website_sale_tax_toggle/README.rst
  website_sale_tax_toggle/__init__.py
  website_sale_tax_toggle/__manifest__.py
  website_sale_tax_toggle/controllers/__init__.py
  website_sale_tax_toggle/controllers/main.py
  website_sale_tax_toggle/i18n/ca.po
  website_sale_tax_toggle/i18n/es.po
  website_sale_tax_toggle/i18n/fr.po
  website_sale_tax_toggle/i18n/nl.po
  website_sale_tax_toggle/i18n/website_sale_tax_toggle.pot
  website_sale_tax_toggle/models/__init__.py
  website_sale_tax_toggle/models/res_users.py
  website_sale_tax_toggle/readme/CONTRIBUTORS.rst
  website_sale_tax_toggle/readme/DESCRIPTION.rst
  website_sale_tax_toggle/readme/USAGE.rst
  website_sale_tax_toggle/static/description/icon.png
  website_sale_tax_toggle/static/description/index.html
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle.esm.js
  website_sale_tax_toggle/static/src/js/website_sale_tax_toggle_tour.esm.js
  website_sale_tax_toggle/static/src/scss/website_sale_tax_toggle.scss
  website_sale_tax_toggle/tests/__init__.py
  website_sale_tax_toggle/tests/test_website_sale_tax_toggle.py
  website_sale_tax_toggle/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#957 [17.0][MIG] website_sale_product_description
  website_sale_product_description/README.rst
  website_sale_product_description/__init__.py
  website_sale_product_description/__manifest__.py
  website_sale_product_description/data/demo_website_sale_product_description.xml
  website_sale_product_description/i18n/ca.po
  website_sale_product_description/i18n/es.po
  website_sale_product_description/i18n/es_AR.po
  website_sale_product_description/i18n/es_ES.po
  website_sale_product_description/i18n/it.po
  website_sale_product_description/i18n/nl.po
  website_sale_product_description/i18n/pt.po
  website_sale_product_description/i18n/website_sale_product_description.pot
  website_sale_product_description/models/__init__.py
  website_sale_product_description/models/product.py
  website_sale_product_description/pyproject.toml
  website_sale_product_description/readme/CONTRIBUTORS.md
  website_sale_product_description/readme/DESCRIPTION.md
  website_sale_product_description/readme/USAGE.md
  website_sale_product_description/static/description/icon.png
  website_sale_product_description/static/description/index.html
  website_sale_product_description/static/description/product.png
  website_sale_product_description/static/description/website-product.png
  website_sale_product_description/views/product_template.xml
  website_sale_product_description/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#964 [16.0][FIX] website_sale_checkout_skip_payment: translate payment message
  website_sale_checkout_skip_payment/i18n/es.po
  website_sale_checkout_skip_payment/i18n/website_sale_checkout_skip_payment.pot
  website_sale_checkout_skip_payment/models/website.py
Labels: bot is merging ⏳

#965 [15.0][FIX] website_sale_checkout_skip_payment: translate payment message
  website_sale_checkout_skip_payment/i18n/es.po
  website_sale_checkout_skip_payment/i18n/website_sale_checkout_skip_payment.pot
  website_sale_checkout_skip_payment/models/website.py
Labels: bot is merging ⏳
