Repository OCA/e-commerce, pull requests merged in 2024-02, with the labels that each got.

#898 [MIG] website_sale_charge_payment_fee: Migration to 14.0
  setup/website_sale_charge_payment_fee/odoo/addons/website_sale_charge_payment_fee
  setup/website_sale_charge_payment_fee/setup.py
  website_sale_charge_payment_fee/README.rst
  website_sale_charge_payment_fee/__init__.py
  website_sale_charge_payment_fee/__manifest__.py
  website_sale_charge_payment_fee/controllers/__init__.py
  website_sale_charge_payment_fee/controllers/main.py
  website_sale_charge_payment_fee/i18n/es.po
  website_sale_charge_payment_fee/i18n/es_AR.po
  website_sale_charge_payment_fee/i18n/website_sale_charge_payment_fee.pot
  website_sale_charge_payment_fee/models/__init__.py
  website_sale_charge_payment_fee/models/payment_acquirer.py
  website_sale_charge_payment_fee/models/sale_order.py
  website_sale_charge_payment_fee/models/sale_order_line.py
  website_sale_charge_payment_fee/readme/CONFIGURE.rst
  website_sale_charge_payment_fee/readme/CONTRIBUTORS.rst
  website_sale_charge_payment_fee/readme/DESCRIPTION.rst
  website_sale_charge_payment_fee/static/description/icon.png
  website_sale_charge_payment_fee/static/description/index.html
  website_sale_charge_payment_fee/static/src/js/website_sale_fee.js
  website_sale_charge_payment_fee/static/tests/tours/website_sale_fee_tour.js
  website_sale_charge_payment_fee/tests/__init__.py
  website_sale_charge_payment_fee/tests/test_website_sale_fee.py
  website_sale_charge_payment_fee/views/payment_acquirer_views.xml
  website_sale_charge_payment_fee/views/website_sale_templates.xml
Labels: bot is merging ⏳

#896 [ADD] website_sale_product_name_fixed_height: add module
  setup/website_sale_product_name_fixed_height/odoo/addons/website_sale_product_name_fixed_height
  setup/website_sale_product_name_fixed_height/setup.py
  website_sale_product_name_fixed_height/README.rst
  website_sale_product_name_fixed_height/__init__.py
  website_sale_product_name_fixed_height/__manifest__.py
  website_sale_product_name_fixed_height/models/__init__.py
  website_sale_product_name_fixed_height/models/res_config_settings.py
  website_sale_product_name_fixed_height/models/website.py
  website_sale_product_name_fixed_height/readme/CONFIGURE.rst
  website_sale_product_name_fixed_height/readme/CONTEXT.rst
  website_sale_product_name_fixed_height/readme/CONTRIBUTORS.rst
  website_sale_product_name_fixed_height/readme/DESCRIPTION.rst
  website_sale_product_name_fixed_height/static/description/icon.png
  website_sale_product_name_fixed_height/static/description/index.html
  website_sale_product_name_fixed_height/tests/__init__.py
  website_sale_product_name_fixed_height/tests/test_website_sale_fixed_name_height.py
  website_sale_product_name_fixed_height/views/res_config_settings_view.xml
  website_sale_product_name_fixed_height/views/website_sale_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#858 [14.0][IMP] Query performance for shop route in website_sale_filter_p…
  website_sale_filter_product_brand/controllers/website_sale.py
Labels: approved, ready to merge, bot is merging ⏳, stale
