Repository OCA/e-commerce, pull requests merged in 2025-07, with the labels that each got.

#1032 [15.0][ADD] website_sale_stock_product_matrix: new module
  setup/website_sale_stock_product_matrix/odoo/addons/website_sale_stock_product_matrix
  setup/website_sale_stock_product_matrix/setup.py
  website_sale_stock_product_matrix/README.rst
  website_sale_stock_product_matrix/__init__.py
  website_sale_stock_product_matrix/__manifest__.py
  website_sale_stock_product_matrix/i18n/es.po
  website_sale_stock_product_matrix/i18n/website_sale_stock_product_matrix.pot
  website_sale_stock_product_matrix/readme/CONTRIBUTORS.md
  website_sale_stock_product_matrix/readme/DESCRIPTION.md
  website_sale_stock_product_matrix/readme/USAGE.md
  website_sale_stock_product_matrix/static/description/index.html
  website_sale_stock_product_matrix/templates/product_template.xml
Labels: approved, bot is merging ⏳

#1031 [15.0][ADD] website_sale_secondary_unit_product_matrix: New module
  setup/website_sale_secondary_unit_product_matrix/odoo/addons/website_sale_secondary_unit_product_matrix
  setup/website_sale_secondary_unit_product_matrix/setup.py
  website_sale_secondary_unit_product_matrix/README.rst
  website_sale_secondary_unit_product_matrix/__init__.py
  website_sale_secondary_unit_product_matrix/__manifest__.py
  website_sale_secondary_unit_product_matrix/i18n/es.po
  website_sale_secondary_unit_product_matrix/i18n/website_sale_secondary_unit_product_matrix.pot
  website_sale_secondary_unit_product_matrix/readme/CONFIGURE.md
  website_sale_secondary_unit_product_matrix/readme/CONTRIBUTORS.md
  website_sale_secondary_unit_product_matrix/readme/DESCRIPTION.md
  website_sale_secondary_unit_product_matrix/readme/USAGE.md
  website_sale_secondary_unit_product_matrix/static/description/index.html
  website_sale_secondary_unit_product_matrix/static/src/js/website_sale.esm.js
  website_sale_secondary_unit_product_matrix/templates/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#1083 [17.0][FIX] website_sale_hide_price: Hide price in product carousel
  website_sale_hide_price/data/product_snippet_template_data.xml
Labels: approved, bot is merging ⏳

#1087 [17.0][FIX] website_sale_hide_price: Don't make snippets noupdate
  website_sale_hide_price/__manifest__.py
  website_sale_hide_price/data/product_snippet_template_data.xml
  website_sale_hide_price/migrations/17.0.1.2.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1079 [17.0][MIG] website_sale_product_matrix: Migration to version 17.0
  website_sale_hide_price/views/website_sale_template.xml
  website_sale_product_matrix/README.rst
  website_sale_product_matrix/__init__.py
  website_sale_product_matrix/__manifest__.py
  website_sale_product_matrix/controllers/__init__.py
  website_sale_product_matrix/controllers/main.py
  website_sale_product_matrix/i18n/ca.po
  website_sale_product_matrix/i18n/es.po
  website_sale_product_matrix/i18n/website_sale_product_matrix.pot
  website_sale_product_matrix/pyproject.toml
  website_sale_product_matrix/readme/CONFIGURE.md
  website_sale_product_matrix/readme/CONTRIBUTORS.md
  website_sale_product_matrix/readme/DESCRIPTION.md
  website_sale_product_matrix/readme/USAGE.md
  website_sale_product_matrix/static/description/icon.png
  website_sale_product_matrix/static/description/index.html
  website_sale_product_matrix/static/src/js/website_sale.esm.js
  website_sale_product_matrix/static/src/scss/matrix_style.scss
  website_sale_product_matrix/templates/product_template.xml
Labels: approved, bot is merging ⏳

#1089 [17.0][FIX] website_sale_hide_price: repair regression as part of #1079
  website_sale_hide_price/views/website_sale_template.xml
Labels: bot is merging ⏳
