Repository OCA/e-commerce, pull requests merged in 2025-02, with the labels that each got.

#1012 [17.0][MIG] website_sale_product_detail_attribute_image: Migration to version 17.0
  website_sale_product_detail_attribute_image/README.rst
  website_sale_product_detail_attribute_image/__init__.py
  website_sale_product_detail_attribute_image/__manifest__.py
  website_sale_product_detail_attribute_image/controllers/__init__.py
  website_sale_product_detail_attribute_image/controllers/main.py
  website_sale_product_detail_attribute_image/i18n/es.po
  website_sale_product_detail_attribute_image/i18n/es_AR.po
  website_sale_product_detail_attribute_image/i18n/it.po
  website_sale_product_detail_attribute_image/i18n/nl.po
  website_sale_product_detail_attribute_image/i18n/pt.po
  website_sale_product_detail_attribute_image/i18n/website_sale_product_detail_attribute_image.pot
  website_sale_product_detail_attribute_image/models/__init__.py
  website_sale_product_detail_attribute_image/models/product_attribute.py
  website_sale_product_detail_attribute_image/pyproject.toml
  website_sale_product_detail_attribute_image/readme/CONTRIBUTORS.md
  website_sale_product_detail_attribute_image/readme/CREDITS.md
  website_sale_product_detail_attribute_image/readme/DESCRIPTION.md
  website_sale_product_detail_attribute_image/readme/USAGE.md
  website_sale_product_detail_attribute_image/static/description/icon.png
  website_sale_product_detail_attribute_image/static/description/index.html
  website_sale_product_detail_attribute_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_image/static/tests/tours/website_sale_product_detail_attribute_image.esm.js
  website_sale_product_detail_attribute_image/tests/__init__.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_product_detail_attribute_image/views/product_attribute_views.xml
  website_sale_product_detail_attribute_image/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1010 [17.0][MIG] website_sale_hide_empty_category: Migration to version 17.0
  website_sale_hide_empty_category/README.rst
  website_sale_hide_empty_category/__init__.py
  website_sale_hide_empty_category/__manifest__.py
  website_sale_hide_empty_category/i18n/ca.po
  website_sale_hide_empty_category/i18n/es.po
  website_sale_hide_empty_category/i18n/nl.po
  website_sale_hide_empty_category/i18n/website_sale_hide_empty_category.pot
  website_sale_hide_empty_category/models/__init__.py
  website_sale_hide_empty_category/models/product_public_category.py
  website_sale_hide_empty_category/pyproject.toml
  website_sale_hide_empty_category/readme/CONFIGURE.md
  website_sale_hide_empty_category/readme/CONTRIBUTORS.md
  website_sale_hide_empty_category/readme/DESCRIPTION.md
  website_sale_hide_empty_category/readme/USAGE.md
  website_sale_hide_empty_category/static/description/icon.png
  website_sale_hide_empty_category/static/description/index.html
  website_sale_hide_empty_category/static/src/js/tour.esm.js
  website_sale_hide_empty_category/tests/__init__.py
  website_sale_hide_empty_category/tests/test_has_product_recursive.py
  website_sale_hide_empty_category/tests/test_ui.py
  website_sale_hide_empty_category/views/website_sale_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1015 [18.0][MIG] website_sale_b2x_alt_price: Migration to version 18.0
  website_sale_b2x_alt_price/README.rst
  website_sale_b2x_alt_price/__init__.py
  website_sale_b2x_alt_price/__manifest__.py
  website_sale_b2x_alt_price/i18n/ca.po
  website_sale_b2x_alt_price/i18n/es.po
  website_sale_b2x_alt_price/i18n/fr.po
  website_sale_b2x_alt_price/i18n/it.po
  website_sale_b2x_alt_price/i18n/website_sale_b2x_alt_price.pot
  website_sale_b2x_alt_price/models/__init__.py
  website_sale_b2x_alt_price/models/product_template.py
  website_sale_b2x_alt_price/pyproject.toml
  website_sale_b2x_alt_price/readme/CONFIGURE.md
  website_sale_b2x_alt_price/readme/CONTRIBUTORS.md
  website_sale_b2x_alt_price/readme/DESCRIPTION.md
  website_sale_b2x_alt_price/readme/ROADMAP.md
  website_sale_b2x_alt_price/readme/USAGE.md
  website_sale_b2x_alt_price/static/description/b2b-features.png
  website_sale_b2x_alt_price/static/description/b2c-features.png
  website_sale_b2x_alt_price/static/description/details-features.gif
  website_sale_b2x_alt_price/static/description/icon.png
  website_sale_b2x_alt_price/static/description/index.html
  website_sale_b2x_alt_price/static/description/toggle-detail.gif
  website_sale_b2x_alt_price/static/description/toggle-list.gif
  website_sale_b2x_alt_price/static/src/js/product_configurator_mixin.esm.js
  website_sale_b2x_alt_price/static/tests/tours/b2b.esm.js
  website_sale_b2x_alt_price/static/tests/tours/b2c.esm.js
  website_sale_b2x_alt_price/templates/product.xml
  website_sale_b2x_alt_price/tests/__init__.py
  website_sale_b2x_alt_price/tests/test_ui.py
Labels: approved, ready to merge, bot is merging ⏳

#1018 [18.0][MIG] website_sale_product_detail_attribute_image: Migration to version 18.0
  website_sale_product_detail_attribute_image/README.rst
  website_sale_product_detail_attribute_image/__init__.py
  website_sale_product_detail_attribute_image/__manifest__.py
  website_sale_product_detail_attribute_image/controllers/__init__.py
  website_sale_product_detail_attribute_image/controllers/main.py
  website_sale_product_detail_attribute_image/i18n/es.po
  website_sale_product_detail_attribute_image/i18n/es_AR.po
  website_sale_product_detail_attribute_image/i18n/it.po
  website_sale_product_detail_attribute_image/i18n/nl.po
  website_sale_product_detail_attribute_image/i18n/pt.po
  website_sale_product_detail_attribute_image/i18n/website_sale_product_detail_attribute_image.pot
  website_sale_product_detail_attribute_image/models/__init__.py
  website_sale_product_detail_attribute_image/models/product_attribute.py
  website_sale_product_detail_attribute_image/pyproject.toml
  website_sale_product_detail_attribute_image/readme/CONTRIBUTORS.md
  website_sale_product_detail_attribute_image/readme/CREDITS.md
  website_sale_product_detail_attribute_image/readme/DESCRIPTION.md
  website_sale_product_detail_attribute_image/readme/USAGE.md
  website_sale_product_detail_attribute_image/static/description/icon.png
  website_sale_product_detail_attribute_image/static/description/index.html
  website_sale_product_detail_attribute_image/static/src/img/EN374.png
  website_sale_product_detail_attribute_image/static/src/img/EN374_2003.png
  website_sale_product_detail_attribute_image/static/src/img/EN388.png
  website_sale_product_detail_attribute_image/static/src/scss/style.scss
  website_sale_product_detail_attribute_image/static/tests/tours/website_sale_product_detail_attribute_image.esm.js
  website_sale_product_detail_attribute_image/tests/__init__.py
  website_sale_product_detail_attribute_image/tests/test_website_sale_product_detail_attribute_image.py
  website_sale_product_detail_attribute_image/views/product_attribute_views.xml
  website_sale_product_detail_attribute_image/views/templates.xml
Labels: approved, bot is merging ⏳

#1009 [17.0][MIG] website_sale_order_type: Migration to version 17.0
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/i18n/ca.po
  website_sale_order_type/i18n/es.po
  website_sale_order_type/i18n/it.po
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/website.py
  website_sale_order_type/pyproject.toml
  website_sale_order_type/readme/CONTRIBUTORS.md
  website_sale_order_type/readme/DESCRIPTION.md
  website_sale_order_type/readme/USAGE.md
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/tests/tours/website_sale_order_type_tour.esm.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, ready to merge, bot is merging ⏳

#765 [15.0][ADD] website_sale_product_publish_date
  setup/website_sale_product_publish_date/odoo/addons/website_sale_product_publish_date
  setup/website_sale_product_publish_date/setup.py
  website_sale_product_publish_date/README.rst
  website_sale_product_publish_date/__init__.py
  website_sale_product_publish_date/__manifest__.py
  website_sale_product_publish_date/models/__init__.py
  website_sale_product_publish_date/models/product_template.py
  website_sale_product_publish_date/readme/CONTRIBUTOR.rst
  website_sale_product_publish_date/readme/DESCRIPTION.rst
  website_sale_product_publish_date/static/description/index.html
  website_sale_product_publish_date/tests/__init__.py
  website_sale_product_publish_date/tests/test_website_sale_product_publish_date.py
  website_sale_product_publish_date/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1016 [17.0][MIG] website_snippet_product_category: Migration to version 17.0
  website_snippet_product_category/README.rst
  website_snippet_product_category/__init__.py
  website_snippet_product_category/__manifest__.py
  website_snippet_product_category/controllers/__init__.py
  website_snippet_product_category/controllers/website.py
  website_snippet_product_category/demo/demo.xml
  website_snippet_product_category/demo/pages.xml
  website_snippet_product_category/i18n/ca.po
  website_snippet_product_category/i18n/es.po
  website_snippet_product_category/i18n/fr.po
  website_snippet_product_category/i18n/it.po
  website_snippet_product_category/i18n/nl.po
  website_snippet_product_category/i18n/website_snippet_product_category.pot
  website_snippet_product_category/models/__init__.py
  website_snippet_product_category/models/product_public_category.py
  website_snippet_product_category/pyproject.toml
  website_snippet_product_category/readme/CONFIGURE.md
  website_snippet_product_category/readme/CONTRIBUTORS.md
  website_snippet_product_category/readme/CREDITS.md
  website_snippet_product_category/readme/DESCRIPTION.md
  website_snippet_product_category/readme/ROADMAP.md
  website_snippet_product_category/readme/USAGE.md
  website_snippet_product_category/static/description/icon.png
  website_snippet_product_category/static/description/index.html
  website_snippet_product_category/static/img/boxes_32.png
  website_snippet_product_category/static/src/img/s_product_category.png
  website_snippet_product_category/static/src/js/frontend.esm.js
  website_snippet_product_category/static/src/js/snippet.options.esm.js
  website_snippet_product_category/static/src/scss/snippet.scss
  website_snippet_product_category/templates/snippets.xml
  website_snippet_product_category/views/product_public_category.xml
Labels: approved, bot is merging ⏳

#1011 [18.0][MIG] website_sale_hide_empty_category: Migration to version 18.0
  website_sale_hide_empty_category/README.rst
  website_sale_hide_empty_category/__init__.py
  website_sale_hide_empty_category/__manifest__.py
  website_sale_hide_empty_category/i18n/ca.po
  website_sale_hide_empty_category/i18n/es.po
  website_sale_hide_empty_category/i18n/nl.po
  website_sale_hide_empty_category/i18n/website_sale_hide_empty_category.pot
  website_sale_hide_empty_category/models/__init__.py
  website_sale_hide_empty_category/models/product_public_category.py
  website_sale_hide_empty_category/pyproject.toml
  website_sale_hide_empty_category/readme/CONFIGURE.md
  website_sale_hide_empty_category/readme/CONTRIBUTORS.md
  website_sale_hide_empty_category/readme/DESCRIPTION.md
  website_sale_hide_empty_category/readme/USAGE.md
  website_sale_hide_empty_category/static/description/icon.png
  website_sale_hide_empty_category/static/description/index.html
  website_sale_hide_empty_category/static/src/js/tour.esm.js
  website_sale_hide_empty_category/tests/__init__.py
  website_sale_hide_empty_category/tests/test_has_product_recursive.py
  website_sale_hide_empty_category/tests/test_ui.py
  website_sale_hide_empty_category/views/website_sale_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1019 [18.0][MIG] website_sale_order_type: Migration to version 18.0
  website_sale_order_type/README.rst
  website_sale_order_type/__init__.py
  website_sale_order_type/__manifest__.py
  website_sale_order_type/i18n/ca.po
  website_sale_order_type/i18n/es.po
  website_sale_order_type/i18n/it.po
  website_sale_order_type/i18n/website_sale_order_type.pot
  website_sale_order_type/models/__init__.py
  website_sale_order_type/models/website.py
  website_sale_order_type/pyproject.toml
  website_sale_order_type/readme/CONTRIBUTORS.md
  website_sale_order_type/readme/DESCRIPTION.md
  website_sale_order_type/readme/USAGE.md
  website_sale_order_type/static/description/icon.png
  website_sale_order_type/static/description/index.html
  website_sale_order_type/static/tests/tours/website_sale_order_type_tour.esm.js
  website_sale_order_type/tests/__init__.py
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: approved, bot is merging ⏳

#1021 [15.0][ADD] website_sale_partner_restrict_payment_acquirer: New module website_sale_partner_restrict_payment_acquirer
  setup/website_sale_partner_restrict_payment_acquirer/odoo/addons/website_sale_partner_restrict_payment_acquirer
  setup/website_sale_partner_restrict_payment_acquirer/setup.py
  website_sale_partner_restrict_payment_acquirer/README.rst
  website_sale_partner_restrict_payment_acquirer/__init__.py
  website_sale_partner_restrict_payment_acquirer/__manifest__.py
  website_sale_partner_restrict_payment_acquirer/i18n/ca.po
  website_sale_partner_restrict_payment_acquirer/i18n/es.po
  website_sale_partner_restrict_payment_acquirer/i18n/website_sale_partner_restrict_payment_acquirer.pot
  website_sale_partner_restrict_payment_acquirer/models/__init__.py
  website_sale_partner_restrict_payment_acquirer/models/payment_acquirer.py
  website_sale_partner_restrict_payment_acquirer/readme/CONTRIBUTORS.rst
  website_sale_partner_restrict_payment_acquirer/readme/DESCRIPTION.rst
  website_sale_partner_restrict_payment_acquirer/readme/USAGE.rst
  website_sale_partner_restrict_payment_acquirer/static/description/checkout_acquirers.png
  website_sale_partner_restrict_payment_acquirer/static/description/icon.png
  website_sale_partner_restrict_payment_acquirer/static/description/index.html
  website_sale_partner_restrict_payment_acquirer/static/description/partner_form_allowed_acquirers.png
  website_sale_partner_restrict_payment_acquirer/static/description/public_user.png
  website_sale_partner_restrict_payment_acquirer/tests/__init__.py
  website_sale_partner_restrict_payment_acquirer/tests/test_payment_acquirer.py
Labels: approved, ready to merge, bot is merging ⏳

#1024 [17.0][MIG] website_sale_vat_required: Migration to version 17.0
  website_sale_vat_required/README.rst
  website_sale_vat_required/__init__.py
  website_sale_vat_required/__manifest__.py
  website_sale_vat_required/controllers/__init__.py
  website_sale_vat_required/controllers/main.py
  website_sale_vat_required/i18n/ca.po
  website_sale_vat_required/i18n/es.po
  website_sale_vat_required/i18n/it.po
  website_sale_vat_required/i18n/website_sale_vat_required.pot
  website_sale_vat_required/pyproject.toml
  website_sale_vat_required/readme/CONTRIBUTORS.md
  website_sale_vat_required/readme/DESCRIPTION.md
  website_sale_vat_required/readme/USAGE.md
  website_sale_vat_required/static/description/icon.png
  website_sale_vat_required/static/description/index.html
  website_sale_vat_required/static/tests/tours/website_sale_vat_required.esm.js
  website_sale_vat_required/tests/__init__.py
  website_sale_vat_required/tests/test_website_sale_vat_required.py
  website_sale_vat_required/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1028 [16.0][FIX] website_sale_order_type: Remove journal_id definition in tests to avoid side effects
  website_sale_order_type/tests/test_website_sale_order_type.py
Labels: bot is merging ⏳

#1027 [18.0][MIG] website_sale_checkout_country_vat: Migration to version 18.0
  website_sale_checkout_country_vat/README.rst
  website_sale_checkout_country_vat/__init__.py
  website_sale_checkout_country_vat/__manifest__.py
  website_sale_checkout_country_vat/i18n/ca.po
  website_sale_checkout_country_vat/i18n/es.po
  website_sale_checkout_country_vat/i18n/fr.po
  website_sale_checkout_country_vat/i18n/website_sale_checkout_country_vat.pot
  website_sale_checkout_country_vat/pyproject.toml
  website_sale_checkout_country_vat/readme/CONFIGURE.md
  website_sale_checkout_country_vat/readme/CONTRIBUTORS.md
  website_sale_checkout_country_vat/readme/DESCRIPTION.md
  website_sale_checkout_country_vat/readme/USAGE.md
  website_sale_checkout_country_vat/static/description/icon.png
  website_sale_checkout_country_vat/static/description/index.html
  website_sale_checkout_country_vat/static/src/js/dropdown.esm.js
  website_sale_checkout_country_vat/views/templates.xml
Labels: approved, bot is merging ⏳
