Repository OCA/e-commerce, pull requests merged in 2025-03, with the labels that each got.

#1025 [17.0][MIG] website_sale_stock_available: Migration to version 17.0
  website_sale_stock_available/README.rst
  website_sale_stock_available/__init__.py
  website_sale_stock_available/__manifest__.py
  website_sale_stock_available/controllers/__init__.py
  website_sale_stock_available/controllers/main.py
  website_sale_stock_available/i18n/ca.po
  website_sale_stock_available/i18n/es.po
  website_sale_stock_available/i18n/es_AR.po
  website_sale_stock_available/i18n/es_CL.po
  website_sale_stock_available/i18n/fr.po
  website_sale_stock_available/i18n/it.po
  website_sale_stock_available/i18n/nl.po
  website_sale_stock_available/i18n/website_sale_stock_available.pot
  website_sale_stock_available/models/__init__.py
  website_sale_stock_available/models/product_product.py
  website_sale_stock_available/models/product_template.py
  website_sale_stock_available/models/sale_order.py
  website_sale_stock_available/pyproject.toml
  website_sale_stock_available/readme/CONFIGURE.md
  website_sale_stock_available/readme/CONTRIBUTORS.md
  website_sale_stock_available/readme/DESCRIPTION.md
  website_sale_stock_available/readme/USAGE.md
  website_sale_stock_available/static/description/availability_message.png
  website_sale_stock_available/static/description/icon.png
  website_sale_stock_available/static/description/index.html
  website_sale_stock_available/tests/__init__.py
  website_sale_stock_available/tests/test_website_sale_stock_available.py
Labels: approved, ready to merge, bot is merging ⏳

#1029 [18.0][MIG] website_sale_vat_required: Migration to version 18.0
  website_sale_vat_required/README.rst
  website_sale_vat_required/__init__.py
  website_sale_vat_required/__manifest__.py
  website_sale_vat_required/controllers/__init__.py
  website_sale_vat_required/controllers/main.py
  website_sale_vat_required/i18n/ca.po
  website_sale_vat_required/i18n/es.po
  website_sale_vat_required/i18n/it.po
  website_sale_vat_required/i18n/website_sale_vat_required.pot
  website_sale_vat_required/pyproject.toml
  website_sale_vat_required/readme/CONTRIBUTORS.md
  website_sale_vat_required/readme/DESCRIPTION.md
  website_sale_vat_required/readme/USAGE.md
  website_sale_vat_required/static/description/icon.png
  website_sale_vat_required/static/description/index.html
  website_sale_vat_required/static/tests/tours/website_sale_vat_required.esm.js
  website_sale_vat_required/tests/__init__.py
  website_sale_vat_required/tests/test_website_sale_vat_required.py
Labels: approved, ready to merge, bot is merging ⏳

#1007 [17.0][MIG] website_sale_product_minimal_price: Migration to version 17.0
  website_sale_product_minimal_price/README.rst
  website_sale_product_minimal_price/__init__.py
  website_sale_product_minimal_price/__manifest__.py
  website_sale_product_minimal_price/i18n/ca.po
  website_sale_product_minimal_price/i18n/es.po
  website_sale_product_minimal_price/i18n/fr.po
  website_sale_product_minimal_price/i18n/it.po
  website_sale_product_minimal_price/i18n/nl.po
  website_sale_product_minimal_price/i18n/pt.po
  website_sale_product_minimal_price/i18n/website_sale_product_minimal_price.pot
  website_sale_product_minimal_price/models/__init__.py
  website_sale_product_minimal_price/models/product_template.py
  website_sale_product_minimal_price/pyproject.toml
  website_sale_product_minimal_price/readme/CONTRIBUTORS.md
  website_sale_product_minimal_price/readme/DESCRIPTION.md
  website_sale_product_minimal_price/readme/USAGE.md
  website_sale_product_minimal_price/static/description/icon.png
  website_sale_product_minimal_price/static/description/index.html
  website_sale_product_minimal_price/static/src/js/website_sale_product_price_scale.esm.js
  website_sale_product_minimal_price/static/src/tests/tours/test_product_with_no_prices_tour.esm.js
  website_sale_product_minimal_price/static/src/tests/tours/tour.esm.js
  website_sale_product_minimal_price/static/src/xml/website_sale_product_price_scale.xml
  website_sale_product_minimal_price/tests/__init__.py
  website_sale_product_minimal_price/tests/test_product_with_no_prices.py
  website_sale_product_minimal_price/tests/test_website_sale_product_minimal_price.py
  website_sale_product_minimal_price/views/templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#995 [UPD] templates.xml, bootstrap class update
  website_sale_cart_expire/views/templates.xml
Labels: bot is merging ⏳

#1040 [17.0][FIX]website_sale_hide_price:replace t-attf-class with hasclass()
  website_sale_hide_price/views/website_sale_template.xml
Labels: approved, bot is merging ⏳

#1033 [17.0][MIG] website_sale_product_attribute_filter_category: Migration to version 17.0
  website_sale_product_attribute_filter_category/README.rst
  website_sale_product_attribute_filter_category/__init__.py
  website_sale_product_attribute_filter_category/__manifest__.py
  website_sale_product_attribute_filter_category/controllers/__init__.py
  website_sale_product_attribute_filter_category/controllers/main.py
  website_sale_product_attribute_filter_category/i18n/ca.po
  website_sale_product_attribute_filter_category/i18n/es.po
  website_sale_product_attribute_filter_category/i18n/fi.po
  website_sale_product_attribute_filter_category/i18n/nl.po
  website_sale_product_attribute_filter_category/i18n/website_sale_product_attribute_filter_category.pot
  website_sale_product_attribute_filter_category/models/__init__.py
  website_sale_product_attribute_filter_category/models/product_attribute_category.py
  website_sale_product_attribute_filter_category/pyproject.toml
  website_sale_product_attribute_filter_category/readme/CONFIGURE.md
  website_sale_product_attribute_filter_category/readme/CONTRIBUTORS.md
  website_sale_product_attribute_filter_category/readme/DESCRIPTION.md
  website_sale_product_attribute_filter_category/readme/USAGE.md
  website_sale_product_attribute_filter_category/static/description/icon.png
  website_sale_product_attribute_filter_category/static/description/index.html
  website_sale_product_attribute_filter_category/static/src/scss/website_sale_attribute_filter_category.scss
  website_sale_product_attribute_filter_category/static/tests/tours/website_sale_attribute_filter_category_tour.esm.js
  website_sale_product_attribute_filter_category/tests/__init__.py
  website_sale_product_attribute_filter_category/tests/test_website_sale_product_attribute_filter_category.py
  website_sale_product_attribute_filter_category/views/snippets/snippets.xml
  website_sale_product_attribute_filter_category/views/templates.xml
  website_sale_product_attribute_filter_category/views/website_sale_product_attribute_filter_category_view.xml
Labels: approved, ready to merge, bot is merging ⏳
